function rendered = c2837x_block_render_pc_files(project)
%C2837X_BLOCK_RENDER_PC_FILES Render deterministic PC runtime files.

c2837x_block_validate_project_structure(project);
templateRoot = fullfile(fileparts(mfilename('fullpath')), 'templates');
repositoryRoot = fileparts(fileparts(mfilename('fullpath')));
templates = struct( ...
    'error_header', [generated_file_header() ...
        read_template(fullfile(repositoryRoot, 'simulink'), ...
        'c2837x_block_pc_error.h')], ...
    'serial_source', read_template(fullfile(repositoryRoot, 'simulink'), ...
        'c2837x_block_pc_serial.c'), ...
    'serial_header', read_template(fullfile(repositoryRoot, 'simulink'), ...
        'c2837x_block_pc_serial.h'), ...
    'socket_source', read_template(templateRoot, 'pc_socket.c.in'), ...
    'socket_header', read_template(templateRoot, 'pc_socket.h.in'), ...
    'protocol_source', read_template(templateRoot, 'protocol.c.in'), ...
    'protocol_header', read_template(templateRoot, 'protocol.h.in'));
prototype = struct('instance_index', 0, 'internal_name', '', ...
    'pc_error_header_bytes', zeros(1, 0, 'uint8'), ...
    'socket_source_bytes', zeros(1, 0, 'uint8'), ...
    'socket_header_bytes', zeros(1, 0, 'uint8'), ...
    'serial_source_bytes', zeros(1, 0, 'uint8'), ...
    'serial_header_bytes', zeros(1, 0, 'uint8'), ...
    'protocol_source_bytes', zeros(1, 0, 'uint8'), ...
    'protocol_header_bytes', zeros(1, 0, 'uint8'));
rendered = repmat(prototype, 1, numel(project.instances));
for index = 1:numel(project.instances)
    names = c2837x_block_build_instance_c_names( ...
        project.instances(index).internal_name);
    protocolSource = native2unicode(render(templates.protocol_source, names), 'UTF-8');
    protocolHeader = native2unicode(render(templates.protocol_header, names), 'UTF-8');
    isSci = strcmp(char(project.instances(index).iodevice.type), 'sci');
    serialSourceBytes = zeros(1, 0, 'uint8');
    serialHeaderBytes = zeros(1, 0, 'uint8');
    if isSci
        requestedBaud = double(project.instances(index).iodevice.settings.baud);
        clock = c2837x_block_get_sci_clock_config();
        baud = c2837x_block_calculate_sci_baud( ...
            clock.lspclk_hz, requestedBaud);
        [protocolSource, protocolHeader] = bind_sci_protocol( ...
            protocolSource, protocolHeader, names, requestedBaud, ...
            baud.actual_baud);
        [serialSource, serialHeader] = bind_serial_files( ...
            templates.serial_source, templates.serial_header, names);
        serialSourceBytes = text_bytes([generated_file_header() serialSource]);
        serialHeaderBytes = text_bytes([generated_file_header() serialHeader]);
    end
    rendered(index) = struct('instance_index', index, ...
        'internal_name', names.internal_name, ...
        'pc_error_header_bytes', text_bytes(templates.error_header), ...
        'socket_source_bytes', render(templates.socket_source, names), ...
        'socket_header_bytes', render(templates.socket_header, names), ...
        'serial_source_bytes', serialSourceBytes, ...
        'serial_header_bytes', serialHeaderBytes, ...
        'protocol_source_bytes', text_bytes(protocolSource), ...
        'protocol_header_bytes', text_bytes(protocolHeader));
end
end

function bytes = text_bytes(text)
bytes = reshape(uint8(unicode2native(text, 'UTF-8')), 1, []);
end

function [source, header] = bind_sci_protocol( ...
        source, header, names, requestedBaud, actualBaud)
% Bind the one protocol implementation to the production serial API.
header = strrep(header, ...
    ['#include "' names.internal_name '_pc_socket.h"'], ...
    ['#include "' names.internal_name '_pc_serial.h"']);
header = strrep(header, [names.typed_prefix 'PcErrorKind'], ...
    'c2837x_pc_error_kind_t');
header = strrep(header, [names.typed_prefix 'PcError'], ...
    'c2837x_pc_error_t');
header = strrep(header, [names.typed_prefix 'PcSocket'], ...
    'c2837x_pc_serial_t');

source = strrep(source, [names.typed_prefix 'PcErrorKind'], ...
    'c2837x_pc_error_kind_t');
source = strrep(source, [names.typed_prefix 'PcError'], ...
    'c2837x_pc_error_t');
source = strrep(source, [names.typed_prefix 'PcSocket'], ...
    'c2837x_pc_serial_t');
source = strrep(source, [names.typed_prefix 'PcDeadline'], ...
    'c2837x_pc_serial_deadline_t');
source = strrep(source, [names.macro_prefix '_PC_ERROR_'], ...
    'C2837X_PC_ERROR_');
source = strrep(source, [names.internal_name '_pc_error_reset(error, '], ...
    [names.internal_name '_protocol_error_reset(error, ']);
source = strrep(source, [names.internal_name '_pc_socket_close'], ...
    'c2837x_pc_serial_close');
source = strrep(source, [names.internal_name '_pc_socket_send_all_until'], ...
    [names.internal_name '_pc_serial_send_all_until']);
source = strrep(source, [names.internal_name '_pc_socket_recv_exact_until'], ...
    [names.internal_name '_pc_serial_recv_exact_until']);
source = strrep(source, [names.internal_name '_pc_deadline_start'], ...
    [names.internal_name '_pc_serial_deadline_start']);

wrapper = sprintf([ ...
    'static void %s_protocol_error_reset(c2837x_pc_error_t *error,\n' ...
    '    const char *stage)\n' ...
    '{\n' ...
    '    uint32_t available = error != NULL ? error->available : 0u;\n' ...
    '    uint32_t com_number = error != NULL ? error->com_number : 0u;\n' ...
    '    c2837x_pc_error_reset(error, "%s", stage);\n' ...
    '    if ((available & C2837X_PC_ERROR_HAS_COM_NUMBER) != 0u) {\n' ...
    '        c2837x_pc_error_set_com_and_actual_baud(error, com_number, %uu,\n' ...
    '            %.17g);\n' ...
    '    }\n' ...
    '}\n\n' ...
    'static int %s_pc_serial_deadline_start(\n' ...
    '    const c2837x_pc_serial_t *serial, uint32_t timeout_ms,\n' ...
    '    c2837x_pc_serial_deadline_t *deadline, c2837x_pc_error_t *error)\n' ...
    '{\n' ...
    '    c2837x_pc_serial_error_t serial_error;\n' ...
    '    int status;\n' ...
    '    status = c2837x_pc_serial_deadline_start(serial, timeout_ms,\n' ...
    '        deadline, &serial_error);\n' ...
    '    if (status != 0) {\n' ...
    '        c2837x_pc_serial_error_to_pc_error(&serial_error, "%s", NULL,\n' ...
    '            %uu, error);\n' ...
    '        c2837x_pc_error_set_com_and_actual_baud(error,\n' ...
    '            serial != NULL ? serial->com_number : 0u, %uu, %.17g);\n' ...
    '    }\n' ...
    '    return status;\n' ...
    '}\n\n' ...
    'static int %s_pc_serial_send_all_until(c2837x_pc_serial_t *serial,\n' ...
    '    const uint8_t *data, uint32_t length,\n' ...
    '    const c2837x_pc_serial_deadline_t *deadline, c2837x_pc_error_t *error)\n' ...
    '{\n' ...
    '    c2837x_pc_serial_error_t serial_error;\n' ...
    '    int status;\n' ...
    '    c2837x_pc_serial_error_reset(&serial_error, "serial_write");\n' ...
    '    status = c2837x_pc_serial_send_all_until(serial, data, length,\n' ...
    '        deadline, &serial_error);\n' ...
    '    if (status != 0) {\n' ...
    '        c2837x_pc_serial_error_to_pc_error(&serial_error, "%s", NULL,\n' ...
    '            %uu, error);\n' ...
    '        c2837x_pc_error_set_com_and_actual_baud(error,\n' ...
    '            serial != NULL ? serial->com_number : 0u, %uu, %.17g);\n' ...
    '    }\n' ...
    '    return status;\n' ...
    '}\n\n' ...
    'static int %s_pc_serial_recv_exact_until(c2837x_pc_serial_t *serial,\n' ...
    '    uint8_t *data, uint32_t length,\n' ...
    '    const c2837x_pc_serial_deadline_t *deadline, c2837x_pc_error_t *error)\n' ...
    '{\n' ...
    '    c2837x_pc_serial_error_t serial_error;\n' ...
    '    int status;\n' ...
    '    c2837x_pc_serial_error_reset(&serial_error, "serial_read");\n' ...
    '    status = c2837x_pc_serial_recv_exact_until(serial, data, length,\n' ...
    '        deadline, &serial_error);\n' ...
    '    if (status != 0) {\n' ...
    '        c2837x_pc_serial_error_to_pc_error(&serial_error, "%s", NULL,\n' ...
    '            %uu, error);\n' ...
    '        c2837x_pc_error_set_com_and_actual_baud(error,\n' ...
    '            serial != NULL ? serial->com_number : 0u, %uu, %.17g);\n' ...
    '    }\n' ...
    '    return status;\n' ...
    '}\n\n'], names.internal_name, names.internal_name, requestedBaud, ...
    actualBaud, names.internal_name, names.internal_name, requestedBaud, ...
    requestedBaud, actualBaud, names.internal_name, names.internal_name, ...
    requestedBaud, requestedBaud, actualBaud, names.internal_name, ...
    names.internal_name, requestedBaud, requestedBaud, actualBaud);
includeLine = ['#include "' names.internal_name '_protocol.h"' newline newline];
source = strrep(source, includeLine, [includeLine wrapper]);
end

function [source, header] = bind_serial_files(source, header, names)
% Bind the production serial files to this instance's generated closure.
source = strrep(source, '#include "c2837x_block_pc_serial.h"', ...
    ['#include "' names.internal_name '_pc_serial.h"']);
header = strrep(header, '#include "c2837x_block_pc_error.h"', ...
    ['#include "' names.internal_name '_pc_error.h"']);
end

function text = generated_file_header()
text = ['/*' newline ...
    ' * AUTO-GENERATED FILE' newline ...
    ' * Manual changes will be overwritten.' newline ...
    ' */' newline newline];
end

function text = read_template(root, name)
text = fileread(fullfile(root, name));
text = strrep(text, [char(13) newline], newline);
text = strrep(text, char(13), newline);
while ~isempty(text) && text(end) == newline
    text(end) = [];
end
text = [text newline];
end

function bytes = render(template, names)
text = strrep(template, '@NAME@', names.internal_name);
text = strrep(text, '@MACRO@', names.macro_prefix);
text = strrep(text, '@TYPED@', names.typed_prefix);
bytes = reshape(uint8(unicode2native(text, 'UTF-8')), 1, []);
end
