function definition = c2837x_block_iodevice_w5300_udp_definition()
%C2837X_BLOCK_IODEVICE_W5300_UDP_DEFINITION Describe W5300 UDP settings.

definition = struct('type', 'w5300_udp', 'max_instance_count', 8, ...
    'validate_settings', @validate_settings, ...
    'collect_resource_claims', @collect_resource_claims, ...
    'render_project_support', @render_project_support, ...
    'render_instance_config_support', @render_instance_config_support, ...
    'render_instance_io_support', @render_instance_io_support);
end

function support = render_project_support(project)
% TCP owns the canonical shared W5300 project support renderer.
tcpDefinition = c2837x_block_iodevice_w5300_tcp_definition();
support = tcpDefinition.render_project_support(project);
end

function support = render_instance_config_support(project, instanceIndex)
instance = project.instances(instanceIndex);
name = char(instance.internal_name);
macro = upper(name);
socket = double(instance.iodevice.settings.socket_number);
port = double(instance.iodevice.settings.udp_port);
support = struct( ...
    'header_definitions', sprintf([ ...
    '#define %s_W5300_SOCKET_NUMBER  %uu\n' ...
    '#define %s_UDP_PORT             %uu\n'], ...
    macro, socket, macro, port), ...
    'header_checks', sprintf([ ...
    '%s_STATIC_ASSERT(%s_W5300_SOCKET_NUMBER <= 7u, socket_number_out_of_range);\n' ...
    '%s_STATIC_ASSERT(%s_UDP_PORT > 0u && %s_UDP_PORT <= 65535u, udp_port_out_of_range);\n'], ...
    macro, macro, macro, macro, macro), ...
    'source_includes', {{'c2837x_w5300_udp_channel.h'}}, ...
    'source_declarations', sprintf([ ...
    'extern C2837xW5300UdpChannel\n' ...
    '    c2837x_block_%s_iodevice_channel;\n'], name), ...
    'iodevice_ops_expression', '&c2837x_w5300_udp_iodevice_ops', ...
    'iodevice_channel_expression', ...
    ['&c2837x_block_' name '_iodevice_channel']);
end

function support = render_instance_io_support(project, instanceIndex)
name = char(project.instances(instanceIndex).internal_name);
macro = upper(name);
support = struct('source_includes', ...
    {{'c2837x_block_platform.h', 'c2837x_w5300_udp_channel.h'}}, ...
    'source_definitions', sprintf([ ...
    'C2837xW5300UdpChannel\n    c2837x_block_%s_iodevice_channel =\n' ...
    'C2837X_W5300_UDP_CHANNEL_INITIALIZER(\n' ...
    '    %s_W5300_SOCKET_NUMBER,\n    8192u,\n    8192u,\n' ...
    '    %s_UDP_PORT,\n    c2837x_block_time_us,\n' ...
    '    %s_TRANSFER_TIMEOUT_US);\n'], name, macro, macro, macro));
end

function issues = validate_settings(settings, instanceIndex)
issues = empty_issues();
prefix = sprintf('project.instances(%u).iodevice.settings.', instanceIndex);
if ~valid_field(settings, 'socket_number', 0, 7)
    issues(end + 1) = issue('SOCKET_INVALID', ...
        'Socket number must be an integer from 0 to 7.', ...
        [prefix 'socket_number'], instanceIndex);
end
if ~valid_field(settings, 'udp_port', 1, 65535)
    issues(end + 1) = issue('UDP_PORT_INVALID', ...
        'UDP port must be an integer from 1 to 65535.', ...
        [prefix 'udp_port'], instanceIndex);
end
end

function claims = collect_resource_claims(settings, instanceIndex)
prototype = struct('scope', '', 'kind', '', 'key', '', 'exclusive', false, ...
    'duplicate_code', '', 'duplicate_message', '', 'field_path', '', ...
    'instance_index', 0);
claims = repmat(prototype, 1, 0);
prefix = sprintf('project.instances(%u).iodevice.settings.', instanceIndex);
if valid_field(settings, 'socket_number', 0, 7)
    claims(end + 1) = claim('project:w5300', 'socket', ...
        settings.socket_number, 'SOCKET_DUPLICATE', ...
        'Socket number is already used.', [prefix 'socket_number'], ...
        instanceIndex);
end
if valid_field(settings, 'udp_port', 1, 65535)
    claims(end + 1) = claim('project:w5300_udp', 'udp_port', ...
        settings.udp_port, 'UDP_PORT_DUPLICATE', ...
        'UDP port is already used.', [prefix 'udp_port'], instanceIndex);
end
end

function value = claim(scope, kind, key, code, message, fieldPath, instanceIndex)
value = struct('scope', scope, 'kind', kind, ...
    'key', sprintf('%.0f', double(key)), 'exclusive', true, ...
    'duplicate_code', code, 'duplicate_message', message, ...
    'field_path', fieldPath, 'instance_index', instanceIndex);
end

function value = issue(code, message, fieldPath, instanceIndex)
value = struct('severity', 'Error', 'code', code, 'message', message, ...
    'field_path', fieldPath, 'instance_index', instanceIndex, 'file_path', '');
end

function values = empty_issues()
values = struct('severity', {}, 'code', {}, 'message', {}, ...
    'field_path', {}, 'instance_index', {}, 'file_path', {});
end

function tf = is_integer_in_range(value, minimum, maximum)
tf = isnumeric(value) && isscalar(value) && isreal(value) && ...
    isfinite(value) && value == fix(value) && value >= minimum && value <= maximum;
end

function tf = valid_field(settings, name, minimum, maximum)
tf = isstruct(settings) && isscalar(settings) && isfield(settings, name) && ...
    is_integer_in_range(settings.(name), minimum, maximum);
end
