function iodevice = c2837x_block_create_iodevice(type)
%C2837X_BLOCK_CREATE_IODEVICE Create canonical persisted IoDevice defaults.

type = char(string(type));
switch type
    case 'w5300_tcp'
        settings = struct( ...
            'socket_number', uint16(0), ...
            'tcp_port', uint16(5000));
    case 'sci'
        settings = struct( ...
            'module', '', ...
            'baud', uint32(57600), ...
            'rx_gpio', '', ...
            'tx_gpio', '', ...
            'rx_pin_type', 'Pull-up', ...
            'rx_qualification', 'Async', ...
            'tx_pin_type', 'Pull-up', ...
            'ctrl_gpio', 'None', ...
            'ctrl_pin_type', 'Standard', ...
            'ctrl_tx_active_level', 'High');
    otherwise
        error('C2837xBlock:IoDevice:UnsupportedType', ...
            'IoDevice type "%s" has no production default.', type);
end
iodevice = struct('type', type, 'settings', settings);
end
