function rendered = c2837x_block_render_sfun_build_files(project)
%C2837X_BLOCK_RENDER_SFUN_BUILD_FILES Render S4-05 user and build files.

c2837x_block_validate_project_structure(project);
prototype = struct('instance_index', 0, 'internal_name', '', ...
    'user_config_bytes', zeros(1, 0, 'uint8'), ...
    'build_script_bytes', zeros(1, 0, 'uint8'));
rendered = repmat(prototype, 1, numel(project.instances));
for index = 1:numel(project.instances)
    instance = project.instances(index);
    names = c2837x_block_build_instance_c_names(instance.internal_name);
    rendered(index) = struct('instance_index', index, ...
        'internal_name', names.internal_name, ...
        'user_config_bytes', text_bytes(user_config(names)), ...
        'build_script_bytes', text_bytes(build_script( ...
            names, project.common.protocol_version, instance.interface_hash)));
end
end

function text = user_config(names)
guard = [names.macro_prefix '_SFUN_USER_CONFIG_H'];
lines = { ...
    '/*', ...
    ' * USER-EDITABLE FILE', ...
    ' * Existing contents are preserved by default.', ...
    ' */', ...
    '', ...
    sprintf('#ifndef %s', guard), ...
    sprintf('#define %s', guard), ...
    '', ...
    '#define CONNECT_TIMEOUT_MS     5000u', ...
    '#define STEP_TIMEOUT_MS        1000u', ...
    '#define TERMINATE_TIMEOUT_MS    200u', ...
    '', ...
    sprintf('#endif /* %s */', guard)};
text = strjoin(lines, newline);
end

function text = build_script(names, protocolVersion, interfaceHash)
name = names.internal_name;
mexName = [name '_sfun'];
lines = { ...
    '% AUTO-GENERATED FILE', ...
    '% Manual changes will be overwritten.', ...
    '', ...
    sprintf('build_%s_sfun_local();', name), ...
    '', ...
    sprintf('function build_%s_sfun_local()', name), ...
    'script_path = mfilename(''fullpath'');', ...
    'script_dir = fileparts(script_path);', ...
    'if isempty(script_path) || ~isfolder(script_dir)', ...
    '    error(''C2837xBlock:MexBuild:InvalidScriptDirectory'', ...', ...
    '        ''The build script directory does not exist: %s'', script_dir);', ...
    'end', ...
    '', ...
    sprintf('mex_name = ''%s'';', mexName), ...
    'mex_path = fullfile(script_dir, [mex_name ''.'' mexext]);', ...
    'source_files = { ...', ...
    sprintf('    fullfile(script_dir, ''%s_sfun.c'')', name), ...
    sprintf('    fullfile(script_dir, ''%s_sfun_io.c'')', name), ...
    sprintf('    fullfile(script_dir, ''%s_pc_socket.c'')', name), ...
    sprintf('    fullfile(script_dir, ''%s_protocol.c'')', name), ...
    '};', ...
    'header_files = { ...', ...
    sprintf('    fullfile(script_dir, ''%s_sfun.h'')', name), ...
    sprintf('    fullfile(script_dir, ''%s_sfun_config.h'')', name), ...
    sprintf('    fullfile(script_dir, ''%s_sfun_user_config.h'')', name), ...
    sprintf('    fullfile(script_dir, ''%s_pc_socket.h'')', name), ...
    sprintf('    fullfile(script_dir, ''%s_protocol.h'')', name), ...
    '};', ...
    '', ...
    'probe_path = [tempname(script_dir) ''.tmp''];', ...
    'if isfile(probe_path) || isfolder(probe_path)', ...
    '    error(''C2837xBlock:MexBuild:ProbeCollision'', ...', ...
    '        ''Writable probe path already exists: %s'', probe_path);', ...
    'end', ...
    'probe_cleanup = onCleanup(@() delete_if_file(probe_path));', ...
    '[probe_id, probe_message] = fopen(probe_path, ''w'');', ...
    'if probe_id < 0', ...
    '    error(''C2837xBlock:MexBuild:DirectoryNotWritable'', ...', ...
    '        ''Cannot write to script directory %s: %s'', script_dir, probe_message);', ...
    'end', ...
    'if fclose(probe_id) ~= 0', ...
    '    error(''C2837xBlock:MexBuild:ProbeCloseFailed'', ...', ...
    '        ''Cannot close writable probe: %s'', probe_path);', ...
    'end', ...
    'delete(probe_path);', ...
    'clear probe_cleanup', ...
    'if isfile(probe_path)', ...
    '    error(''C2837xBlock:MexBuild:ProbeDeleteFailed'', ...', ...
    '        ''Writable probe could not be removed: %s'', probe_path);', ...
    'end', ...
    '', ...
    'required_files = [source_files; header_files];', ...
    'for file_index = 1:numel(required_files)', ...
    '    if ~isfile(required_files{file_index})', ...
    '        error(''C2837xBlock:MexBuild:MissingFile'', ...', ...
    '            ''Required build file not found: %s'', required_files{file_index});', ...
    '    end', ...
    'end', ...
    'if exist(''mex'', ''file'') == 0', ...
    '    error(''C2837xBlock:MexBuild:MexUnavailable'', ...', ...
    '        ''mex is unavailable in this MATLAB installation.'');', ...
    'end', ...
    'simulink_info = ver(''simulink'');', ...
    'simstruc_path = fullfile(matlabroot, ''simulink'', ''include'', ''simstruc.h'');', ...
    'if isempty(simulink_info) || ~isfile(simstruc_path)', ...
    '    error(''C2837xBlock:MexBuild:SimulinkUnavailable'', ...', ...
    '        ''Simulink and its simstruc.h header are required.'');', ...
    'end', ...
    'compiler = mex.getCompilerConfigurations(''C'', ''Selected'');', ...
    'if isempty(compiler)', ...
    '    error(''C2837xBlock:MexBuild:CompilerUnavailable'', ...', ...
    '        [''No supported C MEX compiler is selected. Run mex -setup C '' ...', ...
    '         ''or configure a compiler supported by this MATLAB release.'']);', ...
    'end', ...
    'mex_args = [{''-v'', ''-outdir'', script_dir, ''-output'', mex_name, ...', ...
    '    [''-I'' script_dir]} source_files''];', ...
    'if ispc', ...
    '    if contains(compiler.Name, ''MinGW'', ''IgnoreCase'', true)', ...
    '        mingw_library_dir = fullfile(compiler.Location, ...', ...
    '            ''x86_64-w64-mingw32'', ''lib'');', ...
    '        mingw_socket_library = fullfile(mingw_library_dir, ''libws2_32.a'');', ...
    '        if ~isfile(mingw_socket_library)', ...
    '            error(''C2837xBlock:MexBuild:SocketLibraryUnavailable'', ...', ...
    '                ''MinGW WinSock library not found: %s'', mingw_socket_library);', ...
    '        end', ...
    '        mex_args{end + 1} = [''-L'' mingw_library_dir];', ...
    '        mex_args{end + 1} = ''-lws2_32'';', ...
    '    else', ...
    '        mex_args{end + 1} = ''ws2_32.lib'';', ...
    '    end', ...
    'elseif ~isunix', ...
    '    error(''C2837xBlock:MexBuild:UnsupportedPlatform'', ...', ...
    '        ''Only Windows and POSIX platforms are supported.'');', ...
    'end', ...
    '', ...
    '[~, mex_paths] = inmem(''-completenames'');', ...
    'loaded_paths = matching_mex_paths(mex_paths, mex_name);', ...
    'foreign_paths = loaded_paths(~cellfun(@(value) same_path(value, mex_path), loaded_paths));', ...
    'if ~isempty(foreign_paths)', ...
    '    error(''C2837xBlock:MexBuild:ForeignMexLoaded'', ...', ...
    '        [''A same-name MEX for %s is loaded from another directory. '' ...', ...
    '         ''Expected: %s. Loaded: %s''], mex_name, mex_path, foreign_paths{1});', ...
    'end', ...
    '', ...
    sprintf('clear %s', mexName), ...
    '[~, mex_paths_after_clear] = inmem(''-completenames'');', ...
    'loaded_paths_after_clear = matching_mex_paths(mex_paths_after_clear, mex_name);', ...
    'if ~isempty(loaded_paths_after_clear) || mislocked(mex_name)', ...
    '    error(''C2837xBlock:MexBuild:MexStillLoaded'', ...', ...
    '        [''The target MEX is still loaded or locked: %s. Stop the simulation '' ...', ...
    '         ''or model using this S-Function before rebuilding.''], mex_path);', ...
    'end', ...
    'if isfile(mex_path)', ...
    '    try', ...
    '        delete(mex_path);', ...
    '    catch cause', ...
    '        failure = MException(''C2837xBlock:MexBuild:DeleteFailed'', ...', ...
    '            [''Cannot delete target MEX %s. Stop simulations and programs '' ...', ...
    '             ''using it, then check file permissions.''], mex_path);', ...
    '        failure = addCause(failure, cause);', ...
    '        throw(failure);', ...
    '    end', ...
    '    if isfile(mex_path)', ...
    '        error(''C2837xBlock:MexBuild:DeleteFailed'', ...', ...
    '            ''Target MEX still exists after deletion: %s'', mex_path);', ...
    '    end', ...
    'end', ...
    '', ...
    'try', ...
    '    mex(mex_args{:});', ...
    'catch cause', ...
    '    cleanup_failure = [];', ...
    '    if isfile(mex_path)', ...
    '        try', ...
    '            delete(mex_path);', ...
    '        catch cleanup_cause', ...
    '            cleanup_failure = cleanup_cause;', ...
    '        end', ...
    '    end', ...
    '    fprintf(2, ''MEX build failed: %s\n'', cause.message);', ...
    '    if ~isempty(cleanup_failure) || isfile(mex_path)', ...
    '        failure = MException(''C2837xBlock:MexBuild:FailureCleanupFailed'', ...', ...
    '            ''Build failed and partial target cleanup failed: %s'', mex_path);', ...
    '        failure = addCause(failure, cause);', ...
    '        if ~isempty(cleanup_failure)', ...
    '            failure = addCause(failure, cleanup_failure);', ...
    '        end', ...
    '        throw(failure);', ...
    '    end', ...
    '    rethrow(cause);', ...
    'end', ...
    'if ~isfile(mex_path)', ...
    '    error(''C2837xBlock:MexBuild:MissingOutput'', ...', ...
    '        ''mex returned without creating the target: %s'', mex_path);', ...
    'end', ...
    sprintf('fprintf(''MEX Name: %%s.%%s\\n'', mex_name, mexext);'), ...
    'fprintf(''MEX Path: %s\n'', mex_path);', ...
    sprintf('fprintf(''Protocol Version: %u\\n'');', double(protocolVersion)), ...
    sprintf('fprintf(''Interface Hash: 0x%08X\\n'');', uint32(interfaceHash)), ...
    'end', ...
    '', ...
    'function paths = matching_mex_paths(mex_paths, mex_name)', ...
    'paths = cell(0, 1);', ...
    'for path_index = 1:numel(mex_paths)', ...
    '    candidate = normalize_existing_path(mex_paths{path_index});', ...
    '    [~, candidate_name] = fileparts(candidate);', ...
    '    if same_name(candidate_name, mex_name)', ...
    '        paths{end + 1, 1} = candidate; %#ok<AGROW>', ...
    '    end', ...
    'end', ...
    'end', ...
    '', ...
    'function result = same_path(first, second)', ...
    'first = normalize_existing_path(first);', ...
    'second = normalize_existing_path(second);', ...
    'if ispc', ...
    '    result = strcmpi(first, second);', ...
    'else', ...
    '    result = strcmp(first, second);', ...
    'end', ...
    'end', ...
    '', ...
    'function result = same_name(first, second)', ...
    'if ispc', ...
    '    result = strcmpi(first, second);', ...
    'else', ...
    '    result = strcmp(first, second);', ...
    'end', ...
    'end', ...
    '', ...
    'function path = normalize_existing_path(path)', ...
    '[exists, attributes] = fileattrib(path);', ...
    'if exists', ...
    '    path = attributes.Name;', ...
    'end', ...
    'end', ...
    '', ...
    'function delete_if_file(path)', ...
    'if isfile(path)', ...
    '    delete(path);', ...
    'end', ...
    'end'};
text = strjoin(lines, newline);
end

function bytes = text_bytes(text)
text = strrep(text, [char(13) newline], newline);
text = strrep(text, char(13), newline);
while ~isempty(text) && text(end) == newline
    text(end) = [];
end
bytes = reshape(uint8(unicode2native([text newline], 'UTF-8')), 1, []);
end
