function [str, hash] = c2837x_block_build_hash_string(config)
%C2837X_BLOCK_BUILD_HASH_STRING Deprecated compatibility entry point.
%
%   [str, hash] = c2837x_block_build_hash_string(config)
%
%   Delegates exclusively to the V2 Interface Hash service.

if ~isstruct(config) || ~isscalar(config) || ...
        ~all(isfield(config, {'protocol_version', 'inputs', 'outputs', ...
        'max_payload_size_bytes'}))
    error('C2837xBlock:InterfaceHash:InvalidProject', ...
        'config is missing required Interface Hash input.');
end

instance = struct( ...
    'inputs', config.inputs, ...
    'outputs', config.outputs, ...
    'max_payload_size_bytes', config.max_payload_size_bytes);
project = struct( ...
    'common', struct('protocol_version', config.protocol_version), ...
    'instances', instance);
[str, hash] = c2837x_block_build_interface_hash(project, 1);
end
