function claims = c2837x_block_get_platform_reserved_resources(project)
%C2837X_BLOCK_GET_PLATFORM_RESERVED_RESOURCES Return active fixed resources.

prototype = struct('scope', '', 'kind', '', 'key', '', 'exclusive', false, ...
    'duplicate_code', '', 'duplicate_message', '', 'field_path', '', ...
    'instance_index', 0);
claims = repmat(prototype, 1, 0);
if isempty(project.instances) || ~any(arrayfun(@(instance) ...
        strcmp(char(instance.iodevice.type), 'w5300_tcp'), project.instances))
    return;
end

gpioNumbers = [28 31 37:41 44:52 69:83 85:93 99];
claims = repmat(prototype, 1, numel(gpioNumbers));
for index = 1:numel(gpioNumbers)
    number = gpioNumbers(index);
    claims(index) = struct('scope', 'project:gpio', 'kind', 'gpio', ...
        'key', sprintf('%u', number), 'exclusive', true, ...
        'duplicate_code', 'GPIO_RESOURCE_CONFLICT', ...
        'duplicate_message', sprintf( ...
        'GPIO%u is reserved by active W5300 platform hardware.', number), ...
        'field_path', 'project.instances', 'instance_index', 0);
end
end
