function instance = c2837x_block_create_default_instance()
%C2837X_BLOCK_CREATE_DEFAULT_INSTANCE Create a default V3 project instance.

variables = struct('name', {}, 'type', {}, 'dim', {});
instance = struct( ...
    'display_name', '', ...
    'internal_name', '', ...
    'iodevice', c2837x_block_create_iodevice('w5300_tcp'), ...
    'sample_time_sec', 1e-4, ...
    'max_payload_size_bytes', uint32(1024), ...
    'inputs', variables, ...
    'outputs', variables, ...
    'algorithm', struct( ...
        'mode', 'generated_example', ...
        'source_path', ''), ...
    'interface_hash', uint32(0));
end
