function rendered = c2837x_block_render_sfun_files(project)
%C2837X_BLOCK_RENDER_SFUN_FILES Render deterministic S4-01 templates.

c2837x_block_validate_project_structure(project);
prototype = struct('instance_index', 0, 'internal_name', '', ...
    'sfun_source_bytes', zeros(1, 0, 'uint8'), ...
    'sfun_header_bytes', zeros(1, 0, 'uint8'), ...
    'io_source_bytes', zeros(1, 0, 'uint8'), ...
    'config_header_bytes', zeros(1, 0, 'uint8'));
rendered = repmat(prototype, 1, numel(project.instances));
for index = 1:numel(project.instances)
    instance = project.instances(index);
    names = c2837x_block_build_instance_c_names(instance.internal_name);
    validate_instance(instance);
    rendered(index) = struct('instance_index', index, ...
        'internal_name', names.internal_name, ...
        'sfun_source_bytes', text_bytes(sfun_source(names)), ...
        'sfun_header_bytes', text_bytes(sfun_header(names)), ...
        'io_source_bytes', text_bytes(io_source(names, instance)), ...
        'config_header_bytes', text_bytes(config_header(names, instance)));
end
end

function text = sfun_source(names)
name = names.internal_name;
typed = names.typed_prefix;
text = sprintf([ ...
    '#define S_FUNCTION_NAME %s_sfun\n' ...
    '#define S_FUNCTION_LEVEL 2\n\n' ...
    '#include "simstruc.h"\n' ...
    '#include "%s_sfun_config.h"\n' ...
    '#include "%s_sfun.h"\n\n' ...
    '#include <stdlib.h>\n\n' ...
    '%sSfunContext *%s_sfun_create_context(void)\n' ...
    '{\n    return (%sSfunContext *)calloc(1u, sizeof(%sSfunContext));\n}\n\n' ...
    'void %s_sfun_destroy_context(%sSfunContext *context)\n' ...
    '{\n    free(context);\n}\n\n' ...
    'static void mdlInitializeSizes(SimStruct *S)\n{\n' ...
    '    ssSetNumSFcnParams(S, 0);\n' ...
    '    if (ssGetNumSFcnParams(S) != ssGetSFcnParamsCount(S)) {\n' ...
    '        return;\n    }\n' ...
    '    if (%s_sfun_setup_input_ports(S) != 0 ||\n' ...
    '            %s_sfun_setup_output_ports(S) != 0) {\n' ...
    '        ssSetErrorStatus(S, "%s_sfun: failed to configure ports.");\n' ...
    '        return;\n    }\n' ...
    '    ssSetNumSampleTimes(S, 1);\n' ...
    '    ssSetNumPWork(S, 1);\n' ...
    '    ssSetOptions(S, SS_OPTION_EXCEPTION_FREE_CODE);\n}\n\n' ...
    'static void mdlInitializeSampleTimes(SimStruct *S)\n{\n' ...
    '    ssSetSampleTime(S, 0, %s_SFUN_SAMPLE_TIME_SEC);\n' ...
    '    ssSetOffsetTime(S, 0, 0.0);\n}\n\n' ...
    '#define MDL_START\n' ...
    'static void mdlStart(SimStruct *S)\n{\n' ...
    '    %sSfunContext *context = %s_sfun_create_context();\n' ...
    '    if (context == NULL) {\n' ...
    '        ssSetErrorStatus(S, "%s_sfun: failed to allocate context.");\n' ...
    '        return;\n    }\n' ...
    '    ssSetPWorkValue(S, 0, context);\n}\n\n' ...
    'static void mdlOutputs(SimStruct *S, int_T tid)\n{\n' ...
    '    (void)tid;\n' ...
    '    ssSetErrorStatus(S, "%s_sfun: communication is not implemented by S4-01.");\n' ...
    '}\n\n' ...
    'static void mdlTerminate(SimStruct *S)\n{\n' ...
    '    %sSfunContext *context = (%sSfunContext *)ssGetPWorkValue(S, 0);\n' ...
    '    %s_sfun_destroy_context(context);\n' ...
    '    ssSetPWorkValue(S, 0, NULL);\n}\n\n' ...
    '#ifndef MATLAB_MEX_FILE\n' ...
    '#error "%s_sfun supports MATLAB MEX Normal mode only."\n' ...
    '#else\n#include "simulink.c"\n#endif\n'], ...
    name, name, name, typed, name, typed, typed, name, typed, ...
    name, name, name, names.macro_prefix, typed, name, name, name, ...
    typed, typed, name, name);
end

function text = sfun_header(names)
guard = [names.macro_prefix '_SFUN_H'];
text = sprintf([ ...
    '#ifndef %s\n#define %s\n\n' ...
    '#include "simstruc.h"\n\n' ...
    '#ifdef __cplusplus\nextern "C" {\n#endif\n\n' ...
    'typedef struct\n{\n    unsigned int reserved;\n} %sSfunContext;\n\n' ...
    '%sSfunContext *%s_sfun_create_context(void);\n' ...
    'void %s_sfun_destroy_context(%sSfunContext *context);\n' ...
    'int %s_sfun_setup_input_ports(SimStruct *S);\n' ...
    'int %s_sfun_setup_output_ports(SimStruct *S);\n\n' ...
    '#ifdef __cplusplus\n}\n#endif\n\n' ...
    '#endif /* %s */\n'], guard, guard, names.typed_prefix, ...
    names.typed_prefix, names.internal_name, names.internal_name, ...
    names.typed_prefix, names.internal_name, names.internal_name, guard);
end

function text = io_source(names, instance)
name = names.internal_name;
macro = names.macro_prefix;
inputLines = port_lines(instance.inputs, 'Input', macro);
outputLines = port_lines(instance.outputs, 'Output', macro);
text = sprintf([ ...
    '#include "simstruc.h"\n' ...
    '#include "%s_sfun_config.h"\n' ...
    '#include "%s_sfun.h"\n\n' ...
    'int %s_sfun_setup_input_ports(SimStruct *S)\n{\n' ...
    '    if (!ssSetNumInputPorts(S, %s_SFUN_INPUT_PORT_COUNT)) {\n' ...
    '        return -1;\n    }\n%s' ...
    '    return 0;\n}\n\n' ...
    'int %s_sfun_setup_output_ports(SimStruct *S)\n{\n' ...
    '    if (!ssSetNumOutputPorts(S, %s_SFUN_OUTPUT_PORT_COUNT)) {\n' ...
    '        return -1;\n    }\n%s' ...
    '    return 0;\n}\n'], name, name, name, macro, inputLines, ...
    name, macro, outputLines);
end

function lines = port_lines(variables, direction, macro)
lines = '';
upperDirection = upper(direction);
for index = 1:numel(variables)
    port = index - 1;
    variable = variables(index);
    lines = [lines sprintf('    /* Port %u: %s */\n', port, char(variable.name))]; %#ok<AGROW>
    lines = [lines sprintf('    ssSet%sPortWidth(S, %u, %s_SFUN_%s_%u_WIDTH);\n', ...
        direction, port, macro, upperDirection, port)]; %#ok<AGROW>
    lines = [lines sprintf('    ssSet%sPortDataType(S, %u, %s_SFUN_%s_%u_DATA_TYPE);\n', ...
        direction, port, macro, upperDirection, port)]; %#ok<AGROW>
    if strcmp(direction, 'Input')
        lines = [lines sprintf( ...
            '    ssSetInputPortDirectFeedThrough(S, %u, 1);\n', port)]; %#ok<AGROW>
        lines = [lines sprintf( ...
            '    ssSetInputPortRequiredContiguous(S, %u, 1);\n', port)]; %#ok<AGROW>
    end
end
end

function text = config_header(names, instance)
macro = names.macro_prefix;
guard = [macro '_SFUN_CONFIG_H'];
lines = { ...
    sprintf('#ifndef %s', guard), sprintf('#define %s', guard), '', ...
    '/* AUTO-GENERATED FILE. Manual changes will be overwritten. */', '', ...
    sprintf('#define %s_SFUN_FUNCTION_NAME %s_sfun', macro, names.internal_name), ...
    sprintf('#define %s_SFUN_MEX_BASENAME "%s_sfun"', macro, names.internal_name), ...
    sprintf('#define %s_SFUN_SAMPLE_TIME_SEC (%.17g)', macro, double(instance.sample_time_sec)), ...
    sprintf('#define %s_SFUN_INPUT_PORT_COUNT %uu', macro, numel(instance.inputs)), ...
    sprintf('#define %s_SFUN_OUTPUT_PORT_COUNT %uu', macro, numel(instance.outputs)), ''};
lines = [lines variable_macros(instance.inputs, 'INPUT', macro), ...
    variable_macros(instance.outputs, 'OUTPUT', macro), ...
    {sprintf('#if defined(__STDC_VERSION__) && (__STDC_VERSION__ >= 201112L)'), ...
    sprintf('#define %s_SFUN_STATIC_ASSERT(c_, n_) _Static_assert((c_), #n_)', macro), ...
    '#else', ...
    sprintf('#define %s_SFUN_STATIC_ASSERT(c_, n_) typedef char %s_sfun_static_assert_##n_[(c_) ? 1 : -1]', ...
        macro, lower(macro)), ...
    '#endif', '', ...
    sprintf('%s_SFUN_STATIC_ASSERT(%s_SFUN_SAMPLE_TIME_SEC > 0.0, sample_time_positive);', macro, macro), ...
    sprintf('%s_SFUN_STATIC_ASSERT(%s_SFUN_INPUT_PORT_COUNT > 0u, input_port_count_positive);', macro, macro), ...
    sprintf('%s_SFUN_STATIC_ASSERT(%s_SFUN_OUTPUT_PORT_COUNT > 0u, output_port_count_positive);', macro, macro)}, ...
    variable_asserts(instance.inputs, 'INPUT', macro), ...
    variable_asserts(instance.outputs, 'OUTPUT', macro), ...
    {'', sprintf('#endif /* %s */', guard)}];
text = strjoin(lines, newline);
end

function lines = variable_macros(variables, direction, macro)
lines = cell(1, 2 * numel(variables) + 1);
cursor = 0;
for index = 1:numel(variables)
    port = index - 1;
    cursor = cursor + 1;
    lines{cursor} = sprintf('#define %s_SFUN_%s_%u_WIDTH %uu', ...
        macro, direction, port, double(variables(index).dim));
    cursor = cursor + 1;
    lines{cursor} = sprintf('#define %s_SFUN_%s_%u_DATA_TYPE %s', ...
        macro, direction, port, simulink_type(variables(index).type));
end
lines{end} = '';
end

function lines = variable_asserts(variables, direction, macro)
lines = cell(1, numel(variables));
for index = 1:numel(variables)
    port = index - 1;
    lines{index} = sprintf( ...
        '%s_SFUN_STATIC_ASSERT(%s_SFUN_%s_%u_WIDTH > 0u, %s_%u_width_positive);', ...
        macro, macro, direction, port, lower(direction), port);
end
end

function value = simulink_type(type)
switch char(type)
    case 'int16', value = 'SS_INT16';
    case 'uint16', value = 'SS_UINT16';
    case 'int32', value = 'SS_INT32';
    case 'uint32', value = 'SS_UINT32';
    case 'single', value = 'SS_SINGLE';
    case 'double', value = 'SS_DOUBLE';
    otherwise
        error('C2837xBlock:SfunRender:UnsupportedType', ...
            'Unsupported S-Function port type "%s".', char(type));
end
end

function validate_instance(instance)
if ~isnumeric(instance.sample_time_sec) || ~isreal(instance.sample_time_sec) || ...
        ~isscalar(instance.sample_time_sec) || ~isfinite(instance.sample_time_sec) || ...
        instance.sample_time_sec <= 0
    error('C2837xBlock:SfunRender:InvalidSampleTime', ...
        'S-Function sample time must be a finite positive scalar.');
end
validate_variables(instance.inputs);
validate_variables(instance.outputs);
end

function validate_variables(variables)
if isempty(variables)
    error('C2837xBlock:SfunRender:EmptyPorts', ...
        'S4-01 requires at least one input and one output port.');
end
for index = 1:numel(variables)
    simulink_type(variables(index).type);
    dim = variables(index).dim;
    if ~isnumeric(dim) || ~isreal(dim) || ~isscalar(dim) || ...
            ~isfinite(dim) || dim <= 0 || dim ~= fix(dim)
        error('C2837xBlock:SfunRender:InvalidPortWidth', ...
            'S-Function port widths must be finite positive integers.');
    end
end
end

function bytes = text_bytes(text)
text = strrep(text, [char(13) newline], newline);
text = strrep(text, char(13), newline);
while ~isempty(text) && text(end) == newline
    text(end) = [];
end
bytes = reshape(uint8(unicode2native([text newline], 'UTF-8')), 1, []);
end
