function project = c2837x_block_create_default_project()
%C2837X_BLOCK_CREATE_DEFAULT_PROJECT Create an empty default V4 project.

instance = c2837x_block_create_default_instance();
project = struct( ...
    'format_version', uint16(4), ...
    'common', struct( ...
        'dsp_model', 'TMS320F28377D', ...
        'package', 'PTP', ...
        'protocol_version', uint16(1), ...
        'abi', 'eabi', ...
        'network', struct( ...
            'mac', uint8([0 8 220 1 2 3]), ...
            'ip', '192.168.1.100', ...
            'gateway', '192.168.1.1', ...
            'subnet', '255.255.255.0')), ...
    'instances', instance([]), ...
    'output', struct( ...
        'dsp_root', '', ...
        'sfun_root', ''));
end
