function model = c2837x_block_build_dsp_output_model(project)
%C2837X_BLOCK_BUILD_DSP_OUTPUT_MODEL Describe the complete DSP output tree.

c2837x_block_validate_project_structure(project);
dspRoot = canonical_root(project.output.dsp_root);
appRoot = fileparts(mfilename('fullpath'));
repositoryRoot = fileparts(appRoot);

prototype = struct('relative_path', '', 'target_path', '', 'category', '', ...
    'owner', '', 'instance_index', 0, 'file_scope', '', ...
    'responsibility', '', 'source_path', '', 'candidate_available', false);
files = repmat(prototype, 1, 19 + 6 * numel(project.instances));
fileCount = 0;

corePaths = { ...
    'inc/c2837x_block.h', ...
    'inc/c2837x_block_protocol.h', ...
    'inc/c2837x_block_iodevice.h', ...
    'inc/c2837x_w5300_regs.h', ...
    'inc/c2837x_w5300_hal.h', ...
    'inc/c2837x_w5300_socket.h', ...
    'inc/c2837x_w5300_channel.h', ...
    'src/c2837x_block.c', ...
    'src/c2837x_block_protocol.c', ...
    'src/c2837x_block_internal.h', ...
    'src/c2837x_block_config_internal.h', ...
    'src/c2837x_block_platform.h', ...
    'src/c2837x_block_platform.c', ...
    'src/c2837x_block_timer2.c', ...
    'src/c2837x_w5300_hal.c', ...
    'src/c2837x_w5300_socket.c', ...
    'src/c2837x_w5300_channel.c'};
for index = 1:numel(corePaths)
    relativePath = corePaths{index};
    sourceParts = strsplit_path(relativePath);
    fileCount = fileCount + 1;
    files(fileCount) = make_file(relativePath, 'core', ...
        ['dsp-core:' relativePath], 0, 'core', ...
        'DSP-SimBridge public Core source.', ...
        fullfile(repositoryRoot, 'dsp', sourceParts{:}), true);
end

fileCount = fileCount + 1;
files(fileCount) = make_file('inc/c2837x_block_project.h', ...
    'auto_generated', 'dsp-project:inc/c2837x_block_project.h', 0, ...
    'project', 'Project-level instance exports.', '', false);
fileCount = fileCount + 1;
files(fileCount) = make_file('src/c2837x_block_project.c', ...
    'auto_generated', 'dsp-project:src/c2837x_block_project.c', 0, ...
    'project', 'Project-level static instance bindings.', '', false);

suffixes = {'config.h', 'user_config.h', 'algorithm.h', ...
    'config.c', 'io.c', 'algorithm.c'};
folders = {'inc', 'inc', 'inc', 'src', 'src', 'src'};
categories = {'auto_generated', 'user', 'auto_generated', ...
    'auto_generated', 'auto_generated', 'user'};
responsibilities = { ...
    'Instance generated configuration declarations.', ...
    'Instance user-editable configuration.', ...
    'Instance generated algorithm interface.', ...
    'Instance generated configuration definitions.', ...
    'Instance generated IO adapter.', ...
    'Instance user algorithm implementation.'};
for instanceIndex = 1:numel(project.instances)
    name = project.instances(instanceIndex).internal_name;
    [valid, message] = c2837x_block_validate_name(name, {});
    if ~valid
        error('C2837xBlock:DspOutput:InvalidInstanceName', '%s', message);
    end
    for fileIndex = 1:numel(suffixes)
        relativePath = [folders{fileIndex} '/' name '_' suffixes{fileIndex}];
        fileCount = fileCount + 1;
        files(fileCount) = make_file(relativePath, categories{fileIndex}, ...
            ['dsp-instance:' name ':' relativePath], instanceIndex, ...
            'instance', responsibilities{fileIndex}, '', false);
    end
end

paths = {files.target_path};
foldedPaths = cellfun(@lower, paths, 'UniformOutput', false);
if numel(unique(foldedPaths)) ~= numel(paths)
    error('C2837xBlock:DspOutput:PathConflict', ...
        'DSP output model contains duplicate or case-conflicting paths.');
end
model = struct('schema_version', uint16(1), 'dsp_root', dspRoot, ...
    'inc_root', fullfile(dspRoot, 'inc'), ...
    'src_root', fullfile(dspRoot, 'src'), 'files', files);

    function value = make_file(relativePath, category, owner, instanceIndex, ...
            fileScope, responsibility, sourcePath, candidateAvailable)
        parts = strsplit_path(relativePath);
        if ~any(strcmp(parts{1}, {'inc', 'src'})) || numel(parts) ~= 2 || ...
                any(cellfun(@isempty, parts)) || ...
                any(ismember(parts, {'.', '..'}))
            error('C2837xBlock:DspOutput:InvalidRelativePath', ...
                'DSP output paths must be files directly below inc or src.');
        end
        targetPath = c2837x_block_normalize_absolute_path( ...
            fullfile(dspRoot, parts{:}));
        if ~is_descendant(dspRoot, targetPath)
            error('C2837xBlock:DspOutput:PathEscape', ...
                'DSP output path escapes the DSP root.');
        end
        if ~isempty(sourcePath)
            sourcePath = c2837x_block_normalize_absolute_path(sourcePath);
        end
        value = struct('relative_path', relativePath, ...
            'target_path', targetPath, 'category', category, 'owner', owner, ...
            'instance_index', double(instanceIndex), 'file_scope', fileScope, ...
            'responsibility', responsibility, 'source_path', sourcePath, ...
            'candidate_available', logical(candidateAvailable));
    end
end

function root = canonical_root(value)
if ~((ischar(value) && isrow(value)) || ...
        (isstring(value) && isscalar(value) && ~ismissing(value)))
    error('C2837xBlock:DspOutput:InvalidRoot', ...
        'project.output.dsp_root must be canonical absolute text.');
end
value = char(value);
try
    root = c2837x_block_normalize_absolute_path(value);
catch
    error('C2837xBlock:DspOutput:InvalidRoot', ...
        'project.output.dsp_root must be canonical absolute text.');
end
if isempty(root) || ~strcmp(value, root)
    error('C2837xBlock:DspOutput:InvalidRoot', ...
        'project.output.dsp_root must be canonical absolute text.');
end
end

function parts = strsplit_path(path)
if contains(path, '\') || startsWith(path, '/')
    error('C2837xBlock:DspOutput:InvalidRelativePath', ...
        'DSP relative paths must use normalized forward slashes.');
end
parts = strsplit(path, '/');
end

function tf = is_descendant(root, path)
if endsWith(root, filesep)
    prefix = root;
else
    prefix = [root filesep];
end
if ispc
    tf = startsWith(path, prefix, 'IgnoreCase', true);
else
    tf = startsWith(path, prefix);
end
end
