function [report, issues] = c2837x_block_build_project_report(project)
%C2837X_BLOCK_BUILD_PROJECT_REPORT Build per-instance Hash and buffer report.

prototype = struct('instance_index', 0, 'display_name', '', ...
    'internal_name', '', 'interface_hash', uint32(0), ...
    'canonical_text', '', 'canonical_utf8_octets', 0, ...
    'input_data_octets', 0, 'output_data_octets', 0, ...
    'input_payload_octets', 0, 'output_payload_octets', 0, ...
    'rx_frame_words', 0, 'tx_frame_words', 0);
report = struct('instances', repmat(prototype, 1, 0), ...
    'total_protocol_buffer_words', 0);
issues = empty_issues();

if ~isstruct(project) || ~isscalar(project) || ~isfield(project, 'instances') || ...
        ~isstruct(project.instances)
    issues = report_issue(0);
    return;
end

report.instances = repmat(prototype, 1, numel(project.instances));
for index = 1:numel(project.instances)
    try
        instance = project.instances(index);
        [text, hash, metrics] = ...
            c2837x_block_build_interface_hash(project, index);
        rxWords = (4 + max(6, metrics.input_payload_octets)) / 2;
        txWords = (4 + max(2, metrics.output_payload_octets)) / 2;
        report.instances(index) = struct( ...
            'instance_index', double(index), ...
            'display_name', char(instance.display_name), ...
            'internal_name', char(instance.internal_name), ...
            'interface_hash', hash, 'canonical_text', text, ...
            'canonical_utf8_octets', double(metrics.canonical_utf8_octets), ...
            'input_data_octets', double(metrics.input_data_octets), ...
            'output_data_octets', double(metrics.output_data_octets), ...
            'input_payload_octets', double(metrics.input_payload_octets), ...
            'output_payload_octets', double(metrics.output_payload_octets), ...
            'rx_frame_words', double(rxWords), ...
            'tx_frame_words', double(txWords));
    catch
        issues(end + 1) = report_issue(index); %#ok<AGROW>
    end
end
valid = setdiff(1:numel(report.instances), [issues.instance_index]);
if ~isempty(valid)
    values = report.instances(valid);
    report.total_protocol_buffer_words = ...
        sum([values.rx_frame_words] + [values.tx_frame_words]);
end
end

function issue = report_issue(index)
if index == 0
    fieldPath = 'project';
else
    fieldPath = sprintf('project.instances(%u)', index);
end
issue = struct('severity', 'Error', 'code', 'APP_REPORT_BUILD_FAILED', ...
    'message', 'The instance report could not be built.', ...
    'field_path', fieldPath, 'instance_index', double(index), ...
    'file_path', '');
end

function issues = empty_issues()
issues = struct('severity', {}, 'code', {}, 'message', {}, ...
    'field_path', {}, 'instance_index', {}, 'file_path', {});
end
