function rendered = c2837x_block_render_dsp_instance_config_files(project)
%C2837X_BLOCK_RENDER_DSP_INSTANCE_CONFIG_FILES Render instance Config files.

c2837x_block_validate_project_structure(project);
layout = c2837x_block_build_dsp_wire_layout(project);
prototype = struct('instance_index', 0, 'internal_name', '', ...
    'config_header_bytes', zeros(1, 0, 'uint8'), ...
    'user_config_header_bytes', zeros(1, 0, 'uint8'), ...
    'config_source_bytes', zeros(1, 0, 'uint8'));
rendered = repmat(prototype, 1, numel(project.instances));
for index = 1:numel(project.instances)
    names = c2837x_block_build_instance_c_names( ...
        project.instances(index).internal_name);
    name = names.internal_name;
    macro = names.macro_prefix;
    typed = names.typed_prefix;
    [~, interfaceHash] = ...
        c2837x_block_build_interface_hash(project, index);
    definition = resolve_definition(project.instances(index).iodevice.type);
    support = validated_support(definition, project, index);
    rendered(index) = struct('instance_index', index, ...
        'internal_name', name, ...
        'config_header_bytes', text_bytes(config_header(project, ...
        name, macro, interfaceHash, layout.instances(index), support)), ...
        'user_config_header_bytes', text_bytes(user_header(macro)), ...
        'config_source_bytes', text_bytes(config_source(name, macro, typed, support)));
end
end

function text = config_header(project, name, macro, hash, metrics, support)
rxOctets = metrics.rx_frame_octets;
txOctets = metrics.tx_frame_octets;
guard = ['C2837X_BLOCK_' macro '_CONFIG_H'];
text = sprintf([ ...
    '#ifndef %s\n#define %s\n\n' ...
    '/*\n * AUTO-GENERATED FILE\n * Manual changes will be overwritten.\n */\n\n' ...
    '#include "F28x_Project.h"\n\n' ...
    '#define %s_PROTOCOL_VERSION          ((Uint16)0x%04Xu)\n' ...
    '#define %s_INTERFACE_HASH            ((Uint32)0x%08XUL)\n\n' ...
    '#define %s_INPUT_DATA_OCTETS          %uu\n' ...
    '#define %s_OUTPUT_DATA_OCTETS         %uu\n' ...
    '#define %s_INPUT_PAYLOAD_OCTETS       %uu\n' ...
    '#define %s_OUTPUT_PAYLOAD_OCTETS      %uu\n' ...
    '#define %s_MAX_PAYLOAD_OCTETS         %uu\n\n' ...
    '#define %s_RX_FRAME_OCTETS            %uUL\n' ...
    '#define %s_TX_FRAME_OCTETS            %uUL\n' ...
    '#define %s_RX_FRAME_WORDS             %uu\n' ...
    '#define %s_TX_FRAME_WORDS             %uu\n\n' ...
    '#if defined(__STDC_VERSION__) && (__STDC_VERSION__ >= 201112L)\n' ...
    '#define %s_STATIC_ASSERT(condition_, name_) _Static_assert((condition_), #name_)\n' ...
    '#else\n' ...
    '#define %s_STATIC_ASSERT(condition_, name_) typedef char %s_static_assert_##name_[(condition_) ? 1 : -1]\n' ...
    '#endif\n\n%s\n%s\n' ...
    '#if defined(C2837X_BLOCK_%s_USE_USER_CONFIG)\n' ...
    '#include "%s_user_config.h"\n\n' ...
    '#ifndef INTERACTION_TIMEOUT\n#error "INTERACTION_TIMEOUT must be defined."\n#endif\n' ...
    '#ifndef TRANSFER_TIMEOUT\n#error "TRANSFER_TIMEOUT must be defined."\n#endif\n\n' ...
    '%s_STATIC_ASSERT((INTERACTION_TIMEOUT) > 0, interaction_timeout_positive);\n' ...
    '%s_STATIC_ASSERT((TRANSFER_TIMEOUT) > 0, transfer_timeout_positive);\n' ...
    '%s_STATIC_ASSERT((INTERACTION_TIMEOUT) <= 2147483, interaction_timeout_range);\n' ...
    '%s_STATIC_ASSERT((TRANSFER_TIMEOUT) <= 2147483, transfer_timeout_range);\n' ...
    '%s_STATIC_ASSERT(((INTERACTION_TIMEOUT) %% 1u) == 0u, interaction_timeout_integer);\n' ...
    '%s_STATIC_ASSERT(((TRANSFER_TIMEOUT) %% 1u) == 0u, transfer_timeout_integer);\n\n' ...
    '#define %s_INTERACTION_TIMEOUT_US \\\n    ((Uint32)(INTERACTION_TIMEOUT) * (Uint32)1000u)\n\n' ...
    '#define %s_TRANSFER_TIMEOUT_US \\\n    ((Uint32)(TRANSFER_TIMEOUT) * (Uint32)1000u)\n' ...
    '#endif\n\n' ...
    '#endif /* %s */\n'], ...
    guard, guard, macro, double(project.common.protocol_version), ...
    macro, double(hash), macro, metrics.input_data_octets, ...
    macro, metrics.output_data_octets, macro, metrics.input_payload_octets, ...
    macro, metrics.output_payload_octets, macro, metrics.max_payload_octets, ...
    macro, rxOctets, macro, txOctets, macro, rxOctets / 2, ...
    macro, txOctets / 2, macro, macro, lower(macro), ...
    support.header_definitions, support.header_checks, macro, name, ...
    macro, macro, macro, macro, macro, macro, macro, macro, guard);
end

function text = user_header(macro)
guard = ['C2837X_BLOCK_' macro '_USER_CONFIG_H'];
text = sprintf([ ...
    '#ifndef %s\n#define %s\n\n' ...
    '/* USER-EDITABLE FILE */\n\n' ...
    '#define INTERACTION_TIMEOUT  5000u\n' ...
    '#define TRANSFER_TIMEOUT     1000u\n\n' ...
    '#endif /* %s */\n'], guard, guard, guard);
end

function text = config_source(name, macro, typed, support)
includes = sprintf('#include "%s"\n', support.source_includes{:});
text = sprintf([ ...
    '/*\n * AUTO-GENERATED FILE\n * Manual changes will be overwritten.\n */\n\n' ...
    '#define C2837X_BLOCK_%s_USE_USER_CONFIG\n' ...
    '#include "c2837x_block_config_internal.h"\n' ...
    '#include "%s_config.h"\n\n' ...
    '#include "c2837x_block_platform.h"\n' ...
    '#include "%s_algorithm.h"\n#include <string.h>\n%s\n' ...
    'extern Uint16 c2837x_block_%s_rx_frame_words[%s_RX_FRAME_WORDS];\n' ...
    'extern Uint16 c2837x_block_%s_tx_frame_words[%s_TX_FRAME_WORDS];\n\n' ...
    'extern %s_InputData c2837x_block_%s_input_object;\n' ...
    'extern %s_OutputData c2837x_block_%s_output_object;\n\n%s\n' ...
    'static void c2837x_block_%s_reset_io(\n    void *context,\n    void *input_object,\n    void *output_object)\n{\n' ...
    '    (void)context;\n    memset(input_object, 0, sizeof(%s_InputData));\n' ...
    '    memset(output_object, 0, sizeof(%s_OutputData));\n}\n\n' ...
    'static int16 c2837x_block_%s_on_start(\n    void *context)\n{\n' ...
    '    (void)context;\n    return %s_OnStart();\n}\n\n' ...
    'extern void c2837x_block_%s_decode_input(\n' ...
    '    void *input_object, const Uint16 *user_data_words);\n\n' ...
    'static int16 c2837x_block_%s_on_step(\n    void *context,\n    const void *input_object,\n    void *output_object)\n{\n' ...
    '    (void)context;\n    return %s_OnStep(\n' ...
    '        (const %s_InputData *)input_object,\n' ...
    '        (%s_OutputData *)output_object);\n}\n\n' ...
    'extern void c2837x_block_%s_encode_output(\n' ...
    '    const void *output_object, Uint16 *user_data_words);\n\n' ...
    'static void c2837x_block_%s_on_stop(\n    void *context)\n{\n' ...
    '    (void)context;\n    %s_OnStop();\n}\n\n' ...
    'static const C2837xBlock_AlgorithmAdapter\n    c2837x_block_%s_algorithm_adapter =\n{\n' ...
    '    c2837x_block_%s_reset_io,\n    c2837x_block_%s_on_start,\n' ...
    '    c2837x_block_%s_decode_input,\n    c2837x_block_%s_on_step,\n' ...
    '    c2837x_block_%s_encode_output,\n    c2837x_block_%s_on_stop\n};\n\n' ...
    'const C2837xBlock_Config\n    c2837x_block_%s_config =\n{\n' ...
    '    /* iodevice_ops */\n    %s,\n\n' ...
    '    /* iodevice_channel */\n    %s,\n\n' ...
    '    /* rx */\n    c2837x_block_%s_rx_frame_words,\n    (Uint32)%s_RX_FRAME_OCTETS,\n\n' ...
    '    /* tx */\n    c2837x_block_%s_tx_frame_words,\n    (Uint32)%s_TX_FRAME_OCTETS,\n\n' ...
    '    /* typed objects */\n    &c2837x_block_%s_input_object,\n    &c2837x_block_%s_output_object,\n\n' ...
    '    /* algorithm */\n    &c2837x_block_%s_algorithm_adapter,\n    (void *)0,\n\n' ...
    '    /* protocol/interface */\n    %s_PROTOCOL_VERSION,\n    %s_INTERFACE_HASH,\n' ...
    '    %s_INPUT_PAYLOAD_OCTETS,\n    %s_OUTPUT_PAYLOAD_OCTETS,\n    %s_MAX_PAYLOAD_OCTETS,\n\n' ...
    '    /* clock/timeouts */\n    c2837x_block_time_us,\n' ...
    '    %s_INTERACTION_TIMEOUT_US,\n    %s_TRANSFER_TIMEOUT_US\n};\n'], ...
    macro, name, name, includes, ...
    name, macro, name, macro, typed, name, typed, name, ...
    support.source_declarations, ...
    name, typed, typed, name, typed, name, name, typed, typed, typed, ...
    name, name, typed, ...
    name, name, name, name, name, name, name, name, ...
    support.iodevice_ops_expression, support.iodevice_channel_expression, ...
    name, macro, name, macro, name, name, name, ...
    macro, macro, macro, macro, macro, macro, macro);
end

function definition = resolve_definition(type)
[definition, found] = c2837x_block_get_iodevice_definition(type);
if ~found
    error('C2837xBlock:IoDevice:Unsupported', ...
        'Cannot render unsupported IoDevice type "%s".', char(type));
end
end

function support = validated_support(definition, project, index)
support = definition.render_instance_config_support(project, index);
second = definition.render_instance_config_support(project, index);
fields = {'header_definitions', 'header_checks', 'source_includes', ...
    'source_declarations', 'iodevice_ops_expression', ...
    'iodevice_channel_expression'};
valid = isstruct(support) && isscalar(support) && all(isfield(support, fields)) && ...
    all(cellfun(@(field) ischar(support.(field)) && isrow(support.(field)), ...
    fields([1 2 4 5 6]))) && iscell(support.source_includes) && ...
    isrow(support.source_includes) && ...
    all(cellfun(@(value) ischar(value) && isrow(value) && ~isempty(value), ...
    support.source_includes)) && numel(unique(support.source_includes)) == ...
    numel(support.source_includes) && ...
    ~isempty(support.iodevice_ops_expression) && ...
    ~isempty(support.iodevice_channel_expression) && isequal(support, second);
if ~valid
    error('C2837xBlock:IoDevice:InvalidInstanceConfigSupport', ...
        'IoDevice definition "%s" returned invalid instance Config support.', ...
        definition.type);
end
end

function bytes = text_bytes(text)
text = strrep(text, [char(13) newline], newline);
text = strrep(text, char(13), newline);
while ~isempty(text) && text(end) == newline
    text(end) = [];
end
bytes = reshape(uint8(unicode2native([text newline], 'UTF-8')), 1, []);
end
