function [canonicalText, interfaceHash, metrics] = ...
        c2837x_block_build_interface_hash(project, instanceIndex)
%C2837X_BLOCK_BUILD_INTERFACE_HASH Build one instance Interface Hash.

if ~isstruct(project) || ~isscalar(project) || ...
        ~isfield(project, 'common') || ~isstruct(project.common) || ...
        ~isscalar(project.common) || ...
        ~isfield(project.common, 'protocol_version') || ...
        ~isfield(project, 'instances') || ~isstruct(project.instances)
    error('C2837xBlock:InterfaceHash:InvalidProject', ...
        'project must contain common.protocol_version and a struct instances array.');
end
if ~isnumeric(instanceIndex) || ~isreal(instanceIndex) || ...
        ~isscalar(instanceIndex) || ~isfinite(instanceIndex) || ...
        instanceIndex < 1 || instanceIndex ~= fix(instanceIndex) || ...
        instanceIndex > numel(project.instances)
    error('C2837xBlock:InterfaceHash:InvalidInstanceIndex', ...
        'instanceIndex must identify an existing instance.');
end

[canonicalText, metrics] = c2837x_block_build_interface_text( ...
    project.common.protocol_version, project.instances(instanceIndex));
try
    utf8Data = unicode2native(canonicalText, 'UTF-8');
catch cause
    failure = MException('C2837xBlock:InterfaceHash:EncodingFailed', ...
        'Interface text could not be encoded as UTF-8.');
    throwAsCaller(addCause(failure, cause));
end
metrics.canonical_utf8_octets = numel(utf8Data);
interfaceHash = c2837x_block_crc32(utf8Data);
end
