function model = c2837x_block_build_dsp_output_model(project)
%C2837X_BLOCK_BUILD_DSP_OUTPUT_MODEL Describe the DSP tree and platform data.

c2837x_block_validate_project_structure(project);
dspRoot = canonical_root(project.output.dsp_root);
appRoot = fileparts(mfilename('fullpath'));
repositoryRoot = fileparts(appRoot);
platformConfig = build_platform_config(project);

useW5300 = false;
useSci = false;
for index = 1:numel(project.instances)
    type = char(project.instances(index).iodevice.type);
    useW5300 = useW5300 || strcmp(type, 'w5300_tcp');
    useSci = useSci || strcmp(type, 'sci');
end

prototype = struct('relative_path', '', 'target_path', '', 'category', '', ...
    'owner', '', 'instance_index', 0, 'file_scope', '', ...
    'responsibility', '', 'source_path', '', 'candidate_available', false);

corePaths = { ...
    'inc/c2837x_block.h', ...
    'inc/c2837x_block_protocol.h', ...
    'inc/c2837x_block_iodevice.h'};
if useW5300
    corePaths = [corePaths, { ...
        'inc/c2837x_w5300_regs.h', ...
        'inc/c2837x_w5300_hal.h', ...
        'inc/c2837x_w5300_socket.h', ...
        'inc/c2837x_w5300_channel.h'}]; %#ok<AGROW>
end
if useSci
    corePaths{end + 1} = 'inc/c2837x_block_sci.h'; %#ok<AGROW>
end
corePaths = [corePaths, { ...
    'src/c2837x_block.c', ...
    'src/c2837x_block_protocol.c', ...
    'src/c2837x_block_internal.h', ...
    'src/c2837x_block_config_internal.h', ...
    'src/c2837x_block_platform.h', ...
    'src/c2837x_block_platform.c', ...
    'src/c2837x_block_timer2.c'}];
if useW5300
    corePaths = [corePaths, { ...
        'src/c2837x_w5300_hal.c', ...
        'src/c2837x_w5300_socket.c', ...
        'src/c2837x_w5300_channel.c'}]; %#ok<AGROW>
end
if useSci
    corePaths{end + 1} = 'src/c2837x_block_sci.c'; %#ok<AGROW>
end

files = repmat(prototype, 1, numel(corePaths) + 2 + ...
    6 * numel(project.instances));
fileCount = 0;
for index = 1:numel(corePaths)
    relativePath = corePaths{index};
    sourceParts = strsplit_path(relativePath);
    fileCount = fileCount + 1;
    files(fileCount) = make_file(relativePath, 'core', ...
        ['dsp-core:' relativePath], 0, 'core', ...
        'DSP-SimBridge public Core source.', ...
        fullfile(repositoryRoot, 'dsp', sourceParts{:}), true);
end

fileCount = fileCount + 1;
files(fileCount) = make_file('inc/c2837x_block_project.h', ...
    'auto_generated', 'dsp-project:inc/c2837x_block_project.h', 0, ...
    'project', ['Project instance exports and project-level public ' ...
    'configuration declarations.'], '', true);
fileCount = fileCount + 1;
files(fileCount) = make_file('src/c2837x_block_project.c', ...
    'auto_generated', 'dsp-project:src/c2837x_block_project.c', 0, ...
    'project', ['Project instance definitions, static bindings, and ' ...
    'project-level public configuration.'], '', true);

suffixes = {'config.h', 'user_config.h', 'algorithm.h', ...
    'config.c', 'io.c', 'algorithm.c'};
folders = {'inc', 'inc', 'inc', 'src', 'src', 'src'};
categories = {'auto_generated', 'user', 'auto_generated', ...
    'auto_generated', 'auto_generated', 'user'};
responsibilities = { ...
    ['Instance sizes, Interface Hash, adapter declarations, and static ' ...
    'binding declarations.'], ...
    'User-editable DSP timeout configuration.', ...
    ['Authoritative typed algorithm structures and callback ' ...
    'declarations.'], ...
    ['Instance sizes, Interface Hash, adapter definitions, and static ' ...
    'bindings.'], ...
    'Instance serialization and IoDevice channel binding.', ...
    'User algorithm implementation.'};
for instanceIndex = 1:numel(project.instances)
    rawName = project.instances(instanceIndex).internal_name;
    [valid, message] = c2837x_block_validate_name(rawName, {});
    if ~valid
        error('C2837xBlock:DspOutput:InvalidInstanceName', '%s', message);
    end
    name = char(rawName);
    algorithmMode = char(project.instances(instanceIndex).algorithm.mode);
    for fileIndex = 1:numel(suffixes)
        relativePath = [folders{fileIndex} '/' name '_' suffixes{fileIndex}];
        fileCount = fileCount + 1;
        files(fileCount) = make_file(relativePath, categories{fileIndex}, ...
            ['dsp-instance:' name ':' relativePath], instanceIndex, ...
            'instance', responsibilities{fileIndex}, '', ...
            any(fileIndex == [1 2 3 4 5]) || ...
            (fileIndex == 6 && ~strcmp(algorithmMode, 'external_reference')));
    end
end

paths = {files.target_path};
foldedPaths = cellfun(@lower, paths, 'UniformOutput', false);
if numel(unique(foldedPaths)) ~= numel(paths)
    error('C2837xBlock:DspOutput:PathConflict', ...
        'DSP output model contains duplicate or case-conflicting paths.');
end
model = struct('schema_version', uint16(1), 'dsp_root', dspRoot, ...
    'inc_root', fullfile(dspRoot, 'inc'), ...
    'src_root', fullfile(dspRoot, 'src'), ...
    'platform_config', platformConfig, 'files', files);

    function value = make_file(relativePath, category, owner, instanceIndex, ...
            fileScope, responsibility, sourcePath, candidateAvailable)
        parts = strsplit_path(relativePath);
        if ~any(strcmp(parts{1}, {'inc', 'src'})) || numel(parts) ~= 2 || ...
                any(cellfun(@isempty, parts)) || ...
                any(ismember(parts, {'.', '..'}))
            error('C2837xBlock:DspOutput:InvalidRelativePath', ...
                'DSP output paths must be files directly below inc or src.');
        end
        targetPath = c2837x_block_normalize_absolute_path( ...
            fullfile(dspRoot, parts{:}));
        if ~is_descendant(dspRoot, targetPath)
            error('C2837xBlock:DspOutput:PathEscape', ...
                'DSP output path escapes the DSP root.');
        end
        if ~isempty(sourcePath)
            sourcePath = c2837x_block_normalize_absolute_path(sourcePath);
        end
        value = struct('relative_path', relativePath, ...
            'target_path', targetPath, 'category', category, 'owner', owner, ...
            'instance_index', double(instanceIndex), 'file_scope', fileScope, ...
            'responsibility', responsibility, 'source_path', sourcePath, ...
            'candidate_available', logical(candidateAvailable));
    end
end

function platformConfig = build_platform_config(project)
% Keep this collection at project scope; instance binding is a later stage.
descriptorPrototype = struct( ...
    'module', '', ...
    'baud', uint32(0), ...
    'rx_gpio', '', ...
    'tx_gpio', '', ...
    'rx_pin_type', '', ...
    'rx_qualification', '', ...
    'tx_pin_type', '', ...
    'ctrl_gpio', '', ...
    'ctrl_pin_type', '', ...
    'ctrl_tx_active_level', '');
sciDescriptors = repmat(descriptorPrototype, 1, 0);
useW5300 = false;

for index = 1:numel(project.instances)
    instance = project.instances(index);
    type = char(instance.iodevice.type);
    if strcmp(type, 'w5300_tcp')
        useW5300 = true;
    elseif strcmp(type, 'sci')
        settings = instance.iodevice.settings;
        descriptor = descriptorPrototype;
        descriptor.module = text_value(settings.module);
        descriptor.baud = uint32(double(settings.baud));
        descriptor.rx_gpio = text_value(settings.rx_gpio);
        descriptor.tx_gpio = text_value(settings.tx_gpio);
        descriptor.rx_pin_type = text_value(settings.rx_pin_type);
        descriptor.rx_qualification = text_value(settings.rx_qualification);
        descriptor.tx_pin_type = text_value(settings.tx_pin_type);
        descriptor.ctrl_gpio = text_value(settings.ctrl_gpio);
        descriptor.ctrl_pin_type = text_value(settings.ctrl_pin_type);
        descriptor.ctrl_tx_active_level = ...
            text_value(settings.ctrl_tx_active_level);
        sciDescriptors(end + 1) = descriptor; %#ok<AGROW>
    end
end

if isempty(sciDescriptors)
    sciClock = [];
else
    % W5300-only projects do not consult the SCI clock service.
    sciClock = c2837x_block_get_sci_clock_config();
end

platformConfig = struct( ...
    'use_w5300', logical(useW5300), ...
    'sci_descriptors', sciDescriptors, ...
    'sci_clock', sciClock);
end

function value = text_value(candidate)
if ischar(candidate) && isrow(candidate)
    value = candidate;
elseif isstring(candidate) && isscalar(candidate) && ~ismissing(candidate)
    value = char(candidate);
else
    error('C2837xBlock:DspOutput:InvalidPlatformText', ...
        'SCI platform settings must be scalar text.');
end
end

function root = canonical_root(value)
if ~((ischar(value) && isrow(value)) || ...
        (isstring(value) && isscalar(value) && ~ismissing(value)))
    error('C2837xBlock:DspOutput:InvalidRoot', ...
        'project.output.dsp_root must be canonical absolute text.');
end
value = char(value);
try
    root = c2837x_block_normalize_absolute_path(value);
catch
    error('C2837xBlock:DspOutput:InvalidRoot', ...
        'project.output.dsp_root must be canonical absolute text.');
end
if isempty(root) || ~strcmp(value, root)
    error('C2837xBlock:DspOutput:InvalidRoot', ...
        'project.output.dsp_root must be canonical absolute text.');
end
end

function parts = strsplit_path(path)
if contains(path, '\') || startsWith(path, '/')
    error('C2837xBlock:DspOutput:InvalidRelativePath', ...
        'DSP relative paths must use normalized forward slashes.');
end
parts = strsplit(path, '/');
end

function tf = is_descendant(root, path)
if endsWith(root, filesep)
    prefix = root;
else
    prefix = [root filesep];
end
if ispc
    tf = startsWith(path, prefix, 'IgnoreCase', true);
else
    tf = startsWith(path, prefix);
end
end
