function definition = c2837x_block_iodevice_w5300_tcp_definition()
%C2837X_BLOCK_IODEVICE_W5300_TCP_DEFINITION Describe W5300 TCP resources.

definition = struct('type', 'w5300_tcp', 'max_instance_count', 8, ...
    'validate_settings', @validate_settings, ...
    'collect_resource_claims', @collect_resource_claims, ...
    'render_project_support', @render_project_support, ...
    'render_instance_config_support', @render_instance_config_support);
end

function support = render_instance_config_support(project, instanceIndex)
instance = project.instances(instanceIndex);
name = char(instance.internal_name);
macro = upper(name);
socket = double(instance.iodevice.settings.socket_number);
port = double(instance.iodevice.settings.tcp_port);
support = struct( ...
    'header_definitions', sprintf([ ...
    '#define %s_W5300_SOCKET_NUMBER  %uu\n' ...
    '#define %s_TCP_PORT             %uu\n'], ...
    macro, socket, macro, port), ...
    'header_checks', sprintf([ ...
    '%s_STATIC_ASSERT(%s_W5300_SOCKET_NUMBER <= 7u, socket_number_out_of_range);\n' ...
    '%s_STATIC_ASSERT(%s_TCP_PORT > 0u && %s_TCP_PORT <= 65535u, tcp_port_out_of_range);\n'], ...
    macro, macro, macro, macro, macro), ...
    'source_includes', {{'c2837x_w5300_channel.h'}}, ...
    'source_declarations', sprintf([ ...
    'extern C2837xW5300Channel\n' ...
    '    c2837x_block_%s_iodevice_channel;\n'], name), ...
    'iodevice_ops_expression', '&c2837x_w5300_iodevice_ops', ...
    'iodevice_channel_expression', ...
    ['&c2837x_block_' name '_iodevice_channel']);
end

function issues = validate_settings(settings, instanceIndex)
issues = empty_issues();
prefix = sprintf('project.instances(%u).iodevice.settings.', instanceIndex);
if ~valid_field(settings, 'socket_number', 0, 7)
    issues(end + 1) = issue('SOCKET_INVALID', ...
        'Socket number must be an integer from 0 to 7.', ...
        [prefix 'socket_number'], instanceIndex);
end
if ~valid_field(settings, 'tcp_port', 1, 65535)
    issues(end + 1) = issue('TCP_PORT_INVALID', ...
        'TCP port must be an integer from 1 to 65535.', ...
        [prefix 'tcp_port'], instanceIndex);
end
end

function claims = collect_resource_claims(settings, instanceIndex)
prototype = struct('scope', '', 'kind', '', 'key', '', 'exclusive', false, ...
    'duplicate_code', '', 'duplicate_message', '', 'field_path', '', ...
    'instance_index', 0);
claims = repmat(prototype, 1, 0);
prefix = sprintf('project.instances(%u).iodevice.settings.', instanceIndex);
if valid_field(settings, 'socket_number', 0, 7)
    claims(end + 1) = claim('socket', settings.socket_number, ...
        'SOCKET_DUPLICATE', 'Socket number is already used.', ...
        [prefix 'socket_number'], instanceIndex);
end
if valid_field(settings, 'tcp_port', 1, 65535)
    claims(end + 1) = claim('tcp_listen_port', settings.tcp_port, ...
        'TCP_PORT_DUPLICATE', 'TCP port is already used.', ...
        [prefix 'tcp_port'], instanceIndex);
end
end

function support = render_project_support(project)
network = project.common.network;
mac = double(network.mac);
support.includes = {'c2837x_w5300_hal.h'};
support.source = sprintf([ ...
    'const C2837xW5300ProjectConfig\n' ...
    '    c2837x_w5300_project_config =\n' ...
    '{\n' ...
    '    {\n' ...
    '        0x%02Xu, 0x%02Xu, 0x%02Xu,\n' ...
    '        0x%02Xu, 0x%02Xu, 0x%02Xu\n' ...
    '    },\n' ...
    '    (Uint32)0x%08XUL,\n' ...
    '    (Uint32)0x%08XUL,\n' ...
    '    (Uint32)0x%08XUL\n' ...
    '};\n'], mac(1), mac(2), mac(3), mac(4), mac(5), mac(6), ...
    ipv4_value(network.ip), ipv4_value(network.gateway), ...
    ipv4_value(network.subnet));
end

function value = ipv4_value(text)
tokens = regexp(char(text), ...
    '^(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})$', 'tokens', 'once');
if isempty(tokens)
    error('C2837xBlock:IoDevice:InvalidNetwork', ...
        'W5300 project support requires dotted decimal IPv4 values.');
end
octets = cellfun(@str2double, tokens);
if any(octets > 255)
    error('C2837xBlock:IoDevice:InvalidNetwork', ...
        'W5300 project support requires dotted decimal IPv4 values.');
end
value = uint32(octets(1)) * uint32(16777216) + ...
    uint32(octets(2)) * uint32(65536) + ...
    uint32(octets(3)) * uint32(256) + uint32(octets(4));
end

function value = claim(kind, key, code, message, fieldPath, instanceIndex)
value = struct('scope', 'project:w5300_tcp', 'kind', kind, ...
    'key', sprintf('%.0f', double(key)), 'exclusive', true, ...
    'duplicate_code', code, 'duplicate_message', message, ...
    'field_path', fieldPath, 'instance_index', instanceIndex);
end

function value = issue(code, message, fieldPath, instanceIndex)
value = struct('severity', 'Error', 'code', code, 'message', message, ...
    'field_path', fieldPath, 'instance_index', instanceIndex, 'file_path', '');
end

function values = empty_issues()
values = struct('severity', {}, 'code', {}, 'message', {}, ...
    'field_path', {}, 'instance_index', {}, 'file_path', {});
end

function tf = is_integer_in_range(value, minimum, maximum)
tf = isnumeric(value) && isscalar(value) && isreal(value) && ...
    isfinite(value) && value == fix(value) && value >= minimum && value <= maximum;
end

function tf = valid_field(settings, name, minimum, maximum)
tf = isstruct(settings) && isscalar(settings) && isfield(settings, name) && ...
    is_integer_in_range(settings.(name), minimum, maximum);
end
