function [definition, found] = c2837x_block_get_iodevice_definition(type)
%C2837X_BLOCK_GET_IODEVICE_DEFINITION Resolve a validated IoDevice definition.

definition = struct();
found = false;
if ~((ischar(type) && isrow(type)) || ...
        (isstring(type) && isscalar(type) && ~ismissing(type)))
    return;
end
type = char(type);
if isempty(regexp(type, '^[a-z][a-z0-9_]*$', 'once'))
    return;
end
functionName = ['c2837x_block_iodevice_' type '_definition'];
if exist(functionName, 'file') ~= 2
    return;
end
definition = feval(functionName);
required = {'type', 'max_instance_count', 'validate_settings', ...
    'collect_resource_claims', 'render_project_support'};
if ~isstruct(definition) || ~isscalar(definition) || ...
        ~all(isfield(definition, required)) || ...
        ~(ischar(definition.type) && isrow(definition.type)) || ...
        ~strcmp(definition.type, type) || ...
        ~(isnumeric(definition.max_instance_count) && ...
          isscalar(definition.max_instance_count) && ...
          (isinf(definition.max_instance_count) || ...
           (isfinite(definition.max_instance_count) && ...
            definition.max_instance_count > 0 && ...
            definition.max_instance_count == fix(definition.max_instance_count)))) || ...
        ~all(cellfun(@(field) isa(definition.(field), 'function_handle'), ...
        required(3:end)))
    error('C2837xBlock:IoDevice:InvalidDefinition', ...
        'IoDevice definition "%s" does not satisfy the required contract.', type);
end
found = true;
end
