function project = c2837x_block_create_default_project()
%C2837X_BLOCK_CREATE_DEFAULT_PROJECT Create an empty default V2 project.

instance = c2837x_block_create_default_instance();
project = struct( ...
    'format_version', uint16(2), ...
    'common', struct( ...
        'dsp_model', 'TMS320F28377D', ...
        'protocol_version', uint16(1), ...
        'abi', 'eabi', ...
        'network', struct( ...
            'mac', zeros(1, 0, 'uint8'), ...
            'ip', '', ...
            'gateway', '', ...
            'subnet', '')), ...
    'instances', instance([]), ...
    'output', struct( ...
        'dsp_root', '', ...
        'sfun_root', ''));
end
