function rendered = c2837x_block_render_sfun_files(project)
%C2837X_BLOCK_RENDER_SFUN_FILES Render deterministic S4-04 templates.

c2837x_block_validate_project_structure(project);
wireLayout = c2837x_block_build_dsp_wire_layout(project);
prototype = struct('instance_index', 0, 'internal_name', '', ...
    'sfun_source_bytes', zeros(1, 0, 'uint8'), ...
    'sfun_header_bytes', zeros(1, 0, 'uint8'), ...
    'io_source_bytes', zeros(1, 0, 'uint8'), ...
    'config_header_bytes', zeros(1, 0, 'uint8'));
rendered = repmat(prototype, 1, numel(project.instances));
for index = 1:numel(project.instances)
    instance = project.instances(index);
    layout = wireLayout.instances(index);
    names = c2837x_block_build_instance_c_names(instance.internal_name);
    validate_instance(instance);
    rendered(index) = struct('instance_index', index, ...
        'internal_name', names.internal_name, ...
        'sfun_source_bytes', text_bytes(sfun_source(names)), ...
        'sfun_header_bytes', text_bytes(sfun_header(names, instance, layout)), ...
        'io_source_bytes', text_bytes(io_source(names, instance, layout)), ...
        'config_header_bytes', text_bytes(config_header(names, instance, project, layout)));
end
end

function text = sfun_source(names)
text = [generated_file_header() sprintf([ ...
    '#define S_FUNCTION_NAME @NAME@_sfun\n' ...
    '#define S_FUNCTION_LEVEL 2\n\n' ...
    '#include "simstruc.h"\n' ...
    '#include "@NAME@_sfun_config.h"\n' ...
    '#include "@NAME@_sfun_user_config.h"\n' ...
    '#include "@NAME@_sfun.h"\n\n' ...
    '#include <stdlib.h>\n' ...
    '#include <string.h>\n\n' ...
    '#ifndef CONNECT_TIMEOUT_MS\n' ...
    '#error "CONNECT_TIMEOUT_MS must be defined in @NAME@_sfun_user_config.h"\n' ...
    '#endif\n' ...
    '#ifndef STEP_TIMEOUT_MS\n' ...
    '#error "STEP_TIMEOUT_MS must be defined in @NAME@_sfun_user_config.h"\n' ...
    '#endif\n' ...
    '#ifndef TERMINATE_TIMEOUT_MS\n' ...
    '#error "TERMINATE_TIMEOUT_MS must be defined in @NAME@_sfun_user_config.h"\n' ...
    '#endif\n\n' ...
    '@TYPED@SfunContext *@NAME@_sfun_create_context(void)\n' ...
    '{\n    return (@TYPED@SfunContext *)calloc(1u, sizeof(@TYPED@SfunContext));\n}\n\n' ...
    'void @NAME@_sfun_destroy_context(@TYPED@SfunContext *context)\n' ...
    '{\n' ...
    '    if (context == NULL) return;\n' ...
    '    if (@NAME@_pc_socket_is_valid(&context->socket)) {\n' ...
    '        @NAME@_pc_socket_close(&context->socket);\n' ...
    '    }\n' ...
    '    @NAME@_pc_socket_cleanup(&context->socket);\n' ...
    '    free(context);\n}\n\n' ...
    'static const char *@NAME@_sfun_error_text(SimStruct *S,\n' ...
    '    const @TYPED@PcError *error, const char *fallback)\n' ...
    '{\n' ...
    '    char *buffer = (char *)ssGetDWork(S, 0);\n' ...
    '    if (buffer == NULL || @NAME@_pc_error_format(error, buffer,\n' ...
    '            @MACRO@_SFUN_ERROR_TEXT_CAPACITY) != 0) {\n' ...
    '        return fallback;\n' ...
    '    }\n' ...
    '    return buffer;\n}\n\n' ...
    'static const char *@NAME@_sfun_copy_error(SimStruct *S, const char *message)\n' ...
    '{\n' ...
    '    char *buffer = (char *)ssGetDWork(S, 0);\n' ...
    '    if (buffer == NULL) return message;\n' ...
    '    (void)strncpy(buffer, message, @MACRO@_SFUN_ERROR_TEXT_CAPACITY - 1u);\n' ...
    '    buffer[@MACRO@_SFUN_ERROR_TEXT_CAPACITY - 1u] = ''\\0'';\n' ...
    '    return buffer;\n}\n\n' ...
    'static void @NAME@_sfun_fail_step(SimStruct *S,\n' ...
    '    @TYPED@SfunContext *context, const char *fallback)\n' ...
    '{\n' ...
    '    if (context == NULL) {\n' ...
    '        ssSetErrorStatus(S, @NAME@_sfun_copy_error(S, fallback));\n' ...
    '        return;\n' ...
    '    }\n' ...
    '    context->error.available |= @MACRO@_PC_ERROR_HAS_STEP_INDEX;\n' ...
    '    context->error.step_index = context->step_index;\n' ...
    '    @NAME@_pc_socket_close(&context->socket);\n' ...
    '    context->session_started = 0;\n' ...
    '    ssSetErrorStatus(S, @NAME@_sfun_error_text(S, &context->error, fallback));\n' ...
    '}\n\n' ...
    'static void mdlInitializeSizes(SimStruct *S)\n{\n' ...
    '    ssSetNumSFcnParams(S, 0);\n' ...
    '    if (ssGetNumSFcnParams(S) != ssGetSFcnParamsCount(S)) {\n' ...
    '        return;\n    }\n' ...
    '    if (@NAME@_sfun_setup_input_ports(S) != 0 ||\n' ...
    '            @NAME@_sfun_setup_output_ports(S) != 0) {\n' ...
    '        ssSetErrorStatus(S, "@NAME@_sfun: failed to configure ports.");\n' ...
    '        return;\n    }\n' ...
    '    ssSetNumSampleTimes(S, 1);\n' ...
    '    ssSetNumPWork(S, 1);\n' ...
    '    if (!ssSetNumDWork(S, 1)) {\n' ...
    '        ssSetErrorStatus(S, "@NAME@_sfun: failed to configure error DWork.");\n' ...
    '        return;\n' ...
    '    }\n' ...
    '    ssSetDWorkWidth(S, 0, @MACRO@_SFUN_ERROR_TEXT_CAPACITY);\n' ...
    '    ssSetDWorkDataType(S, 0, SS_UINT8);\n' ...
    '    ssSetDWorkUsedAsDState(S, 0, 0);\n' ...
    '    ssSetOptions(S, SS_OPTION_EXCEPTION_FREE_CODE |\n' ...
    '        SS_OPTION_CALL_TERMINATE_ON_EXIT);\n}\n\n' ...
    'static void mdlInitializeSampleTimes(SimStruct *S)\n{\n' ...
    '    ssSetSampleTime(S, 0, @MACRO@_SFUN_SAMPLE_TIME_SEC);\n' ...
    '    ssSetOffsetTime(S, 0, 0.0);\n}\n\n' ...
    '#define MDL_START\n' ...
    'static void mdlStart(SimStruct *S)\n{\n' ...
    '    @TYPED@SfunContext *context;\n' ...
    '    const char *message;\n' ...
    '    ssSetPWorkValue(S, 0, NULL);\n' ...
    '    context = @NAME@_sfun_create_context();\n' ...
    '    if (context == NULL) {\n' ...
    '        ssSetErrorStatus(S, @NAME@_sfun_copy_error(S,\n' ...
    '            "@NAME@_sfun: failed to allocate context."));\n' ...
    '        return;\n    }\n' ...
    '    if (@NAME@_pc_socket_init(&context->socket, &context->error) != 0) {\n' ...
    '        message = @NAME@_sfun_error_text(S, &context->error,\n' ...
    '            "@NAME@_sfun: socket initialization failed.");\n' ...
    '        @NAME@_sfun_destroy_context(context);\n' ...
    '        ssSetPWorkValue(S, 0, NULL);\n' ...
    '        ssSetErrorStatus(S, message);\n' ...
    '        return;\n' ...
    '    }\n' ...
    '    if (@NAME@_pc_socket_connect(&context->socket,\n' ...
    '            @MACRO@_SFUN_DSP_IP_ADDRESS, @MACRO@_SFUN_TCP_PORT,\n' ...
    '            CONNECT_TIMEOUT_MS, &context->error) != 0) {\n' ...
    '        message = @NAME@_sfun_error_text(S, &context->error,\n' ...
    '            "@NAME@_sfun: TCP connect failed.");\n' ...
    '        @NAME@_sfun_destroy_context(context);\n' ...
    '        ssSetPWorkValue(S, 0, NULL);\n' ...
    '        ssSetErrorStatus(S, message);\n' ...
    '        return;\n' ...
    '    }\n' ...
    '    if (@NAME@_protocol_send_sim_start(&context->socket,\n' ...
    '            @MACRO@_SFUN_PROTOCOL_VERSION, @MACRO@_SFUN_INTERFACE_HASH,\n' ...
    '            STEP_TIMEOUT_MS, &context->error) != 0) {\n' ...
    '        message = @NAME@_sfun_error_text(S, &context->error,\n' ...
    '            "@NAME@_sfun: SIM_START send failed.");\n' ...
    '        @NAME@_sfun_destroy_context(context);\n' ...
    '        ssSetPWorkValue(S, 0, NULL);\n' ...
    '        ssSetErrorStatus(S, message);\n' ...
    '        return;\n' ...
    '    }\n' ...
    '    if (@NAME@_protocol_wait_response(&context->socket, STEP_TIMEOUT_MS,\n' ...
    '            &context->error) != 0) {\n' ...
    '        message = @NAME@_sfun_error_text(S, &context->error,\n' ...
    '            "@NAME@_sfun: SIM_START response failed.");\n' ...
    '        @NAME@_sfun_destroy_context(context);\n' ...
    '        ssSetPWorkValue(S, 0, NULL);\n' ...
    '        ssSetErrorStatus(S, message);\n' ...
    '        return;\n' ...
    '    }\n' ...
    '    context->step_index = 0u;\n' ...
    '    context->session_started = 1;\n' ...
    '    ssSetPWorkValue(S, 0, context);\n}\n\n' ...
    'static void mdlOutputs(SimStruct *S, int_T tid)\n{\n' ...
    '    @TYPED@SfunContext *context = (@TYPED@SfunContext *)ssGetPWorkValue(S, 0);\n' ...
    '    uint16_t received_length = 0u;\n' ...
    '    (void)tid;\n' ...
    '    if (context == NULL) {\n' ...
    '        @NAME@_sfun_fail_step(S, NULL, "@NAME@_sfun: context is not initialized.");\n' ...
    '        return;\n' ...
    '    }\n' ...
    '    if (context->session_started == 0 ||\n' ...
    '            !@NAME@_pc_socket_is_valid(&context->socket)) {\n' ...
    '        @NAME@_pc_error_reset(&context->error, "step_precondition");\n' ...
    '        context->error.kind = @MACRO@_PC_ERROR_ARGUMENT;\n' ...
    '        @NAME@_sfun_fail_step(S, context, "@NAME@_sfun: session is not active.");\n' ...
    '        return;\n' ...
    '    }\n' ...
    '    if (@NAME@_sfun_pack_input_payload(S, context->step_index,\n' ...
    '            context->tx_payload, @MACRO@_SFUN_INPUT_PAYLOAD_OCTETS,\n' ...
    '            &context->error) != 0 ||\n' ...
    '            @NAME@_protocol_send_input_data(&context->socket,\n' ...
    '                context->tx_payload, @MACRO@_SFUN_INPUT_PAYLOAD_OCTETS,\n' ...
    '                STEP_TIMEOUT_MS, &context->error) != 0) {\n' ...
    '        @NAME@_sfun_fail_step(S, context, "@NAME@_sfun: INPUT_DATA failed.");\n' ...
    '        return;\n' ...
    '    }\n' ...
    '    if (@NAME@_protocol_wait_output_data(&context->socket,\n' ...
    '            context->rx_payload, &received_length,\n' ...
    '            @MACRO@_SFUN_OUTPUT_PAYLOAD_OCTETS, STEP_TIMEOUT_MS,\n' ...
    '            &context->error) != 0) {\n' ...
    '        if ((context->error.available &\n' ...
    '                (@MACRO@_PC_ERROR_HAS_ACTUAL_TYPE |\n' ...
    '                 @MACRO@_PC_ERROR_HAS_ACTUAL_LENGTH)) ==\n' ...
    '                (@MACRO@_PC_ERROR_HAS_ACTUAL_TYPE |\n' ...
    '                 @MACRO@_PC_ERROR_HAS_ACTUAL_LENGTH) &&\n' ...
    '                context->error.actual_type == @MACRO@_TYPE_OUTPUT_DATA &&\n' ...
    '                context->error.actual_length !=\n' ...
    '                    @MACRO@_SFUN_OUTPUT_PAYLOAD_OCTETS) {\n' ...
    '            context->error.kind = @MACRO@_PC_ERROR_PAYLOAD_LENGTH;\n' ...
    '            context->error.stage = "step_output_length";\n' ...
    '            context->error.available |=\n' ...
    '                @MACRO@_PC_ERROR_HAS_EXPECTED_TYPE |\n' ...
    '                @MACRO@_PC_ERROR_HAS_EXPECTED_LENGTH;\n' ...
    '            context->error.expected_type = @MACRO@_TYPE_OUTPUT_DATA;\n' ...
    '            context->error.expected_length =\n' ...
    '                @MACRO@_SFUN_OUTPUT_PAYLOAD_OCTETS;\n' ...
    '        }\n' ...
    '        @NAME@_sfun_fail_step(S, context, "@NAME@_sfun: OUTPUT_DATA receive failed.");\n' ...
    '        return;\n' ...
    '    }\n' ...
    '    if (received_length != @MACRO@_SFUN_OUTPUT_PAYLOAD_OCTETS) {\n' ...
    '        @NAME@_pc_error_reset(&context->error, "step_output_length");\n' ...
    '        context->error.kind = @MACRO@_PC_ERROR_PAYLOAD_LENGTH;\n' ...
    '        context->error.available = @MACRO@_PC_ERROR_HAS_EXPECTED_TYPE |\n' ...
    '            @MACRO@_PC_ERROR_HAS_ACTUAL_TYPE |\n' ...
    '            @MACRO@_PC_ERROR_HAS_EXPECTED_LENGTH |\n' ...
    '            @MACRO@_PC_ERROR_HAS_ACTUAL_LENGTH;\n' ...
    '        context->error.expected_type = @MACRO@_TYPE_OUTPUT_DATA;\n' ...
    '        context->error.actual_type = @MACRO@_TYPE_OUTPUT_DATA;\n' ...
    '        context->error.expected_length = @MACRO@_SFUN_OUTPUT_PAYLOAD_OCTETS;\n' ...
    '        context->error.actual_length = received_length;\n' ...
    '        @NAME@_sfun_fail_step(S, context, "@NAME@_sfun: OUTPUT_DATA length mismatch.");\n' ...
    '        return;\n' ...
    '    }\n' ...
    '    if (@NAME@_sfun_decode_output_payload(context->rx_payload,\n' ...
    '            received_length, context->step_index, &context->output_temp,\n' ...
    '            &context->error) != 0 ||\n' ...
    '            @NAME@_sfun_commit_output_ports(S, &context->output_temp,\n' ...
    '                &context->error) != 0) {\n' ...
    '        @NAME@_sfun_fail_step(S, context, "@NAME@_sfun: output decode or commit failed.");\n' ...
    '        return;\n' ...
    '    }\n' ...
    '    context->step_index++;\n' ...
    '}\n\n' ...
    'static void mdlTerminate(SimStruct *S)\n{\n' ...
    '    @TYPED@SfunContext *context;\n' ...
    '    if (ssGetPWork(S) == NULL) return;\n' ...
    '    context = (@TYPED@SfunContext *)ssGetPWorkValue(S, 0);\n' ...
    '    if (context == NULL) {\n' ...
    '        ssSetPWorkValue(S, 0, NULL);\n' ...
    '        return;\n' ...
    '    }\n' ...
    '    if (context->session_started != 0 &&\n' ...
    '            @NAME@_pc_socket_is_valid(&context->socket)) {\n' ...
    '        (void)@NAME@_protocol_send_sim_stop(&context->socket,\n' ...
    '            TERMINATE_TIMEOUT_MS, &context->error);\n' ...
    '    }\n' ...
    '    @NAME@_sfun_destroy_context(context);\n' ...
    '    ssSetPWorkValue(S, 0, NULL);\n}\n\n' ...
    '#ifndef MATLAB_MEX_FILE\n' ...
    '#error "@NAME@_sfun supports MATLAB MEX Normal mode only."\n' ...
    '#else\n#include "simulink.c"\n#endif\n'])];
text = strrep(text, '@NAME@', names.internal_name);
text = strrep(text, '@MACRO@', names.macro_prefix);
text = strrep(text, '@TYPED@', names.typed_prefix);
end

function text = sfun_header(names, instance, layout)
guard = [names.macro_prefix '_SFUN_H'];
temporaryFields = output_temporary_fields(instance.outputs, names.macro_prefix);
text = [generated_file_header() sprintf([ ...
    '#ifndef %s\n#define %s\n\n' ...
    '#include "simstruc.h"\n' ...
    '#include "%s_sfun_config.h"\n' ...
    '#include "%s_protocol.h"\n\n' ...
    '#ifdef __cplusplus\nextern "C" {\n#endif\n\n' ...
    'typedef struct\n{\n%s' ...
    '} %sSfunOutputTemp;\n\n' ...
    'typedef struct\n{\n' ...
    '    %sPcSocket socket;\n' ...
    '    %sPcError error;\n' ...
    '    uint32_t step_index;\n' ...
    '    int session_started;\n' ...
    '    uint8_t tx_payload[%s_SFUN_INPUT_PAYLOAD_OCTETS];\n' ...
    '    uint8_t rx_payload[%s_SFUN_OUTPUT_PAYLOAD_OCTETS];\n' ...
    '    %sSfunOutputTemp output_temp;\n' ...
    '} %sSfunContext;\n\n' ...
    '%sSfunContext *%s_sfun_create_context(void);\n' ...
    'void %s_sfun_destroy_context(%sSfunContext *context);\n' ...
    'int %s_sfun_setup_input_ports(SimStruct *S);\n' ...
    'int %s_sfun_setup_output_ports(SimStruct *S);\n' ...
    'int %s_sfun_pack_input_payload(SimStruct *S, uint32_t step_index,\n' ...
    '    uint8_t *payload, uint16_t payload_capacity, %sPcError *error);\n' ...
    'int %s_sfun_decode_output_payload(const uint8_t *payload,\n' ...
    '    uint16_t payload_length, uint32_t expected_step,\n' ...
    '    %sSfunOutputTemp *temporary, %sPcError *error);\n' ...
    'int %s_sfun_commit_output_ports(SimStruct *S,\n' ...
    '    const %sSfunOutputTemp *temporary, %sPcError *error);\n\n' ...
    '#ifdef __cplusplus\n}\n#endif\n\n' ...
    '#endif /* %s */\n'], guard, guard, names.internal_name, names.internal_name, ...
    temporaryFields, names.typed_prefix, names.typed_prefix, names.typed_prefix, ...
    names.macro_prefix, names.macro_prefix, names.typed_prefix, ...
    names.typed_prefix, names.typed_prefix, names.internal_name, ...
    names.internal_name, names.typed_prefix, names.internal_name, ...
    names.internal_name, names.internal_name, names.typed_prefix, ...
    names.internal_name, names.typed_prefix, names.typed_prefix, ...
    names.internal_name, names.typed_prefix, names.typed_prefix, guard)];
assert(layout.input_payload_octets > 0 && layout.output_payload_octets > 0);
end

function text = io_source(names, instance, layout)
name = names.internal_name;
macro = names.macro_prefix;
inputLines = port_lines(instance.inputs, 'Input', macro);
outputLines = port_lines(instance.outputs, 'Output', macro);
packLines = pack_lines(instance.inputs, layout.input_fields);
decodeLines = decode_lines(instance.outputs, layout.output_fields);
commitLines = commit_lines(instance.outputs);
helperLines = endian_helpers(layout);
body = sprintf([ ...
    '#include "simstruc.h"\n' ...
    '#include "@NAME@_sfun_config.h"\n' ...
    '#include "@NAME@_sfun.h"\n\n' ...
    '#include <string.h>\n\n@ENDIAN_HELPERS@' ...
    'int @NAME@_sfun_setup_input_ports(SimStruct *S)\n{\n' ...
    '    if (!ssSetNumInputPorts(S, @MACRO@_SFUN_INPUT_PORT_COUNT)) {\n' ...
    '        return -1;\n    }\n@INPUT_PORTS@' ...
    '    return 0;\n}\n\n' ...
    'int @NAME@_sfun_setup_output_ports(SimStruct *S)\n{\n' ...
    '    if (!ssSetNumOutputPorts(S, @MACRO@_SFUN_OUTPUT_PORT_COUNT)) {\n' ...
    '        return -1;\n    }\n@OUTPUT_PORTS@' ...
    '    return 0;\n}\n\n' ...
    'int @NAME@_sfun_pack_input_payload(SimStruct *S, uint32_t step_index,\n' ...
    '    uint8_t *payload, uint16_t payload_capacity, @TYPED@PcError *error)\n' ...
    '{\n' ...
    '    const void *signals[@MACRO@_SFUN_INPUT_PORT_COUNT];\n' ...
    '    unsigned int port;\n' ...
    '    @NAME@_pc_error_reset(error, "pack_input");\n' ...
    '    if (S == NULL || payload == NULL || error == NULL ||\n' ...
    '            payload_capacity != @MACRO@_SFUN_INPUT_PAYLOAD_OCTETS) {\n' ...
    '        if (error != NULL) {\n' ...
    '            error->kind = @MACRO@_PC_ERROR_PAYLOAD_LENGTH;\n' ...
    '            error->available = @MACRO@_PC_ERROR_HAS_EXPECTED_LENGTH |\n' ...
    '                @MACRO@_PC_ERROR_HAS_ACTUAL_LENGTH;\n' ...
    '            error->expected_length = @MACRO@_SFUN_INPUT_PAYLOAD_OCTETS;\n' ...
    '            error->actual_length = payload_capacity;\n' ...
    '        }\n' ...
    '        return -1;\n' ...
    '    }\n' ...
    '    for (port = 0u; port < @MACRO@_SFUN_INPUT_PORT_COUNT; ++port) {\n' ...
    '        signals[port] = ssGetInputPortSignal(S, port);\n' ...
    '        if (signals[port] == NULL) {\n' ...
    '            error->kind = @MACRO@_PC_ERROR_PORT_ACCESS;\n' ...
    '            return -1;\n' ...
    '        }\n' ...
    '    }\n' ...
    '    @NAME@_sfun_write_le32(payload, step_index);\n@PACK@' ...
    '    return 0;\n}\n\n' ...
    'int @NAME@_sfun_decode_output_payload(const uint8_t *payload,\n' ...
    '    uint16_t payload_length, uint32_t expected_step,\n' ...
    '    @TYPED@SfunOutputTemp *temporary, @TYPED@PcError *error)\n' ...
    '{\n' ...
    '    uint32_t actual_step;\n' ...
    '    @NAME@_pc_error_reset(error, "decode_output");\n' ...
    '    if (error != NULL) {\n' ...
    '        error->available = @MACRO@_PC_ERROR_HAS_EXPECTED_TYPE |\n' ...
    '            @MACRO@_PC_ERROR_HAS_ACTUAL_TYPE;\n' ...
    '        error->expected_type = @MACRO@_TYPE_OUTPUT_DATA;\n' ...
    '        error->actual_type = @MACRO@_TYPE_OUTPUT_DATA;\n' ...
    '    }\n' ...
    '    if (payload == NULL || temporary == NULL || error == NULL ||\n' ...
    '            payload_length != @MACRO@_SFUN_OUTPUT_PAYLOAD_OCTETS) {\n' ...
    '        if (error != NULL) {\n' ...
    '            error->kind = @MACRO@_PC_ERROR_PAYLOAD_LENGTH;\n' ...
    '            error->available |= @MACRO@_PC_ERROR_HAS_EXPECTED_LENGTH |\n' ...
    '                @MACRO@_PC_ERROR_HAS_ACTUAL_LENGTH;\n' ...
    '            error->expected_length = @MACRO@_SFUN_OUTPUT_PAYLOAD_OCTETS;\n' ...
    '            error->actual_length = payload_length;\n' ...
    '        }\n' ...
    '        return -1;\n' ...
    '    }\n' ...
    '    actual_step = @NAME@_sfun_read_le32(payload);\n' ...
    '    if (actual_step != expected_step) {\n' ...
    '        error->kind = @MACRO@_PC_ERROR_STEP_INDEX;\n' ...
    '        error->available |= @MACRO@_PC_ERROR_HAS_EXPECTED_LENGTH |\n' ...
    '            @MACRO@_PC_ERROR_HAS_ACTUAL_LENGTH |\n' ...
    '            @MACRO@_PC_ERROR_HAS_EXPECTED_STEP |\n' ...
    '            @MACRO@_PC_ERROR_HAS_ACTUAL_STEP;\n' ...
    '        error->expected_length = @MACRO@_SFUN_OUTPUT_PAYLOAD_OCTETS;\n' ...
    '        error->actual_length = payload_length;\n' ...
    '        error->expected_step = expected_step;\n' ...
    '        error->actual_step = actual_step;\n' ...
    '        return -1;\n' ...
    '    }\n@DECODE@' ...
    '    return 0;\n}\n\n' ...
    'int @NAME@_sfun_commit_output_ports(SimStruct *S,\n' ...
    '    const @TYPED@SfunOutputTemp *temporary, @TYPED@PcError *error)\n' ...
    '{\n' ...
    '    void *signals[@MACRO@_SFUN_OUTPUT_PORT_COUNT];\n' ...
    '    unsigned int port;\n' ...
    '    @NAME@_pc_error_reset(error, "commit_output");\n' ...
    '    if (S == NULL || temporary == NULL || error == NULL) {\n' ...
    '        if (error != NULL) error->kind = @MACRO@_PC_ERROR_ARGUMENT;\n' ...
    '        return -1;\n' ...
    '    }\n' ...
    '    for (port = 0u; port < @MACRO@_SFUN_OUTPUT_PORT_COUNT; ++port) {\n' ...
    '        signals[port] = ssGetOutputPortSignal(S, port);\n' ...
    '        if (signals[port] == NULL) {\n' ...
    '            error->kind = @MACRO@_PC_ERROR_PORT_ACCESS;\n' ...
    '            error->available = @MACRO@_PC_ERROR_HAS_EXPECTED_TYPE |\n' ...
    '                @MACRO@_PC_ERROR_HAS_ACTUAL_TYPE |\n' ...
    '                @MACRO@_PC_ERROR_HAS_EXPECTED_LENGTH |\n' ...
    '                @MACRO@_PC_ERROR_HAS_ACTUAL_LENGTH;\n' ...
    '            error->expected_type = @MACRO@_TYPE_OUTPUT_DATA;\n' ...
    '            error->actual_type = @MACRO@_TYPE_OUTPUT_DATA;\n' ...
    '            error->expected_length = @MACRO@_SFUN_OUTPUT_PAYLOAD_OCTETS;\n' ...
    '            error->actual_length = @MACRO@_SFUN_OUTPUT_PAYLOAD_OCTETS;\n' ...
    '            return -1;\n' ...
    '        }\n' ...
    '    }\n@COMMIT@' ...
    '    return 0;\n}\n']);
body = strrep(body, '@INPUT_PORTS@', inputLines);
body = strrep(body, '@OUTPUT_PORTS@', outputLines);
body = strrep(body, '@PACK@', packLines);
body = strrep(body, '@DECODE@', decodeLines);
body = strrep(body, '@COMMIT@', commitLines);
body = strrep(body, '@ENDIAN_HELPERS@', helperLines);
body = strrep(body, '@NAME@', name);
body = strrep(body, '@MACRO@', macro);
body = strrep(body, '@TYPED@', names.typed_prefix);
text = [generated_file_header() body];
end

function lines = port_lines(variables, direction, macro)
lines = '';
upperDirection = upper(direction);
for index = 1:numel(variables)
    port = index - 1;
    variable = variables(index);
    lines = [lines sprintf('    /* Port %u: %s */\n', port, char(variable.name))]; %#ok<AGROW>
    lines = [lines sprintf('    ssSet%sPortWidth(S, %u, %s_SFUN_%s_%u_WIDTH);\n', ...
        direction, port, macro, upperDirection, port)]; %#ok<AGROW>
    lines = [lines sprintf('    ssSet%sPortDataType(S, %u, %s_SFUN_%s_%u_DATA_TYPE);\n', ...
        direction, port, macro, upperDirection, port)]; %#ok<AGROW>
    if strcmp(direction, 'Input')
        lines = [lines sprintf( ...
            '    ssSetInputPortDirectFeedThrough(S, %u, 1);\n', port)]; %#ok<AGROW>
        lines = [lines sprintf( ...
            '    ssSetInputPortRequiredContiguous(S, %u, 1);\n', port)]; %#ok<AGROW>
    end
end
end

function text = config_header(names, instance, project, layout)
macro = names.macro_prefix;
guard = [macro '_SFUN_CONFIG_H'];
lines = { ...
    sprintf('#ifndef %s', guard), sprintf('#define %s', guard), '', ...
    '#include <float.h>', '#include <limits.h>', '#include <stdint.h>', '', ...
    sprintf('#define %s_SFUN_FUNCTION_NAME %s_sfun', macro, names.internal_name), ...
    sprintf('#define %s_SFUN_MEX_BASENAME "%s_sfun"', macro, names.internal_name), ...
    sprintf('#define %s_SFUN_SAMPLE_TIME_SEC (%.17g)', macro, double(instance.sample_time_sec)), ...
    sprintf('#define %s_SFUN_DSP_IP_ADDRESS "%s"', macro, char(project.common.network.ip)), ...
    sprintf('#define %s_SFUN_TCP_PORT %uu', macro, double(instance.iodevice.settings.tcp_port)), ...
    sprintf('#define %s_SFUN_PROTOCOL_VERSION %uu', macro, double(project.common.protocol_version)), ...
    sprintf('#define %s_SFUN_INTERFACE_HASH 0x%08Xu', macro, uint32(instance.interface_hash)), ...
    sprintf('#define %s_SFUN_ERROR_TEXT_CAPACITY 512u', macro), ...
    sprintf('#define %s_SFUN_INPUT_PORT_COUNT %uu', macro, numel(instance.inputs)), ...
    sprintf('#define %s_SFUN_OUTPUT_PORT_COUNT %uu', macro, numel(instance.outputs)), ...
    sprintf('#define %s_SFUN_STEP_INDEX_OCTETS 4u', macro), ...
    sprintf('#define %s_SFUN_INPUT_DATA_OCTETS %uu', macro, layout.input_data_octets), ...
    sprintf('#define %s_SFUN_OUTPUT_DATA_OCTETS %uu', macro, layout.output_data_octets), ...
    sprintf('#define %s_SFUN_INPUT_PAYLOAD_OCTETS %uu', macro, layout.input_payload_octets), ...
    sprintf('#define %s_SFUN_OUTPUT_PAYLOAD_OCTETS %uu', macro, layout.output_payload_octets), ...
    sprintf('#define %s_SFUN_MAX_PAYLOAD_OCTETS %uu', macro, layout.max_payload_octets), ''};
lines = [lines variable_macros(instance.inputs, 'INPUT', macro), ...
    variable_macros(instance.outputs, 'OUTPUT', macro), ...
    wire_macros(layout.input_fields, 'INPUT', macro), ...
    wire_macros(layout.output_fields, 'OUTPUT', macro), ...
    {sprintf('#if defined(__STDC_VERSION__) && (__STDC_VERSION__ >= 201112L)'), ...
    sprintf('#define %s_SFUN_STATIC_ASSERT(c_, n_) _Static_assert((c_), #n_)', macro), ...
    '#else', ...
    sprintf('#define %s_SFUN_STATIC_ASSERT(c_, n_) typedef char %s_sfun_static_assert_##n_[(c_) ? 1 : -1]', ...
        macro, lower(macro)), ...
    '#endif', '', ...
    sprintf('%s_SFUN_STATIC_ASSERT(%s_SFUN_INPUT_PORT_COUNT > 0u, input_port_count_positive);', macro, macro), ...
    sprintf('%s_SFUN_STATIC_ASSERT(%s_SFUN_OUTPUT_PORT_COUNT > 0u, output_port_count_positive);', macro, macro), ...
    sprintf('%s_SFUN_STATIC_ASSERT(CHAR_BIT == 8, char_is_8_bits);', macro), ...
    sprintf('%s_SFUN_STATIC_ASSERT(sizeof(int16_t) * CHAR_BIT == 16u, int16_is_16_bits);', macro), ...
    sprintf('%s_SFUN_STATIC_ASSERT(sizeof(uint16_t) * CHAR_BIT == 16u, uint16_is_16_bits);', macro), ...
    sprintf('%s_SFUN_STATIC_ASSERT(sizeof(int32_t) * CHAR_BIT == 32u, int32_is_32_bits);', macro), ...
    sprintf('%s_SFUN_STATIC_ASSERT(sizeof(uint32_t) * CHAR_BIT == 32u, uint32_is_32_bits);', macro), ...
    sprintf('%s_SFUN_STATIC_ASSERT(sizeof(uint64_t) * CHAR_BIT == 64u, uint64_is_64_bits);', macro), ...
    sprintf('%s_SFUN_STATIC_ASSERT(sizeof(float) * CHAR_BIT == 32u, float_is_32_bits);', macro), ...
    sprintf('%s_SFUN_STATIC_ASSERT(sizeof(double) * CHAR_BIT == 64u, double_is_64_bits);', macro), ...
    sprintf('%s_SFUN_STATIC_ASSERT(FLT_MANT_DIG == 24 && FLT_MAX_EXP == 128, float_is_binary32);', macro), ...
    sprintf('%s_SFUN_STATIC_ASSERT(DBL_MANT_DIG == 53 && DBL_MAX_EXP == 1024, double_is_binary64);', macro), ...
    sprintf('%s_SFUN_STATIC_ASSERT((%s_SFUN_INPUT_PAYLOAD_OCTETS & 1u) == 0u, input_payload_even);', macro, macro), ...
    sprintf('%s_SFUN_STATIC_ASSERT((%s_SFUN_OUTPUT_PAYLOAD_OCTETS & 1u) == 0u, output_payload_even);', macro, macro), ...
    sprintf('%s_SFUN_STATIC_ASSERT(%s_SFUN_INPUT_PAYLOAD_OCTETS <= %s_SFUN_MAX_PAYLOAD_OCTETS, input_payload_within_max);', macro, macro, macro), ...
    sprintf('%s_SFUN_STATIC_ASSERT(%s_SFUN_OUTPUT_PAYLOAD_OCTETS <= %s_SFUN_MAX_PAYLOAD_OCTETS, output_payload_within_max);', macro, macro, macro), ...
    sprintf('%s_SFUN_STATIC_ASSERT(%s_SFUN_INPUT_PAYLOAD_OCTETS <= UINT16_MAX, input_payload_u16);', macro, macro), ...
    sprintf('%s_SFUN_STATIC_ASSERT(%s_SFUN_OUTPUT_PAYLOAD_OCTETS <= UINT16_MAX, output_payload_u16);', macro, macro)}, ...
    variable_asserts(instance.inputs, 'INPUT', macro), ...
    variable_asserts(instance.outputs, 'OUTPUT', macro), ...
    {'', sprintf('#endif /* %s */', guard)}];
text = [generated_file_header() strjoin(lines, newline)];
end

function text = generated_file_header()
text = sprintf([ ...
    '/*\n' ...
    ' * AUTO-GENERATED FILE\n' ...
    ' * Manual changes will be overwritten.\n' ...
    ' */\n\n']);
end

function lines = variable_macros(variables, direction, macro)
lines = cell(1, 2 * numel(variables) + 1);
cursor = 0;
for index = 1:numel(variables)
    port = index - 1;
    cursor = cursor + 1;
    lines{cursor} = sprintf('#define %s_SFUN_%s_%u_WIDTH %uu', ...
        macro, direction, port, double(variables(index).dim));
    cursor = cursor + 1;
    lines{cursor} = sprintf('#define %s_SFUN_%s_%u_DATA_TYPE %s', ...
        macro, direction, port, simulink_type(variables(index).type));
end
lines{end} = '';
end

function lines = wire_macros(fields, direction, macro)
lines = cell(1, 2 * numel(fields) + 1);
cursor = 0;
for index = 1:numel(fields)
    port = index - 1;
    cursor = cursor + 1;
    lines{cursor} = sprintf('#define %s_SFUN_%s_%u_WIRE_OFFSET %uu', ...
        macro, direction, port, 4 + fields(index).offset_octets);
    cursor = cursor + 1;
    lines{cursor} = sprintf('#define %s_SFUN_%s_%u_WIRE_OCTETS %uu', ...
        macro, direction, port, fields(index).element_octets * fields(index).dim);
end
lines{end} = '';
end

function text = output_temporary_fields(variables, macro)
text = '';
for index = 1:numel(variables)
    text = [text sprintf('    %s output_%u[%s_SFUN_OUTPUT_%u_WIDTH];\n', ...
        c_type(variables(index).type), index - 1, macro, index - 1)]; %#ok<AGROW>
end
end

function text = endian_helpers(layout)
inputSizes = [layout.input_fields.element_octets];
outputSizes = [layout.output_fields.element_octets];
text = '';
for octets = [2 4 8]
    if octets == 4 || any(inputSizes == octets)
        text = [text write_helper(octets)]; %#ok<AGROW>
    end
    if octets == 4 || any(outputSizes == octets)
        text = [text read_helper(octets)]; %#ok<AGROW>
    end
end
end

function text = write_helper(octets)
if octets == 2
    body = sprintf([ ...
        '    buffer[0] = (uint8_t)(value & 0xffu);\n' ...
        '    buffer[1] = (uint8_t)((value >> 8) & 0xffu);\n']);
elseif octets == 4
    body = sprintf([ ...
        '    buffer[0] = (uint8_t)(value & 0xffu);\n' ...
        '    buffer[1] = (uint8_t)((value >> 8) & 0xffu);\n' ...
        '    buffer[2] = (uint8_t)((value >> 16) & 0xffu);\n' ...
        '    buffer[3] = (uint8_t)((value >> 24) & 0xffu);\n']);
else
    body = sprintf([ ...
        '    unsigned int index;\n' ...
        '    for (index = 0u; index < 8u; ++index) {\n' ...
        '        buffer[index] = (uint8_t)((value >> (8u * index)) & 0xffu);\n' ...
        '    }\n']);
end
text = sprintf('static void @NAME@_sfun_write_le%u(uint8_t *buffer, uint%u_t value)\n{\n%s}\n\n', ...
    8 * octets, 8 * octets, body);
end

function text = read_helper(octets)
if octets == 2
    body = '    return (uint16_t)((uint16_t)buffer[0] | ((uint16_t)buffer[1] << 8));';
elseif octets == 4
    body = sprintf([ ...
        '    return (uint32_t)buffer[0] | ((uint32_t)buffer[1] << 8) |\n' ...
        '        ((uint32_t)buffer[2] << 16) | ((uint32_t)buffer[3] << 24);']);
else
    body = sprintf([ ...
        '    uint64_t value = 0u;\n' ...
        '    unsigned int index;\n' ...
        '    for (index = 0u; index < 8u; ++index) {\n' ...
        '        value |= (uint64_t)buffer[index] << (8u * index);\n' ...
        '    }\n' ...
        '    return value;']);
end
text = sprintf('static uint%u_t @NAME@_sfun_read_le%u(const uint8_t *buffer)\n{\n%s\n}\n\n', ...
    8 * octets, 8 * octets, body);
end

function text = pack_lines(variables, fields)
text = '';
for index = 1:numel(variables)
    port = index - 1;
    type = char(variables(index).type);
    bits = unsigned_type(fields(index).element_octets);
    writer = sprintf('sfun_write_le%u', 8 * fields(index).element_octets);
    text = [text sprintf([ ...
        '    {\n' ...
        '        const %s *values = (const %s *)signals[%u];\n' ...
        '        unsigned int element;\n' ...
        '        for (element = 0u; element < %u; ++element) {\n' ...
        '            %s bits;\n' ...
        '            memcpy(&bits, &values[element], sizeof(bits));\n' ...
        '            %s_%s(payload + %u + element * %u, bits);\n' ...
        '        }\n' ...
        '    }\n'], c_type(type), c_type(type), port, fields(index).dim, ...
        bits, '@NAME@', writer, 4 + fields(index).offset_octets, ...
        fields(index).element_octets)]; %#ok<AGROW>
end
end

function text = decode_lines(variables, fields)
text = '';
for index = 1:numel(variables)
    port = index - 1;
    bits = unsigned_type(fields(index).element_octets);
    reader = sprintf('sfun_read_le%u', 8 * fields(index).element_octets);
    text = [text sprintf([ ...
        '    {\n' ...
        '        unsigned int element;\n' ...
        '        for (element = 0u; element < %u; ++element) {\n' ...
        '            %s bits = %s_%s(payload + %u + element * %u);\n' ...
        '            memcpy(&temporary->output_%u[element], &bits, sizeof(bits));\n' ...
        '        }\n' ...
        '    }\n'], fields(index).dim, bits, '@NAME@', reader, ...
        4 + fields(index).offset_octets, fields(index).element_octets, port)]; %#ok<AGROW>
end
end

function text = commit_lines(variables)
text = '';
for index = 1:numel(variables)
    port = index - 1;
    text = [text sprintf( ...
        '    memcpy(signals[%u], temporary->output_%u, sizeof(temporary->output_%u));\n', ...
        port, port, port)]; %#ok<AGROW>
end
end

function value = unsigned_type(octets)
value = sprintf('uint%u_t', 8 * octets);
end

function value = c_type(type)
switch char(type)
    case 'int16', value = 'int16_t';
    case 'uint16', value = 'uint16_t';
    case 'int32', value = 'int32_t';
    case 'uint32', value = 'uint32_t';
    case 'single', value = 'float';
    case 'double', value = 'double';
    otherwise
        error('C2837xBlock:SfunRender:UnsupportedType', ...
            'Unsupported S-Function port type "%s".', char(type));
end
end

function lines = variable_asserts(variables, direction, macro)
lines = cell(1, numel(variables));
for index = 1:numel(variables)
    port = index - 1;
    lines{index} = sprintf( ...
        '%s_SFUN_STATIC_ASSERT(%s_SFUN_%s_%u_WIDTH > 0u, %s_%u_width_positive);', ...
        macro, macro, direction, port, lower(direction), port);
end
end

function value = simulink_type(type)
switch char(type)
    case 'int16', value = 'SS_INT16';
    case 'uint16', value = 'SS_UINT16';
    case 'int32', value = 'SS_INT32';
    case 'uint32', value = 'SS_UINT32';
    case 'single', value = 'SS_SINGLE';
    case 'double', value = 'SS_DOUBLE';
    otherwise
        error('C2837xBlock:SfunRender:UnsupportedType', ...
            'Unsupported S-Function port type "%s".', char(type));
end
end

function validate_instance(instance)
if ~isnumeric(instance.sample_time_sec) || ~isreal(instance.sample_time_sec) || ...
        ~isscalar(instance.sample_time_sec) || ~isfinite(instance.sample_time_sec) || ...
        instance.sample_time_sec <= 0
    error('C2837xBlock:SfunRender:InvalidSampleTime', ...
        'S-Function sample time must be a finite positive scalar.');
end
validate_variables(instance.inputs);
validate_variables(instance.outputs);
end

function validate_variables(variables)
if isempty(variables)
    error('C2837xBlock:SfunRender:EmptyPorts', ...
        'S4-01 requires at least one input and one output port.');
end
for index = 1:numel(variables)
    simulink_type(variables(index).type);
    dim = variables(index).dim;
    if ~isnumeric(dim) || ~isreal(dim) || ~isscalar(dim) || ...
            ~isfinite(dim) || dim <= 0 || dim ~= fix(dim)
        error('C2837xBlock:SfunRender:InvalidPortWidth', ...
            'S-Function port widths must be finite positive integers.');
    end
end
end

function bytes = text_bytes(text)
text = strrep(text, [char(13) newline], newline);
text = strrep(text, char(13), newline);
while ~isempty(text) && text(end) == newline
    text(end) = [];
end
bytes = reshape(uint8(unicode2native([text newline], 'UTF-8')), 1, []);
end
