function rendered = c2837x_block_render_dsp_algorithm_files(project)
%C2837X_BLOCK_RENDER_DSP_ALGORITHM_FILES Render typed algorithm files.

c2837x_block_validate_project_structure(project);
prototype = struct('instance_index', 0, 'internal_name', '', ...
    'algorithm_header_bytes', zeros(1, 0, 'uint8'), ...
    'algorithm_source_available', false, ...
    'algorithm_source_bytes', zeros(1, 0, 'uint8'), ...
    'algorithm_mode', '', 'external_source_path', '');
rendered = repmat(prototype, 1, numel(project.instances));
for index = 1:numel(project.instances)
    instance = project.instances(index);
    names = c2837x_block_build_instance_c_names(instance.internal_name);
    mode = char(instance.algorithm.mode);
    sourceAvailable = false;
    sourceBytes = zeros(1, 0, 'uint8');
    externalPath = '';
    switch mode
        case 'generated_example'
            sourceAvailable = true;
            sourceBytes = text_bytes(example_source(names));
        case 'external_copy'
            source = c2837x_block_resolve_external_algorithm_source( ...
                instance.algorithm.source_path);
            sourceAvailable = true;
            sourceBytes = source.content_bytes;
            externalPath = source.source_path;
        case 'external_reference'
            source = c2837x_block_resolve_external_algorithm_source( ...
                instance.algorithm.source_path);
            externalPath = source.source_path;
        otherwise
            error('C2837xBlock:Algorithm:InvalidMode', ...
                'Unsupported algorithm mode "%s".', mode);
    end
    rendered(index) = struct('instance_index', double(index), ...
        'internal_name', names.internal_name, ...
        'algorithm_header_bytes', text_bytes(algorithm_header(instance, names)), ...
        'algorithm_source_available', sourceAvailable, ...
        'algorithm_source_bytes', sourceBytes, 'algorithm_mode', mode, ...
        'external_source_path', externalPath);
end
end

function text = algorithm_header(instance, names)
guard = ['C2837X_BLOCK_' names.macro_prefix '_ALGORITHM_H'];
text = sprintf([ ...
    '/*\n * AUTO-GENERATED FILE\n * Manual changes will be overwritten.\n */\n\n' ...
    '#ifndef %s\n#define %s\n\n' ...
    '#include "F28x_Project.h"\n#include <stdint.h>\n\n' ...
    '%s\n\n%s\n\n' ...
    'int16 %s_OnStart(void);\n\n' ...
    'int16 %s_OnStep(\n    const %s_InputData *input,\n' ...
    '    %s_OutputData *output);\n\n' ...
    'void %s_OnStop(void);\n\n#endif /* %s */\n'], ...
    guard, guard, data_type(instance.inputs, names.typed_prefix, 'InputData'), ...
    data_type(instance.outputs, names.typed_prefix, 'OutputData'), ...
    names.typed_prefix, names.typed_prefix, names.typed_prefix, ...
    names.typed_prefix, names.typed_prefix, guard);
end

function text = data_type(variables, prefix, suffix)
fields = cell(1, numel(variables));
for index = 1:numel(variables)
    variable = variables(index);
    cType = type_name(char(variable.type));
    if double(variable.dim) == 1
        fields{index} = sprintf('    %s %s;', cType, char(variable.name));
    else
        fields{index} = sprintf('    %s %s[%u];', ...
            cType, char(variable.name), double(variable.dim));
    end
end
text = sprintf('typedef struct\n{\n%s\n} %s_%s;', ...
    strjoin(fields, newline), prefix, suffix);
end

function value = type_name(type)
types = struct('int16', 'int16_t', 'uint16', 'uint16_t', ...
    'int32', 'int32_t', 'uint32', 'uint32_t', ...
    'single', 'float', 'double', 'long double');
if ~isfield(types, type)
    error('C2837xBlock:Algorithm:UnsupportedType', ...
        'Unsupported algorithm variable type "%s".', type);
end
value = types.(type);
end

function text = example_source(names)
text = sprintf([ ...
    '/*\n * USER-EDITABLE FILE\n */\n\n' ...
    '#include "%s_algorithm.h"\n#include <string.h>\n\n' ...
    'int16 %s_OnStart(void)\n{\n    return 0;\n}\n\n' ...
    'int16 %s_OnStep(\n    const %s_InputData *input,\n' ...
    '    %s_OutputData *output)\n{\n    (void)input;\n' ...
    '    memset(output, 0, sizeof(*output));\n    return 0;\n}\n\n' ...
    'void %s_OnStop(void)\n{\n}\n'], ...
    names.internal_name, names.typed_prefix, names.typed_prefix, ...
    names.typed_prefix, names.typed_prefix, names.typed_prefix);
end

function bytes = text_bytes(text)
text = strrep(text, [char(13) newline], newline);
text = strrep(text, char(13), newline);
while ~isempty(text) && text(end) == newline
    text(end) = [];
end
bytes = reshape(uint8(unicode2native([text newline], 'UTF-8')), 1, []);
end
