function c2837x_block_generate_dsp_files(config, output_path)
%C2837X_BLOCK_GENERATE_DSP_FILES  Generate DSP-side configuration files.
%
%   c2837x_block_generate_dsp_files(config, output_path)
%
%   Generates 4 files under output_path/inc/ and output_path/src/:
%     c2837x_block_algorithm.h
%     c2837x_block_config.h
%     c2837x_block_config.c
%     c2837x_block_global_variable.c

    inc_dir = fullfile(output_path, 'inc');
    src_dir = fullfile(output_path, 'src');
    if ~isfolder(inc_dir), mkdir(inc_dir); end
    if ~isfolder(src_dir), mkdir(src_dir); end

    [~, config_hash] = c2837x_block_build_hash_string(config);

    write_file(fullfile(inc_dir, 'c2837x_block_algorithm.h'), ...
               gen_algorithm_h(config));
    write_file(fullfile(inc_dir, 'c2837x_block_config.h'), ...
               gen_config_h(config, config_hash));
    write_file(fullfile(src_dir, 'c2837x_block_config.c'), ...
               gen_config_c(config));
    write_file(fullfile(src_dir, 'c2837x_block_global_variable.c'), ...
               gen_global_variable_c(config));
end

%% ---- File writer ----
function write_file(filepath, content)
    fid = fopen(filepath, 'w');
    if fid < 0
        error('Failed to write %s', filepath);
    end
    fprintf(fid, '%s', content);
    fclose(fid);
end

%% ---- c2837x_block_algorithm.h ----
function s = gen_algorithm_h(config)
    L = {};
    L{end+1} = '#ifndef C2837X_BLOCK_ALGORITHM_H';
    L{end+1} = '#define C2837X_BLOCK_ALGORITHM_H';
    L{end+1} = '';
    L{end+1} = '/*';
    L{end+1} = ' * Auto-generated by C2837xBlock Configurator.';
    L{end+1} = ' * DO NOT EDIT MANUALLY.';
    L{end+1} = ' */';
    L{end+1} = '';
    L{end+1} = '#include <stdint.h>';
    L{end+1} = '';

    % Input struct
    L{end+1} = 'typedef struct {';
    for i = 1:numel(config.inputs)
        v = config.inputs(i);
        ctype = type_to_c_type(v.type);
        if v.dim == 1
            L{end+1} = sprintf('    %s %s;', ctype, v.name);
        else
            L{end+1} = sprintf('    %s %s[%d];', ctype, v.name, v.dim);
        end
    end
    L{end+1} = '} C2837xBlock_InputData;';
    L{end+1} = '';

    % Output struct
    L{end+1} = 'typedef struct {';
    for i = 1:numel(config.outputs)
        v = config.outputs(i);
        ctype = type_to_c_type(v.type);
        if v.dim == 1
            L{end+1} = sprintf('    %s %s;', ctype, v.name);
        else
            L{end+1} = sprintf('    %s %s[%d];', ctype, v.name, v.dim);
        end
    end
    L{end+1} = '} C2837xBlock_OutputData;';
    L{end+1} = '';

    % Extern declarations
    L{end+1} = 'extern C2837xBlock_InputData  c2837x_block_input;';
    L{end+1} = 'extern C2837xBlock_OutputData c2837x_block_output;';
    L{end+1} = '';

    % Callback declarations
    L{end+1} = 'int C2837xBlock_OnSimStart(void);';
    L{end+1} = 'int C2837xBlock_OnStep(void);';
    L{end+1} = 'void C2837xBlock_OnSimStop(void);';
    L{end+1} = '';

    L{end+1} = '#endif /* C2837X_BLOCK_ALGORITHM_H */';
    s = strjoin(L, '\n');
end

%% ---- c2837x_block_config.h ----
function s = gen_config_h(config, config_hash)
    L = {};
    L{end+1} = '#ifndef C2837X_BLOCK_CONFIG_H';
    L{end+1} = '#define C2837X_BLOCK_CONFIG_H';
    L{end+1} = '';
    L{end+1} = '/*';
    L{end+1} = ' * Auto-generated by C2837xBlock Configurator.';
    L{end+1} = ' * DO NOT EDIT MANUALLY.';
    L{end+1} = ' */';
    L{end+1} = '';
    L{end+1} = '#include <stdint.h>';
    L{end+1} = '#include "F28x_Project.h"';
    L{end+1} = '';

    % Static assert macro
    L{end+1} = '/* ---- Static assert compatibility macro ---- */';
    L{end+1} = '#if defined(__STDC_VERSION__) && (__STDC_VERSION__ >= 201112L)';
    L{end+1} = '#define C2837X_STATIC_ASSERT(cond, name) _Static_assert((cond), #name)';
    L{end+1} = '#else';
    L{end+1} = '#define C2837X_STATIC_ASSERT_JOIN_(a, b) a##b';
    L{end+1} = '#define C2837X_STATIC_ASSERT_JOIN(a, b)  C2837X_STATIC_ASSERT_JOIN_(a, b)';
    L{end+1} = '#define C2837X_STATIC_ASSERT(cond, name) \';
    L{end+1} = '    typedef char C2837X_STATIC_ASSERT_JOIN(static_assertion_, __LINE__)[(cond) ? 1 : -1]';
    L{end+1} = '#endif';
    L{end+1} = '';

    % Protocol
    L{end+1} = '/* ---- Protocol configuration ---- */';
    L{end+1} = sprintf('#define C2837X_BLOCK_PROTOCOL_VERSION  0x%04Xu', config.protocol_version);
    L{end+1} = sprintf('#define C2837X_BLOCK_CONFIG_HASH       0x%08Xu', config_hash);
    L{end+1} = sprintf('#define C2837X_BLOCK_SAMPLE_TIME_SEC   %.17g', config.sample_time_sec);
    L{end+1} = '';

    % Network
    L{end+1} = '/* ---- Network configuration ---- */';
    L{end+1} = sprintf('#define C2837X_BLOCK_IP_ADDR           0x%08Xu   /* %s */', ...
                        ip_to_uint32(config.dsp_ip), config.dsp_ip);
    L{end+1} = sprintf('#define C2837X_BLOCK_GATEWAY           0x%08Xu   /* %s */', ...
                        ip_to_uint32(config.gateway), config.gateway);
    L{end+1} = sprintf('#define C2837X_BLOCK_SUBNET            0x%08Xu   /* %s */', ...
                        ip_to_uint32(config.subnet), config.subnet);
    L{end+1} = sprintf('#define C2837X_BLOCK_TCP_PORT          %du', config.tcp_port);
    L{end+1} = sprintf('#define C2837X_BLOCK_SOCKET_NUM        %du', config.socket_num);
    L{end+1} = '';

    % Double
    enable_double = strcmpi(config.double_mode, 'eabi64');
    L{end+1} = '/* ---- Double support ---- */';
    if enable_double
        L{end+1} = '#define C2837X_BLOCK_ENABLE_DOUBLE     1u';
    else
        L{end+1} = '#define C2837X_BLOCK_ENABLE_DOUBLE     0u';
    end
    L{end+1} = '';

    % MAC
    L{end+1} = '/* ---- MAC address (6 bytes) ---- */';
    mac = config.mac;
    for i = 1:6
        L{end+1} = sprintf('#define C2837X_BLOCK_MAC%d   0x%02Xu', i-1, mac(i));
    end
    L{end+1} = '';

    % Socket buffer
    L{end+1} = '/* ---- W5300 socket memory allocation (in KB) ---- */';
    L{end+1} = sprintf('#define C2837X_BLOCK_SOCKET0_TX_KB   %du', config.socket0_tx_kb);
    L{end+1} = sprintf('#define C2837X_BLOCK_SOCKET0_RX_KB   %du', config.socket0_rx_kb);
    L{end+1} = '';

    % Data counts
    L{end+1} = '/* ---- Data counts ---- */';
    L{end+1} = sprintf('#define C2837X_BLOCK_INPUT_COUNT       %du', numel(config.inputs));
    L{end+1} = sprintf('#define C2837X_BLOCK_OUTPUT_COUNT      %du', numel(config.outputs));
    L{end+1} = '';

    % Sizes
    in_data_bytes = compute_data_bytes(config.inputs);
    out_data_bytes = compute_data_bytes(config.outputs);
    L{end+1} = '/* ---- Wire byte sizes ---- */';
    L{end+1} = sprintf('#define C2837X_BLOCK_INPUT_DATA_SIZE_BYTES      %du   /* %s */', ...
                        in_data_bytes, describe_vars(config.inputs));
    L{end+1} = sprintf('#define C2837X_BLOCK_OUTPUT_DATA_SIZE_BYTES     %du   /* %s */', ...
                        out_data_bytes, describe_vars(config.outputs));
    L{end+1} = '#define C2837X_BLOCK_INPUT_PAYLOAD_SIZE_BYTES   (4u + C2837X_BLOCK_INPUT_DATA_SIZE_BYTES)';
    L{end+1} = '#define C2837X_BLOCK_OUTPUT_PAYLOAD_SIZE_BYTES  (4u + C2837X_BLOCK_OUTPUT_DATA_SIZE_BYTES)';
    L{end+1} = '';

    L{end+1} = '/* ---- DSP word sizes ---- */';
    L{end+1} = '#define C2837X_BLOCK_INPUT_DATA_SIZE_WORDS      (C2837X_BLOCK_INPUT_DATA_SIZE_BYTES / 2u)';
    L{end+1} = '#define C2837X_BLOCK_OUTPUT_DATA_SIZE_WORDS     (C2837X_BLOCK_OUTPUT_DATA_SIZE_BYTES / 2u)';
    L{end+1} = '#define C2837X_BLOCK_INPUT_PAYLOAD_SIZE_WORDS   (C2837X_BLOCK_INPUT_PAYLOAD_SIZE_BYTES / 2u)';
    L{end+1} = '#define C2837X_BLOCK_OUTPUT_PAYLOAD_SIZE_WORDS  (C2837X_BLOCK_OUTPUT_PAYLOAD_SIZE_BYTES / 2u)';
    L{end+1} = '';

    % Serialization declarations
    L{end+1} = '/* ---- Payload pack/unpack functions ---- */';
    L{end+1} = 'void c2837x_block_unpack_input_payload(const uint16_t* payload_words,';
    L{end+1} = '                                       uint32_t* step_index);';
    L{end+1} = 'void c2837x_block_pack_output_payload(uint16_t* payload_words,';
    L{end+1} = '                                      uint32_t step_index);';
    L{end+1} = '';

    L{end+1} = '#endif /* C2837X_BLOCK_CONFIG_H */';
    s = strjoin(L, '\n');
end

%% ---- c2837x_block_config.c ----
function s = gen_config_c(config)
    need_double = any(strcmp({config.inputs.type}, 'double')) || ...
                  any(strcmp({config.outputs.type}, 'double'));
    L = {};
    L{end+1} = '/*';
    L{end+1} = ' * Auto-generated by C2837xBlock Configurator.';
    L{end+1} = ' * DO NOT EDIT MANUALLY.';
    L{end+1} = ' *';
    L{end+1} = ' * DSP-side payload serialization (uint16_t word buffer).';
    L{end+1} = ' * Wire format: little-endian, low word first.';
    L{end+1} = ' */';
    L{end+1} = '';
    L{end+1} = '#include "c2837x_block_config.h"';
    L{end+1} = '#include "c2837x_block_algorithm.h"';
    L{end+1} = '#include <limits.h>';
    L{end+1} = '#include <string.h>';
    L{end+1} = '';

    % Static asserts
    L{end+1} = '/* ---- Static asserts ---- */';
    L{end+1} = 'C2837X_STATIC_ASSERT((sizeof(uint16_t) * CHAR_BIT) == 16u,';
    L{end+1} = '                     uint16_bit_size_mismatch);';
    L{end+1} = 'C2837X_STATIC_ASSERT((sizeof(uint32_t) * CHAR_BIT) == 32u,';
    L{end+1} = '                     uint32_bit_size_mismatch);';
    L{end+1} = 'C2837X_STATIC_ASSERT((sizeof(float) * CHAR_BIT) == 32u,';
    L{end+1} = '                     single_bit_size_mismatch);';
    L{end+1} = 'C2837X_STATIC_ASSERT((C2837X_BLOCK_INPUT_DATA_SIZE_BYTES % 2u) == 0u,';
    L{end+1} = '                     input_data_size_must_be_even);';
    L{end+1} = 'C2837X_STATIC_ASSERT((C2837X_BLOCK_OUTPUT_DATA_SIZE_BYTES % 2u) == 0u,';
    L{end+1} = '                     output_data_size_must_be_even);';
    L{end+1} = '';

    % Serialization helpers - only generate needed functions
    all_types = unique([{config.inputs.type}, {config.outputs.type}]);
    L{end+1} = '/* ---- Serialization helpers ---- */';
    L{end+1} = '';
    L = [L, gen_dsp_helpers(all_types)];
    L{end+1} = '';

    if need_double
        L{end+1} = '#if C2837X_BLOCK_ENABLE_DOUBLE';
        L{end+1} = 'C2837X_STATIC_ASSERT((sizeof(double) * CHAR_BIT) == 64u,';
        L{end+1} = '                     double_bit_size_mismatch);';
        L{end+1} = '';
        L = [L, gen_dsp_double_helpers()];
        L{end+1} = '#endif';
        L{end+1} = '';
    end

    % Unpack input
    L{end+1} = '/* ---- Unpack INPUT_DATA payload ----';
    L{end+1} = ' * Payload layout (words):';
    L{end+1} = ' *   [0..1] step_index (uint32)';
    word_off = 2;
    for i = 1:numel(config.inputs)
        v = config.inputs(i);
        w = type_word_size(v.type);
        if v.dim == 1
            L{end+1} = sprintf(' *   [%d]    %s (%s)', word_off, v.name, v.type);
            word_off = word_off + w;
        else
            L{end+1} = sprintf(' *   [%d..%d] %s[%d] (%s)', word_off, ...
                               word_off + w*v.dim - 1, v.name, v.dim, v.type);
            word_off = word_off + w * v.dim;
        end
    end
    L{end+1} = ' */';
    L{end+1} = 'void c2837x_block_unpack_input_payload(const uint16_t* payload_words,';
    L{end+1} = '                                       uint32_t* step_index)';
    L{end+1} = '{';
    L{end+1} = '    uint32_t offset = 0;';
    L{end+1} = '';
    L{end+1} = '    *step_index = read_uint32(payload_words, &offset);';
    L{end+1} = '';
    for i = 1:numel(config.inputs)
        v = config.inputs(i);
        rfn = read_fn_name(v.type);
        if v.dim == 1
            L{end+1} = sprintf('    c2837x_block_input.%s = %s(payload_words, &offset);', ...
                               v.name, rfn);
        else
            L{end+1} = sprintf('    {');
            L{end+1} = sprintf('        int i;');
            L{end+1} = sprintf('        for (i = 0; i < %d; ++i)', v.dim);
            L{end+1} = sprintf('            c2837x_block_input.%s[i] = %s(payload_words, &offset);', ...
                               v.name, rfn);
            L{end+1} = sprintf('    }');
        end
    end
    L{end+1} = '}';
    L{end+1} = '';

    % Pack output
    L{end+1} = '/* ---- Pack OUTPUT_DATA payload ----';
    L{end+1} = ' * Payload layout (words):';
    L{end+1} = ' *   [0..1] step_index (uint32)';
    word_off = 2;
    for i = 1:numel(config.outputs)
        v = config.outputs(i);
        w = type_word_size(v.type);
        if v.dim == 1
            L{end+1} = sprintf(' *   [%d]    %s (%s)', word_off, v.name, v.type);
            word_off = word_off + w;
        else
            L{end+1} = sprintf(' *   [%d..%d] %s[%d] (%s)', word_off, ...
                               word_off + w*v.dim - 1, v.name, v.dim, v.type);
            word_off = word_off + w * v.dim;
        end
    end
    L{end+1} = ' */';
    L{end+1} = 'void c2837x_block_pack_output_payload(uint16_t* payload_words,';
    L{end+1} = '                                      uint32_t step_index)';
    L{end+1} = '{';
    L{end+1} = '    uint32_t offset = 0;';
    L{end+1} = '';
    L{end+1} = '    write_uint32(payload_words, &offset, step_index);';
    L{end+1} = '';
    for i = 1:numel(config.outputs)
        v = config.outputs(i);
        wfn = write_fn_name(v.type);
        if v.dim == 1
            L{end+1} = sprintf('    %s(payload_words, &offset, c2837x_block_output.%s);', ...
                               wfn, v.name);
        else
            L{end+1} = sprintf('    {');
            L{end+1} = sprintf('        int i;');
            L{end+1} = sprintf('        for (i = 0; i < %d; ++i)', v.dim);
            L{end+1} = sprintf('            %s(payload_words, &offset, c2837x_block_output.%s[i]);', ...
                               wfn, v.name);
            L{end+1} = sprintf('    }');
        end
    end
    L{end+1} = '}';
    L{end+1} = '';

    s = strjoin(L, '\n');
end

%% ---- c2837x_block_global_variable.c ----
function s = gen_global_variable_c(config)
    L = {};
    L{end+1} = '/*';
    L{end+1} = ' * Auto-generated by C2837xBlock Configurator.';
    L{end+1} = ' * DO NOT EDIT MANUALLY.';
    L{end+1} = ' */';
    L{end+1} = '';
    L{end+1} = '#include "c2837x_block_algorithm.h"';
    L{end+1} = '';
    L{end+1} = 'C2837xBlock_InputData  c2837x_block_input;';
    L{end+1} = 'C2837xBlock_OutputData c2837x_block_output;';
    L{end+1} = '';
    s = strjoin(L, '\n');
end

%% ---- DSP serialization helpers ----
function L = gen_dsp_helpers(used_types)
    L = {};
    need_int16  = any(strcmp(used_types, 'int16'));
    need_uint16 = any(strcmp(used_types, 'uint16'));
    need_int32  = any(strcmp(used_types, 'int32'));
    need_uint32 = any(strcmp(used_types, 'uint32'));
    need_single = any(strcmp(used_types, 'single'));

    % uint16 (DSP: read_int16 does NOT call read_uint16, so only needed for uint16 vars)
    L = [L, gen_block('read_uint16', need_uint16, { ...
        'static inline uint16_t read_uint16(const uint16_t* buf, uint32_t* offset)', ...
        '{', ...
        '    return buf[(*offset)++];', ...
        '}'; ...
    })];
    L = [L, gen_block('write_uint16', need_uint16, { ...
        'static inline void write_uint16(uint16_t* buf, uint32_t* offset, uint16_t val)', ...
        '{', ...
        '    buf[(*offset)++] = val;', ...
        '}'; ...
    })];
    if need_uint16, L{end+1} = ''; end

    % int16
    L = [L, gen_block('read_int16', need_int16, { ...
        'static inline int16_t read_int16(const uint16_t* buf, uint32_t* offset)', ...
        '{', ...
        '    return (int16_t)buf[(*offset)++];', ...
        '}'; ...
    })];
    L = [L, gen_block('write_int16', need_int16, { ...
        'static inline void write_int16(uint16_t* buf, uint32_t* offset, int16_t val)', ...
        '{', ...
        '    buf[(*offset)++] = (uint16_t)val;', ...
        '}'; ...
    })];
    if need_int16, L{end+1} = ''; end

    % uint32 is base for int32/uint32/single and step_index (always needed)
    L = [L, gen_block('read_uint32', true, { ...
        'static inline uint32_t read_uint32(const uint16_t* buf, uint32_t* offset)', ...
        '{', ...
        '    uint32_t lo = (uint32_t)buf[(*offset)++];', ...
        '    uint32_t hi = (uint32_t)buf[(*offset)++];', ...
        '    return lo | (hi << 16);', ...
        '}'; ...
    })];
    L = [L, gen_block('write_uint32', true, { ...
        'static inline void write_uint32(uint16_t* buf, uint32_t* offset, uint32_t val)', ...
        '{', ...
        '    buf[(*offset)++] = (uint16_t)(val & 0xFFFFu);', ...
        '    buf[(*offset)++] = (uint16_t)((val >> 16) & 0xFFFFu);', ...
        '}'; ...
    })];
    L{end+1} = '';

    % int32
    L = [L, gen_block('read_int32', need_int32, { ...
        'static inline int32_t read_int32(const uint16_t* buf, uint32_t* offset)', ...
        '{', ...
        '    return (int32_t)read_uint32(buf, offset);', ...
        '}'; ...
    })];
    L = [L, gen_block('write_int32', need_int32, { ...
        'static inline void write_int32(uint16_t* buf, uint32_t* offset, int32_t val)', ...
        '{', ...
        '    write_uint32(buf, offset, (uint32_t)val);', ...
        '}'; ...
    })];
    if need_int32, L{end+1} = ''; end

    % single
    L = [L, gen_block('read_single', need_single, { ...
        'static inline float read_single(const uint16_t* buf, uint32_t* offset)', ...
        '{', ...
        '    uint32_t raw = read_uint32(buf, offset);', ...
        '    float val;', ...
        '    memcpy(&val, &raw, sizeof(val));', ...
        '    return val;', ...
        '}'; ...
    })];
    L = [L, gen_block('write_single', need_single, { ...
        'static inline void write_single(uint16_t* buf, uint32_t* offset, float val)', ...
        '{', ...
        '    uint32_t raw;', ...
        '    memcpy(&raw, &val, sizeof(raw));', ...
        '    write_uint32(buf, offset, raw);', ...
        '}'; ...
    })];
end

function L = gen_block(~, active, lines)
    L = {};
    if ~active
        for i = 1:numel(lines)
            L{end+1} = ['// ' lines{i}];
        end
    else
        for i = 1:numel(lines)
            L{end+1} = lines{i};
        end
    end
end

function L = gen_dsp_double_helpers()
    L = {};
    L{end+1} = 'static inline void write_double64(uint16_t* buf, uint32_t* offset, double val)';
    L{end+1} = '{';
    L{end+1} = '    uint16_t raw_words[4];';
    L{end+1} = '    memcpy(raw_words, &val, sizeof(raw_words));';
    L{end+1} = '    buf[(*offset)++] = raw_words[0];';
    L{end+1} = '    buf[(*offset)++] = raw_words[1];';
    L{end+1} = '    buf[(*offset)++] = raw_words[2];';
    L{end+1} = '    buf[(*offset)++] = raw_words[3];';
    L{end+1} = '}';
    L{end+1} = '';
    L{end+1} = 'static inline double read_double64(const uint16_t* buf, uint32_t* offset)';
    L{end+1} = '{';
    L{end+1} = '    uint16_t raw_words[4];';
    L{end+1} = '    double val;';
    L{end+1} = '    raw_words[0] = buf[(*offset)++];';
    L{end+1} = '    raw_words[1] = buf[(*offset)++];';
    L{end+1} = '    raw_words[2] = buf[(*offset)++];';
    L{end+1} = '    raw_words[3] = buf[(*offset)++];';
    L{end+1} = '    memcpy(&val, raw_words, sizeof(raw_words));';
    L{end+1} = '    return val;';
    L{end+1} = '}';
end

%% ---- Helper functions ----
function bytes = compute_data_bytes(vars)
    bytes = 0;
    for i = 1:numel(vars)
        bytes = bytes + type_wire_bytes(vars(i).type) * vars(i).dim;
    end
end

function b = type_wire_bytes(t)
    switch t
        case {'int16','uint16'}, b = 2;
        case {'int32','uint32','single'}, b = 4;
        case 'double', b = 8;
    end
end

function w = type_word_size(t)
    w = type_wire_bytes(t) / 2;
end

function s = describe_vars(vars)
    parts = cell(1, numel(vars));
    for i = 1:numel(vars)
        v = vars(i);
        if v.dim == 1
            parts{i} = sprintf('%d x %s', type_wire_bytes(v.type)/2, v.type);
        else
            parts{i} = sprintf('%d x %s[%d]', v.dim, v.type, v.dim);
        end
    end
    s = strjoin(parts, ' + ');
end

function c = type_to_c_type(t)
    switch t
        case 'int16',  c = 'int16_t';
        case 'uint16', c = 'uint16_t';
        case 'int32',  c = 'int32_t';
        case 'uint32', c = 'uint32_t';
        case 'single', c = 'float';
        case 'double', c = 'double';
    end
end

function fn = read_fn_name(t)
    switch t
        case 'int16',  fn = 'read_int16';
        case 'uint16', fn = 'read_uint16';
        case 'int32',  fn = 'read_int32';
        case 'uint32', fn = 'read_uint32';
        case 'single', fn = 'read_single';
        case 'double', fn = 'read_double64';
    end
end

function fn = write_fn_name(t)
    switch t
        case 'int16',  fn = 'write_int16';
        case 'uint16', fn = 'write_uint16';
        case 'int32',  fn = 'write_int32';
        case 'uint32', fn = 'write_uint32';
        case 'single', fn = 'write_single';
        case 'double', fn = 'write_double64';
    end
end

function val = ip_to_uint32(ip_str)
    parts = strsplit(ip_str, '.');
    if numel(parts) ~= 4
        error('Invalid IP address "%s": expected 4 octets.', ip_str);
    end
    nums = str2double(parts);
    if any(isnan(nums)) || any(nums < 0) || any(nums > 255) || any(nums ~= floor(nums))
        error('Invalid IP address "%s": each octet must be 0..255.', ip_str);
    end
    val = uint32(nums(1)) * 16777216 + ...
          uint32(nums(2)) * 65536 + ...
          uint32(nums(3)) * 256 + ...
          uint32(nums(4));
end
