function c2837x_block_generate_pc_files(config, output_path)
%C2837X_BLOCK_GENERATE_PC_FILES  Generate PC-side configuration files.
%
%   c2837x_block_generate_pc_files(config, output_path)
%
%   Generates 2 files under output_path/inc/ and output_path/src/:
%     c2837x_block_pc_config.h
%     c2837x_block_pc_config.c

    inc_dir = fullfile(output_path, 'inc');
    src_dir = fullfile(output_path, 'src');
    if ~isfolder(inc_dir), mkdir(inc_dir); end
    if ~isfolder(src_dir), mkdir(src_dir); end

    [~, config_hash] = c2837x_block_build_hash_string(config);

    write_file(fullfile(inc_dir, 'c2837x_block_pc_config.h'), ...
               gen_pc_config_h(config, config_hash));
    write_file(fullfile(src_dir, 'c2837x_block_pc_config.c'), ...
               gen_pc_config_c(config));
end

%% ---- File writer ----
function write_file(filepath, content)
    fid = fopen(filepath, 'w');
    if fid < 0
        error('Failed to write %s', filepath);
    end
    fprintf(fid, '%s', content);
    fclose(fid);
end

%% ---- c2837x_block_pc_config.h ----
function s = gen_pc_config_h(config, config_hash)
    L = {};
    L{end+1} = '#ifndef C2837X_BLOCK_PC_CONFIG_H';
    L{end+1} = '#define C2837X_BLOCK_PC_CONFIG_H';
    L{end+1} = '';
    L{end+1} = '/*';
    L{end+1} = ' * Auto-generated by C2837xBlock Configurator.';
    L{end+1} = ' * DO NOT EDIT MANUALLY.';
    L{end+1} = ' *';
    L{end+1} = ' * PC/Simulink C S-Function side configuration.';
    L{end+1} = ' */';
    L{end+1} = '';
    L{end+1} = '#include <stdint.h>';
    L{end+1} = '';

    % Protocol
    L{end+1} = '/* ---- Protocol configuration ---- */';
    L{end+1} = sprintf('#define C2837X_BLOCK_PROTOCOL_VERSION  0x%04Xu', config.protocol_version);
    L{end+1} = sprintf('#define C2837X_BLOCK_CONFIG_HASH       0x%08Xu', config_hash);
    L{end+1} = sprintf('#define C2837X_BLOCK_SAMPLE_TIME_SEC   %.17g', config.sample_time_sec);
    L{end+1} = '';

    % Network (PC side uses string IP)
    L{end+1} = '/* ---- Network configuration ---- */';
    L{end+1} = sprintf('#define C2837X_BLOCK_IP_ADDR           "%s"', config.dsp_ip);
    L{end+1} = sprintf('#define C2837X_BLOCK_TCP_PORT          %du', config.tcp_port);
    L{end+1} = '';

    % Max payload
    L{end+1} = sprintf('#define C2837X_BLOCK_MAX_PAYLOAD_SIZE_BYTES       %du', config.max_payload_size_bytes);
    L{end+1} = '#define C2837X_BLOCK_MAX_FRAME_SIZE_BYTES         (4u + C2837X_BLOCK_MAX_PAYLOAD_SIZE_BYTES)';
    L{end+1} = '';

    % PC timeouts
    L{end+1} = '/* ---- PC-side timeouts ---- */';
    L{end+1} = '#define C2837X_BLOCK_PC_CONNECT_TIMEOUT_MS        5000u';
    L{end+1} = '#define C2837X_BLOCK_PC_STEP_TIMEOUT_MS           5000u';
    L{end+1} = '#define C2837X_BLOCK_PC_TERMINATE_TIMEOUT_MS      1000u';
    L{end+1} = '';

    % Data counts
    L{end+1} = '/* ---- Data counts ---- */';
    L{end+1} = sprintf('#define C2837X_BLOCK_INPUT_COUNT       %du', numel(config.inputs));
    L{end+1} = sprintf('#define C2837X_BLOCK_OUTPUT_COUNT      %du', numel(config.outputs));
    L{end+1} = '';

    % Sizes
    in_data_bytes = compute_data_bytes(config.inputs);
    out_data_bytes = compute_data_bytes(config.outputs);
    L{end+1} = '/* ---- Wire byte sizes ---- */';
    L{end+1} = sprintf('#define C2837X_BLOCK_INPUT_DATA_SIZE_BYTES      %du', in_data_bytes);
    L{end+1} = sprintf('#define C2837X_BLOCK_OUTPUT_DATA_SIZE_BYTES     %du', out_data_bytes);
    L{end+1} = '#define C2837X_BLOCK_INPUT_PAYLOAD_SIZE_BYTES   (4u + C2837X_BLOCK_INPUT_DATA_SIZE_BYTES)';
    L{end+1} = '#define C2837X_BLOCK_OUTPUT_PAYLOAD_SIZE_BYTES  (4u + C2837X_BLOCK_OUTPUT_DATA_SIZE_BYTES)';
    L{end+1} = '';

    % Input struct
    L{end+1} = '/* ---- Data structures ---- */';
    L{end+1} = 'typedef struct {';
    for i = 1:numel(config.inputs)
        v = config.inputs(i);
        ctype = type_to_c_type(v.type);
        if v.dim == 1
            L{end+1} = sprintf('    %s %s;', ctype, v.name);
        else
            L{end+1} = sprintf('    %s %s[%d];', ctype, v.name, v.dim);
        end
    end
    L{end+1} = '} C2837xBlock_InputData;';
    L{end+1} = '';

    % Output struct
    L{end+1} = 'typedef struct {';
    for i = 1:numel(config.outputs)
        v = config.outputs(i);
        ctype = type_to_c_type(v.type);
        if v.dim == 1
            L{end+1} = sprintf('    %s %s;', ctype, v.name);
        else
            L{end+1} = sprintf('    %s %s[%d];', ctype, v.name, v.dim);
        end
    end
    L{end+1} = '} C2837xBlock_OutputData;';
    L{end+1} = '';

    % Serialization declarations
    L{end+1} = '/* ---- Payload pack/unpack functions (uint8_t* buffer) ---- */';
    L{end+1} = 'void c2837x_block_pack_input_payload(uint8_t* payload,';
    L{end+1} = '                                      uint32_t step_index,';
    L{end+1} = '                                      const C2837xBlock_InputData* src);';
    L{end+1} = 'void c2837x_block_unpack_output_payload(const uint8_t* payload,';
    L{end+1} = '                                        uint32_t* step_index,';
    L{end+1} = '                                        C2837xBlock_OutputData* dst);';
    L{end+1} = '';

    L{end+1} = '#endif /* C2837X_BLOCK_PC_CONFIG_H */';
    s = strjoin(L, '\n');
end

%% ---- c2837x_block_pc_config.c ----
function s = gen_pc_config_c(config)
    need_double = any(strcmp({config.inputs.type}, 'double')) || ...
                  any(strcmp({config.outputs.type}, 'double'));
    L = {};
    L{end+1} = '/*';
    L{end+1} = ' * Auto-generated by C2837xBlock Configurator.';
    L{end+1} = ' * DO NOT EDIT MANUALLY.';
    L{end+1} = ' *';
    L{end+1} = ' * PC-side payload serialization (uint8_t* buffer).';
    L{end+1} = ' * Wire format: little-endian.';
    L{end+1} = ' */';
    L{end+1} = '';
    L{end+1} = '#include "c2837x_block_pc_config.h"';
    L{end+1} = '#include <string.h>';
    L{end+1} = '';

    % Serialization helpers - only generate needed functions
    all_types = unique([{config.inputs.type}, {config.outputs.type}]);
    L{end+1} = '/* ---- Serialization helpers ---- */';
    L{end+1} = '';
    L = [L, gen_pc_helpers(all_types)];
    L{end+1} = '';

    if need_double
        L{end+1} = '/* double support */';
        L = [L, gen_pc_double_helper()];
        L{end+1} = '';
    end

    % Pack input
    L{end+1} = '/* ---- Pack INPUT_DATA payload ---- */';
    L{end+1} = 'void c2837x_block_pack_input_payload(uint8_t* payload,';
    L{end+1} = '                                      uint32_t step_index,';
    L{end+1} = '                                      const C2837xBlock_InputData* src)';
    L{end+1} = '{';
    L{end+1} = '    uint32_t offset = 0;';
    L{end+1} = '';
    L{end+1} = '    write_uint32(payload, &offset, step_index);';
    for i = 1:numel(config.inputs)
        v = config.inputs(i);
        wfn = write_fn_name(v.type);
        if v.dim == 1
            L{end+1} = sprintf('    %s(payload, &offset, src->%s);', wfn, v.name);
        else
            L{end+1} = sprintf('    {');
            L{end+1} = sprintf('        int i;');
            L{end+1} = sprintf('        for (i = 0; i < %d; ++i)', v.dim);
            L{end+1} = sprintf('            %s(payload, &offset, src->%s[i]);', wfn, v.name);
            L{end+1} = sprintf('    }');
        end
    end
    L{end+1} = '}';
    L{end+1} = '';

    % Unpack output
    L{end+1} = '/* ---- Unpack OUTPUT_DATA payload ---- */';
    L{end+1} = 'void c2837x_block_unpack_output_payload(const uint8_t* payload,';
    L{end+1} = '                                        uint32_t* step_index,';
    L{end+1} = '                                        C2837xBlock_OutputData* dst)';
    L{end+1} = '{';
    L{end+1} = '    uint32_t offset = 0;';
    L{end+1} = '';
    L{end+1} = '    *step_index = read_uint32(payload, &offset);';
    for i = 1:numel(config.outputs)
        v = config.outputs(i);
        rfn = read_fn_name(v.type);
        if v.dim == 1
            L{end+1} = sprintf('    dst->%s = %s(payload, &offset);', v.name, rfn);
        else
            L{end+1} = sprintf('    {');
            L{end+1} = sprintf('        int i;');
            L{end+1} = sprintf('        for (i = 0; i < %d; ++i)', v.dim);
            L{end+1} = sprintf('            dst->%s[i] = %s(payload, &offset);', v.name, rfn);
            L{end+1} = sprintf('    }');
        end
    end
    L{end+1} = '}';
    L{end+1} = '';

    s = strjoin(L, '\n');
end

%% ---- PC serialization helpers ----
function L = gen_pc_helpers(used_types)
    L = {};
    need_int16  = any(strcmp(used_types, 'int16'));
    need_uint16 = any(strcmp(used_types, 'uint16'));
    need_int32  = any(strcmp(used_types, 'int32'));
    need_uint32 = any(strcmp(used_types, 'uint32'));
    need_single = any(strcmp(used_types, 'single'));
    need_uint16_base = need_int16 || need_uint16;  % PC: read_int16 calls read_uint16

    % uint16 (PC: read_int16 calls read_uint16, so needed for int16 or uint16)
    L = [L, gen_block('write_uint16', need_uint16_base, { ...
        'static inline void write_uint16(uint8_t* buf, uint32_t* offset, uint16_t val)', ...
        '{', ...
        '    buf[*offset]     = (uint8_t)(val & 0xFFu);', ...
        '    buf[*offset + 1] = (uint8_t)((val >> 8) & 0xFFu);', ...
        '    *offset += 2u;', ...
        '}'; ...
    })];
    L = [L, gen_block('read_uint16', need_uint16_base, { ...
        'static inline uint16_t read_uint16(const uint8_t* buf, uint32_t* offset)', ...
        '{', ...
        '    uint16_t val = (uint16_t)((uint16_t)buf[*offset] |', ...
        '                              ((uint16_t)buf[*offset + 1] << 8));', ...
        '    *offset += 2u;', ...
        '    return val;', ...
        '}'; ...
    })];
    if need_uint16_base, L{end+1} = ''; end

    % int16
    L = [L, gen_block('write_int16', need_int16, { ...
        'static inline void write_int16(uint8_t* buf, uint32_t* offset, int16_t val)', ...
        '{', ...
        '    write_uint16(buf, offset, (uint16_t)val);', ...
        '}'; ...
    })];
    L = [L, gen_block('read_int16', need_int16, { ...
        'static inline int16_t read_int16(const uint8_t* buf, uint32_t* offset)', ...
        '{', ...
        '    return (int16_t)read_uint16(buf, offset);', ...
        '}'; ...
    })];
    if need_int16, L{end+1} = ''; end

    % uint32 is base for int32/uint32/single (always needed for step_index)
    L = [L, gen_block('write_uint32', true, { ...
        'static inline void write_uint32(uint8_t* buf, uint32_t* offset, uint32_t val)', ...
        '{', ...
        '    buf[*offset]     = (uint8_t)(val & 0xFFu);', ...
        '    buf[*offset + 1] = (uint8_t)((val >> 8) & 0xFFu);', ...
        '    buf[*offset + 2] = (uint8_t)((val >> 16) & 0xFFu);', ...
        '    buf[*offset + 3] = (uint8_t)((val >> 24) & 0xFFu);', ...
        '    *offset += 4u;', ...
        '}'; ...
    })];
    L = [L, gen_block('read_uint32', true, { ...
        'static inline uint32_t read_uint32(const uint8_t* buf, uint32_t* offset)', ...
        '{', ...
        '    uint32_t val = ((uint32_t)buf[*offset]) |', ...
        '                   ((uint32_t)buf[*offset + 1] << 8) |', ...
        '                   ((uint32_t)buf[*offset + 2] << 16) |', ...
        '                   ((uint32_t)buf[*offset + 3] << 24);', ...
        '    *offset += 4u;', ...
        '    return val;', ...
        '}'; ...
    })];
    L{end+1} = '';

    % int32
    L = [L, gen_block('write_int32', need_int32, { ...
        'static inline void write_int32(uint8_t* buf, uint32_t* offset, int32_t val)', ...
        '{', ...
        '    write_uint32(buf, offset, (uint32_t)val);', ...
        '}'; ...
    })];
    L = [L, gen_block('read_int32', need_int32, { ...
        'static inline int32_t read_int32(const uint8_t* buf, uint32_t* offset)', ...
        '{', ...
        '    return (int32_t)read_uint32(buf, offset);', ...
        '}'; ...
    })];
    if need_int32, L{end+1} = ''; end

    % single
    L = [L, gen_block('write_single', need_single, { ...
        'static inline void write_single(uint8_t* buf, uint32_t* offset, float val)', ...
        '{', ...
        '    uint32_t raw;', ...
        '    memcpy(&raw, &val, sizeof(raw));', ...
        '    write_uint32(buf, offset, raw);', ...
        '}'; ...
    })];
    L = [L, gen_block('read_single', need_single, { ...
        'static inline float read_single(const uint8_t* buf, uint32_t* offset)', ...
        '{', ...
        '    uint32_t raw = read_uint32(buf, offset);', ...
        '    float val;', ...
        '    memcpy(&val, &raw, sizeof(val));', ...
        '    return val;', ...
        '}'; ...
    })];
end

function L = gen_block(~, active, lines)
    L = {};
    if ~active
        for i = 1:numel(lines)
            L{end+1} = ['// ' lines{i}];
        end
    else
        for i = 1:numel(lines)
            L{end+1} = lines{i};
        end
    end
end

function L = gen_pc_double_helper()
    L = {};
    L{end+1} = 'static inline void write_double64(uint8_t* buf, uint32_t* offset, double val)';
    L{end+1} = '{';
    L{end+1} = '    uint8_t raw[8];';
    L{end+1} = '    memcpy(raw, &val, sizeof(raw));';
    L{end+1} = '    buf[(*offset)++] = raw[0];';
    L{end+1} = '    buf[(*offset)++] = raw[1];';
    L{end+1} = '    buf[(*offset)++] = raw[2];';
    L{end+1} = '    buf[(*offset)++] = raw[3];';
    L{end+1} = '    buf[(*offset)++] = raw[4];';
    L{end+1} = '    buf[(*offset)++] = raw[5];';
    L{end+1} = '    buf[(*offset)++] = raw[6];';
    L{end+1} = '    buf[(*offset)++] = raw[7];';
    L{end+1} = '}';
    L{end+1} = '';
    L{end+1} = 'static inline double read_double64(const uint8_t* buf, uint32_t* offset)';
    L{end+1} = '{';
    L{end+1} = '    double val;';
    L{end+1} = '    memcpy(&val, buf + *offset, sizeof(val));';
    L{end+1} = '    *offset += 8u;';
    L{end+1} = '    return val;';
    L{end+1} = '}';
end

%% ---- Helper functions ----
function bytes = compute_data_bytes(vars)
    bytes = 0;
    for i = 1:numel(vars)
        bytes = bytes + type_wire_bytes(vars(i).type) * vars(i).dim;
    end
end

function b = type_wire_bytes(t)
    switch t
        case {'int16','uint16'}, b = 2;
        case {'int32','uint32','single'}, b = 4;
        case 'double', b = 8;
    end
end

function c = type_to_c_type(t)
    switch t
        case 'int16',  c = 'int16_t';
        case 'uint16', c = 'uint16_t';
        case 'int32',  c = 'int32_t';
        case 'uint32', c = 'uint32_t';
        case 'single', c = 'float';
        case 'double', c = 'double';
    end
end

function fn = read_fn_name(t)
    switch t
        case 'int16',  fn = 'read_int16';
        case 'uint16', fn = 'read_uint16';
        case 'int32',  fn = 'read_int32';
        case 'uint32', fn = 'read_uint32';
        case 'single', fn = 'read_single';
        case 'double', fn = 'read_double64';
    end
end

function fn = write_fn_name(t)
    switch t
        case 'int16',  fn = 'write_int16';
        case 'uint16', fn = 'write_uint16';
        case 'int32',  fn = 'write_int32';
        case 'uint32', fn = 'write_uint32';
        case 'single', fn = 'write_single';
        case 'double', fn = 'write_double64';
    end
end
