function rendered = c2837x_block_render_pc_files(project)
%C2837X_BLOCK_RENDER_PC_FILES Render deterministic S4-02 PC runtime files.

c2837x_block_validate_project_structure(project);
templateRoot = fullfile(fileparts(mfilename('fullpath')), 'templates');
templates = struct( ...
    'socket_source', read_template(templateRoot, 'pc_socket.c.in'), ...
    'socket_header', read_template(templateRoot, 'pc_socket.h.in'), ...
    'protocol_source', read_template(templateRoot, 'protocol.c.in'), ...
    'protocol_header', read_template(templateRoot, 'protocol.h.in'));
prototype = struct('instance_index', 0, 'internal_name', '', ...
    'socket_source_bytes', zeros(1, 0, 'uint8'), ...
    'socket_header_bytes', zeros(1, 0, 'uint8'), ...
    'protocol_source_bytes', zeros(1, 0, 'uint8'), ...
    'protocol_header_bytes', zeros(1, 0, 'uint8'));
rendered = repmat(prototype, 1, numel(project.instances));
for index = 1:numel(project.instances)
    names = c2837x_block_build_instance_c_names( ...
        project.instances(index).internal_name);
    rendered(index) = struct('instance_index', index, ...
        'internal_name', names.internal_name, ...
        'socket_source_bytes', render(templates.socket_source, names), ...
        'socket_header_bytes', render(templates.socket_header, names), ...
        'protocol_source_bytes', render(templates.protocol_source, names), ...
        'protocol_header_bytes', render(templates.protocol_header, names));
end
end

function text = read_template(root, name)
text = fileread(fullfile(root, name));
text = strrep(text, [char(13) newline], newline);
text = strrep(text, char(13), newline);
while ~isempty(text) && text(end) == newline
    text(end) = [];
end
text = [text newline];
end

function bytes = render(template, names)
text = strrep(template, '@NAME@', names.internal_name);
text = strrep(text, '@MACRO@', names.macro_prefix);
text = strrep(text, '@TYPED@', names.typed_prefix);
bytes = reshape(uint8(unicode2native(text, 'UTF-8')), 1, []);
end
