function layout = c2837x_block_build_dsp_wire_layout(project)
%C2837X_BLOCK_BUILD_DSP_WIRE_LAYOUT Build deterministic DSP wire layouts.

c2837x_block_validate_project_structure(project);
fieldPrototype = struct('name', '', 'type', '', 'dim', 0, ...
    'element_octets', 0, 'offset_octets', 0, 'offset_words', 0);
instancePrototype = struct('instance_index', 0, 'internal_name', '', ...
    'input_fields', repmat(fieldPrototype, 1, 0), ...
    'output_fields', repmat(fieldPrototype, 1, 0), ...
    'input_data_octets', 0, 'output_data_octets', 0, ...
    'input_payload_octets', 0, 'output_payload_octets', 0, ...
    'max_payload_octets', 0, 'rx_frame_octets', 0, ...
    'tx_frame_octets', 0, 'rx_frame_words', 0, ...
    'tx_frame_words', 0, 'protocol_buffer_words', 0);
instances = repmat(instancePrototype, 1, numel(project.instances));
for index = 1:numel(project.instances)
    [~, ~, metrics] = c2837x_block_build_interface_hash(project, index);
    rxOctets = 4 + max(6, metrics.input_payload_octets);
    txOctets = 4 + max(2, metrics.output_payload_octets);
    instances(index) = struct('instance_index', double(index), ...
        'internal_name', char(project.instances(index).internal_name), ...
        'input_fields', fields(project.instances(index).inputs), ...
        'output_fields', fields(project.instances(index).outputs), ...
        'input_data_octets', metrics.input_data_octets, ...
        'output_data_octets', metrics.output_data_octets, ...
        'input_payload_octets', metrics.input_payload_octets, ...
        'output_payload_octets', metrics.output_payload_octets, ...
        'max_payload_octets', metrics.max_payload_octets, ...
        'rx_frame_octets', rxOctets, 'tx_frame_octets', txOctets, ...
        'rx_frame_words', rxOctets / 2, 'tx_frame_words', txOctets / 2, ...
        'protocol_buffer_words', (rxOctets + txOctets) / 2);
end
layout = struct('schema_version', uint16(1), 'instances', instances, ...
    'project_protocol_buffer_words', sum([instances.protocol_buffer_words]));
end

function values = fields(variables)
prototype = struct('name', '', 'type', '', 'dim', 0, ...
    'element_octets', 0, 'offset_octets', 0, 'offset_words', 0);
values = repmat(prototype, 1, numel(variables));
offset = 0;
for index = 1:numel(variables)
    type = char(variables(index).type);
    octets = type_octets(type);
    values(index) = struct('name', char(variables(index).name), ...
        'type', type, 'dim', double(variables(index).dim), ...
        'element_octets', octets, 'offset_octets', offset, ...
        'offset_words', offset / 2);
    offset = offset + octets * double(variables(index).dim);
end
end

function value = type_octets(type)
switch type
    case {'int16', 'uint16'}
        value = 2;
    case {'int32', 'uint32', 'single'}
        value = 4;
    case 'double'
        value = 8;
    otherwise
        error('C2837xBlock:DspWire:UnsupportedType', ...
            'Unsupported wire type "%s".', type);
end
end
