function result = c2837x_block_build_transport_summary(instance)
%C2837X_BLOCK_BUILD_TRANSPORT_SUMMARY Format persisted transport settings.

switch char(instance.iodevice.type)
    case 'w5300_tcp'
        settings = instance.iodevice.settings;
        result = struct( ...
            'type_label', 'W5300 TCP', ...
            'resource', sprintf('Socket %u', settings.socket_number), ...
            'link', sprintf('TCP %u', settings.tcp_port), ...
            'summary', sprintf('Socket %u / TCP %u', ...
            settings.socket_number, settings.tcp_port));
    case 'sci'
        settings = instance.iodevice.settings;
        resource = settings.module;
        if isempty(resource)
            resource = 'Not Selected';
        end
        link = sprintf('%u baud', settings.baud);
        result = struct( ...
            'type_label', 'SCI', ...
            'resource', resource, ...
            'link', link, ...
            'summary', sprintf('%s / %s', resource, link));
    otherwise
        error('C2837xBlock:App:UnsupportedIoDevice', ...
            'Unsupported IoDevice type %s.', char(instance.iodevice.type));
end
end
