function rendered = c2837x_block_render_dsp_instance_io_files(project)
%C2837X_BLOCK_RENDER_DSP_INSTANCE_IO_FILES Render instance wire bindings.

c2837x_block_validate_project_structure(project);
layout = c2837x_block_build_dsp_wire_layout(project);
prototype = struct('instance_index', 0, 'internal_name', '', ...
    'io_source_bytes', zeros(1, 0, 'uint8'));
rendered = repmat(prototype, 1, numel(project.instances));
for index = 1:numel(project.instances)
    names = c2837x_block_build_instance_c_names( ...
        project.instances(index).internal_name);
    definition = resolve_definition(project.instances(index).iodevice.type);
    support = validated_support(definition, project, index);
    rendered(index) = struct('instance_index', double(index), ...
        'internal_name', names.internal_name, ...
        'io_source_bytes', text_bytes(source_text(names, ...
        layout.instances(index), support)));
end
end

function text = source_text(names, layout, support)
name = names.internal_name;
macro = names.macro_prefix;
typed = names.typed_prefix;
includes = sprintf('#include "%s"\n', support.source_includes{:});
text = sprintf([ ...
    '/*\n * AUTO-GENERATED FILE\n * Manual changes will be overwritten.\n */\n\n' ...
    '#define C2837X_BLOCK_%s_USE_USER_CONFIG\n#include "%s_config.h"\n\n' ...
    '#include "%s_algorithm.h"\n#include <stdint.h>\n#include <limits.h>\n' ...
    '#include <float.h>\n%s\n%s\n%s\n' ...
    'Uint16 c2837x_block_%s_rx_frame_words[%s_RX_FRAME_WORDS];\n\n' ...
    'Uint16 c2837x_block_%s_tx_frame_words[%s_TX_FRAME_WORDS];\n\n' ...
    '%s_InputData c2837x_block_%s_input_object;\n\n' ...
    '%s_OutputData c2837x_block_%s_output_object;\n\n%s\n' ...
    'void c2837x_block_%s_decode_input(\n    void *input_object,\n' ...
    '    const Uint16 *user_data_words)\n{\n' ...
    '    %s_InputData *input = (%s_InputData *)input_object;\n\n' ...
    '%s\n}\n\n' ...
    'void c2837x_block_%s_encode_output(\n' ...
    '    const void *output_object,\n    Uint16 *user_data_words)\n{\n' ...
    '    const %s_OutputData *output = (const %s_OutputData *)output_object;\n\n' ...
    '%s\n}\n'], ...
    macro, name, name, includes, assertions(macro), helpers(layout), ...
    name, macro, name, macro, typed, name, typed, name, ...
    support.source_definitions, name, typed, typed, ...
    decode_lines(layout.input_fields), name, typed, typed, ...
    encode_lines(layout.output_fields));
end

function text = assertions(macro)
text = sprintf([ ...
    '%s_STATIC_ASSERT(sizeof(int16_t) * CHAR_BIT == 16, int16_width);\n' ...
    '%s_STATIC_ASSERT(sizeof(uint16_t) * CHAR_BIT == 16, uint16_width);\n' ...
    '%s_STATIC_ASSERT(sizeof(int32_t) * CHAR_BIT == 32, int32_width);\n' ...
    '%s_STATIC_ASSERT(sizeof(uint32_t) * CHAR_BIT == 32, uint32_width);\n' ...
    '%s_STATIC_ASSERT(sizeof(uint64_t) * CHAR_BIT == 64, uint64_width);\n' ...
    '%s_STATIC_ASSERT(sizeof(float) * CHAR_BIT == 32, float_width);\n' ...
    '%s_STATIC_ASSERT(sizeof(long double) * CHAR_BIT == 64, long_double_width);\n' ...
    '%s_STATIC_ASSERT(FLT_RADIX == 2, float_radix);\n' ...
    '%s_STATIC_ASSERT(FLT_MANT_DIG == 24, float_mantissa);\n' ...
    '%s_STATIC_ASSERT(FLT_MAX_EXP == 128, float_exponent);\n' ...
    '%s_STATIC_ASSERT(LDBL_MANT_DIG == 53, long_double_mantissa);\n' ...
    '%s_STATIC_ASSERT(LDBL_MAX_EXP == 1024, long_double_exponent);\n' ...
    '%s_STATIC_ASSERT((%s_INPUT_DATA_OCTETS %% 2u) == 0u, input_data_even);\n' ...
    '%s_STATIC_ASSERT((%s_OUTPUT_DATA_OCTETS %% 2u) == 0u, output_data_even);\n' ...
    '%s_STATIC_ASSERT((%s_INPUT_PAYLOAD_OCTETS %% 2u) == 0u, input_payload_even);\n' ...
    '%s_STATIC_ASSERT((%s_OUTPUT_PAYLOAD_OCTETS %% 2u) == 0u, output_payload_even);\n' ...
    '%s_STATIC_ASSERT(((Uint32)%s_RX_FRAME_WORDS * (Uint32)2u) == (Uint32)%s_RX_FRAME_OCTETS, rx_frame_word_capacity);\n' ...
    '%s_STATIC_ASSERT(((Uint32)%s_TX_FRAME_WORDS * (Uint32)2u) == (Uint32)%s_TX_FRAME_OCTETS, tx_frame_word_capacity);\n'], ...
    macro, macro, macro, macro, macro, macro, macro, macro, macro, macro, ...
    macro, macro, macro, macro, macro, macro, macro, macro, macro, macro, ...
    macro, macro, macro, macro, macro, macro);
end

function text = helpers(layout)
inputTypes = {layout.input_fields.type};
outputTypes = {layout.output_fields.type};
parts = {};
for type = {'int16', 'int32', 'single', 'double'}
    if any(strcmp(inputTypes, type{1}))
        parts{end + 1} = decode_helper(type{1}); %#ok<AGROW>
    end
    if any(strcmp(outputTypes, type{1}))
        parts{end + 1} = encode_helper(type{1}); %#ok<AGROW>
    end
end
text = strjoin(parts, newline);
end

function text = decode_helper(type)
types = struct('int16', {{'int16_t', 'uint16_t'}}, ...
    'int32', {{'int32_t', 'uint32_t'}}, 'single', {{'float', 'uint32_t'}}, ...
    'double', {{'long double', 'uint64_t'}});
pair = types.(type);
text = sprintf([ ...
    'static %s c2837x_block_decode_%s(%s bits)\n{\n' ...
    '    union { %s value; %s bits; } converted;\n' ...
    '    converted.bits = bits;\n    return converted.value;\n}\n'], ...
    pair{1}, type, pair{2}, pair{1}, pair{2});
end

function text = encode_helper(type)
types = struct('int16', {{'int16_t', 'uint16_t'}}, ...
    'int32', {{'int32_t', 'uint32_t'}}, 'single', {{'float', 'uint32_t'}}, ...
    'double', {{'long double', 'uint64_t'}});
pair = types.(type);
text = sprintf([ ...
    'static %s c2837x_block_encode_%s(%s value)\n{\n' ...
    '    union { %s value; %s bits; } converted;\n' ...
    '    converted.value = value;\n    return converted.bits;\n}\n'], ...
    pair{2}, type, pair{1}, pair{1}, pair{2});
end

function text = decode_lines(fields)
lines = {};
for field = fields
    words = field.element_octets / 2;
    for element = 1:field.dim
        offset = field.offset_words + (element - 1) * words;
        target = member('input', field.name, field.dim, element);
        lines{end + 1} = sprintf('    %s = %s;', target, ...
            decode_expression(field.type, offset)); %#ok<AGROW>
    end
end
text = strjoin(lines, newline);
end

function expression = decode_expression(type, offset)
word = sprintf('user_data_words[%uu]', offset);
bits32 = sprintf('((uint32_t)%s | ((uint32_t)user_data_words[%uu] << 16))', ...
    word, offset + 1);
bits64 = sprintf([ ...
    '((uint64_t)%s | ((uint64_t)user_data_words[%uu] << 16) | ' ...
    '((uint64_t)user_data_words[%uu] << 32) | ' ...
    '((uint64_t)user_data_words[%uu] << 48))'], ...
    word, offset + 1, offset + 2, offset + 3);
switch type
    case 'uint16'
        expression = ['(uint16_t)' word];
    case 'int16'
        expression = ['c2837x_block_decode_int16((uint16_t)' word ')'];
    case 'uint32'
        expression = bits32;
    case 'int32'
        expression = ['c2837x_block_decode_int32(' bits32 ')'];
    case 'single'
        expression = ['c2837x_block_decode_single(' bits32 ')'];
    case 'double'
        expression = ['c2837x_block_decode_double(' bits64 ')'];
end
end

function text = encode_lines(fields)
lines = {};
for field = fields
    words = field.element_octets / 2;
    for element = 1:field.dim
        offset = field.offset_words + (element - 1) * words;
        source = member('output', field.name, field.dim, element);
        expression = encode_expression(field.type, source);
        if words == 1
            lines{end + 1} = sprintf( ...
                '    user_data_words[%uu] = (Uint16)%s;', ...
                offset, expression); %#ok<AGROW>
        else
            lines{end + 1} = '    {'; %#ok<AGROW>
            lines{end + 1} = sprintf('        %s bits = %s;', ...
                encode_bits_type(field.type), expression); %#ok<AGROW>
            for word = 1:words
                lines{end + 1} = sprintf( ...
                    '        user_data_words[%uu] = (Uint16)((bits >> %u) & 0xffffu);', ...
                    offset + word - 1, 16 * (word - 1)); %#ok<AGROW>
            end
            lines{end + 1} = '    }'; %#ok<AGROW>
        end
    end
end
text = strjoin(lines, newline);
end

function type = encode_bits_type(fieldType)
switch fieldType
    case {'int32', 'uint32', 'single'}
        type = 'uint32_t';
    case 'double'
        type = 'uint64_t';
    otherwise
        error('C2837xBlock:IoDevice:InvalidMultiwordType', ...
            'Type "%s" cannot be encoded as multiple words.', fieldType);
end
end

function expression = encode_expression(type, source)
switch type
    case 'uint16'
        expression = ['(uint16_t)' source];
    case 'uint32'
        expression = ['(uint32_t)' source];
    otherwise
        expression = sprintf('c2837x_block_encode_%s(%s)', type, source);
end
end

function text = member(object, name, dim, element)
if dim == 1
    text = [object '->' name];
else
    text = sprintf('%s->%s[%u]', object, name, element - 1);
end
end

function definition = resolve_definition(type)
[definition, found] = c2837x_block_get_iodevice_definition(type);
if ~found
    error('C2837xBlock:IoDevice:Unsupported', ...
        'Cannot render unsupported IoDevice type "%s".', char(type));
end
end

function support = validated_support(definition, project, index)
support = definition.render_instance_io_support(project, index);
second = definition.render_instance_io_support(project, index);
valid = isstruct(support) && isscalar(support) && ...
    all(isfield(support, {'source_includes', 'source_definitions'})) && ...
    iscell(support.source_includes) && isrow(support.source_includes) && ...
    all(cellfun(@(value) ischar(value) && isrow(value) && ~isempty(value), ...
    support.source_includes)) && numel(unique(support.source_includes)) == ...
    numel(support.source_includes) && ischar(support.source_definitions) && ...
    isrow(support.source_definitions) && ~isempty(support.source_definitions) && ...
    isequal(support, second);
if ~valid
    error('C2837xBlock:IoDevice:InvalidInstanceIoSupport', ...
        'IoDevice definition "%s" returned invalid instance IO support.', ...
        definition.type);
end
end

function bytes = text_bytes(text)
text = strrep(text, [char(13) newline], newline);
text = strrep(text, char(13), newline);
while ~isempty(text) && text(end) == newline
    text(end) = [];
end
bytes = reshape(uint8(unicode2native([text newline], 'UTF-8')), 1, []);
end
