function c2837x_block_generate_pc_files(config, output_path)
%C2837X_BLOCK_GENERATE_PC_FILES  Generate PC-side configuration files.
%
%   c2837x_block_generate_pc_files(config, output_path)
%
%   Generates 2 files and copies 7 existing files under output_path:
%     Generated: c2837x_block_pc_config.h, c2837x_block_sfun_io.c
%     Copied:    c2837x_block_sfun.c, c2837x_block_sfun.h,
%                c2837x_block_pc_socket.c, c2837x_block_pc_socket.h,
%                c2837x_block_protocol.c, c2837x_block_protocol.h,
%                build_c2837x_block_sfun.m

    if ~isfolder(output_path), mkdir(output_path); end

    [~, config_hash] = c2837x_block_build_hash_string(config);

    % Generate configuration files
    write_file(fullfile(output_path, 'c2837x_block_pc_config.h'), ...
               gen_pc_config_h(config, config_hash));
    write_file(fullfile(output_path, 'c2837x_block_sfun_io.c'), ...
               gen_sfun_io_c(config));

    % Copy existing PC library files
    copy_pc_library_files(output_path);
end

%% ---- File writer ----
function write_file(filepath, content)
    fid = fopen(filepath, 'w');
    if fid < 0
        error('Failed to write %s', filepath);
    end
    % Ensure content ends with newline (avoids compiler warnings)
    if ~isempty(content) && content(end) ~= newline
        content = [content newline];
    end
    fprintf(fid, '%s', content);
    fclose(fid);
end

%% ---- c2837x_block_pc_config.h ----
function s = gen_pc_config_h(config, config_hash)
    L = {};
    L{end+1} = '#ifndef C2837X_BLOCK_PC_CONFIG_H';
    L{end+1} = '#define C2837X_BLOCK_PC_CONFIG_H';
    L{end+1} = '';
    L{end+1} = '/*';
    L{end+1} = ' * Auto-generated by C2837xBlock Configurator.';
    L{end+1} = ' * DO NOT EDIT MANUALLY.';
    L{end+1} = ' *';
    L{end+1} = ' * PC/Simulink C S-Function side configuration.';
    L{end+1} = ' *';
    L{end+1} = ' * This file defines compile-time constants for the S-Function.';
    L{end+1} = ' * Port I/O is handled by c2837x_block_sfun_io.c (also auto-generated).';
    L{end+1} = ' */';
    L{end+1} = '';
    L{end+1} = '#include <stdint.h>';
    L{end+1} = '';

    % Protocol
    L{end+1} = '/* ---- Protocol configuration ---- */';
    L{end+1} = sprintf('#define C2837X_BLOCK_PROTOCOL_VERSION  0x%04Xu', config.protocol_version);
    L{end+1} = sprintf('#define C2837X_BLOCK_CONFIG_HASH       0x%08Xu', config_hash);
    L{end+1} = sprintf('#define C2837X_BLOCK_SAMPLE_TIME_SEC   %.17g', config.sample_time_sec);
    L{end+1} = '';

    % Network (PC side uses string IP)
    L{end+1} = '/* ---- Network configuration ---- */';
    L{end+1} = sprintf('#define C2837X_BLOCK_IP_ADDR           "%s"', config.dsp_ip);
    L{end+1} = sprintf('#define C2837X_BLOCK_TCP_PORT          %du', config.tcp_port);
    L{end+1} = '';

    % Max payload
    L{end+1} = sprintf('#define C2837X_BLOCK_MAX_PAYLOAD_SIZE_BYTES       %du', config.max_payload_size_bytes);
    L{end+1} = '#define C2837X_BLOCK_MAX_FRAME_SIZE_BYTES         (4u + C2837X_BLOCK_MAX_PAYLOAD_SIZE_BYTES)';
    L{end+1} = '';

    % PC timeouts
    L{end+1} = '/* ---- PC-side timeouts ---- */';
    L{end+1} = '#define C2837X_BLOCK_PC_CONNECT_TIMEOUT_MS        5000u';
    L{end+1} = '#define C2837X_BLOCK_PC_STEP_TIMEOUT_MS           5000u';
    L{end+1} = '#define C2837X_BLOCK_PC_TERMINATE_TIMEOUT_MS      1000u';
    L{end+1} = '';

    % Data counts
    L{end+1} = '/* ---- Data counts ---- */';
    L{end+1} = sprintf('#define C2837X_BLOCK_INPUT_COUNT       %du', numel(config.inputs));
    L{end+1} = sprintf('#define C2837X_BLOCK_OUTPUT_COUNT      %du', numel(config.outputs));
    L{end+1} = '';

    % Sizes
    in_data_bytes = compute_data_bytes(config.inputs);
    out_data_bytes = compute_data_bytes(config.outputs);
    L{end+1} = '/* ---- Wire byte sizes ---- */';
    L{end+1} = sprintf('#define C2837X_BLOCK_INPUT_DATA_SIZE_BYTES      %du', in_data_bytes);
    L{end+1} = sprintf('#define C2837X_BLOCK_OUTPUT_DATA_SIZE_BYTES     %du', out_data_bytes);
    L{end+1} = '#define C2837X_BLOCK_INPUT_PAYLOAD_SIZE_BYTES   (4u + C2837X_BLOCK_INPUT_DATA_SIZE_BYTES)';
    L{end+1} = '#define C2837X_BLOCK_OUTPUT_PAYLOAD_SIZE_BYTES  (4u + C2837X_BLOCK_OUTPUT_DATA_SIZE_BYTES)';
    L{end+1} = '';

    % Port configuration macros
    L{end+1} = '/* ---- Port configuration ----';
    L{end+1} = ' * Each port has: WIDTH (elements), SIMTYPE (Simulink type ID), BYTES_PER_ELEM';
    L{end+1} = ' * Simulink type IDs: SS_DOUBLE=0, SS_SINGLE=1, SS_INT8=2, SS_UINT8=3,';
    L{end+1} = ' *                    SS_INT16=4, SS_UINT16=5, SS_INT32=6, SS_UINT32=7';
    L{end+1} = ' */';
    L{end+1} = '';

    % Input port configs
    for i = 1:numel(config.inputs)
        v = config.inputs(i);
        idx = i - 1;  % 0-based index
        L{end+1} = sprintf('#define C2837X_BLOCK_INPUT%d_WIDTH           %d', idx, v.dim);
        L{end+1} = sprintf('#define C2837X_BLOCK_INPUT%d_SIMTYPE         %s', idx, type_to_simtype(v.type));
        L{end+1} = sprintf('#define C2837X_BLOCK_INPUT%d_BYTES_PER_ELEM  %d', idx, type_wire_bytes(v.type));
    end
    L{end+1} = '';

    % Output port configs
    for i = 1:numel(config.outputs)
        v = config.outputs(i);
        idx = i - 1;  % 0-based index
        L{end+1} = sprintf('#define C2837X_BLOCK_OUTPUT%d_WIDTH          %d', idx, v.dim);
        L{end+1} = sprintf('#define C2837X_BLOCK_OUTPUT%d_SIMTYPE        %s', idx, type_to_simtype(v.type));
        L{end+1} = sprintf('#define C2837X_BLOCK_OUTPUT%d_BYTES_PER_ELEM %d', idx, type_wire_bytes(v.type));
    end
    L{end+1} = '';

    % Port I/O function declarations (new direct conversion)
    L{end+1} = '/* ---- Port I/O functions (implemented in c2837x_block_sfun_io.c) ---- */';
    L{end+1} = '/* Note: SimStruct is defined in simstruc.h, included by c2837x_block_sfun.c */';
    L{end+1} = 'struct SimStruct_tag;';
    L{end+1} = 'typedef struct SimStruct_tag SimStruct;';
    L{end+1} = '';
    L{end+1} = '/*';
    L{end+1} = ' * Pack input ports directly to payload buffer.';
    L{end+1} = ' * Payload format: [step_index: 4 bytes] [input data...]';
    L{end+1} = ' * Total size: C2837X_BLOCK_INPUT_PAYLOAD_SIZE_BYTES';
    L{end+1} = ' */';
    L{end+1} = 'void c2837x_block_pack_input_from_ports(SimStruct *S,';
    L{end+1} = '                                        uint8_t* payload,';
    L{end+1} = '                                        uint32_t step_index);';
    L{end+1} = '';
    L{end+1} = '/*';
    L{end+1} = ' * Unpack output payload buffer directly to output ports.';
    L{end+1} = ' * Payload format: [step_index: 4 bytes] [output data...]';
    L{end+1} = ' * Total size: C2837X_BLOCK_OUTPUT_PAYLOAD_SIZE_BYTES';
    L{end+1} = ' */';
    L{end+1} = 'void c2837x_block_unpack_output_to_ports(SimStruct *S,';
    L{end+1} = '                                         const uint8_t* payload,';
    L{end+1} = '                                         uint32_t* step_index);';
    L{end+1} = '';

    L{end+1} = '#endif /* C2837X_BLOCK_PC_CONFIG_H */';
    s = strjoin(L, '\n');
end

%% ---- c2837x_block_sfun_io.c (direct port-to-payload conversion) ----
function s = gen_sfun_io_c(config)
    L = {};
    L{end+1} = '/*';
    L{end+1} = ' * Auto-generated by C2837xBlock Configurator.';
    L{end+1} = ' * DO NOT EDIT MANUALLY.';
    L{end+1} = ' *';
    L{end+1} = ' * Port I/O helpers for C S-Function.';
    L{end+1} = ' *';
    L{end+1} = ' * These functions directly pack/unpack between Simulink ports and';
    L{end+1} = ' * wire-format payload buffers, eliminating intermediate data structures.';
    L{end+1} = ' *';
    L{end+1} = ' * Payload format (little-endian):';
    L{end+1} = ' *   [step_index: 4 bytes] [input0 data] [input1 data] ...';
    L{end+1} = ' */';
    L{end+1} = '';
    L{end+1} = '#include "c2837x_block_pc_config.h"';
    L{end+1} = '#include <string.h>';
    L{end+1} = '';
    L{end+1} = '/* SimStruct and port access macros are defined in simstruc.h */';
    L{end+1} = '#include "simstruc.h"';
    L{end+1} = '';

    % Generate write helpers
    all_types = unique([{config.inputs.type}, {config.outputs.type}]);
    need_int16 = any(strcmp(all_types, 'int16'));
    need_uint16 = any(strcmp(all_types, 'uint16'));
    need_int32 = any(strcmp(all_types, 'int32'));
    need_uint32 = any(strcmp(all_types, 'uint32'));
    need_single = any(strcmp(all_types, 'single'));

    L{end+1} = '/* ---- Little-endian serialization helpers ---- */';
    L{end+1} = '';

    % Always needed: write_le16, write_le32, read_le16, read_le32
    L = [L, gen_le_helper('write_le16', 'uint16_t', true, true)];
    L = [L, gen_le_helper('write_le32', 'uint32_t', true, true)];
    L = [L, gen_le_helper('read_le16', 'uint16_t', false, true)];
    L = [L, gen_le_helper('read_le32', 'uint32_t', false, true)];
    L{end+1} = '';

    % Additional helpers for other types
    if need_int16
        L{end+1} = 'static inline void write_int16_le(uint8_t* buf, int16_t val) { write_le16(buf, (uint16_t)val); }';
        L{end+1} = 'static inline int16_t read_int16_le(const uint8_t* buf) { return (int16_t)read_le16(buf); }';
    end
    if need_int32
        L{end+1} = 'static inline void write_int32_le(uint8_t* buf, int32_t val) { write_le32(buf, (uint32_t)val); }';
        L{end+1} = 'static inline int32_t read_int32_le(const uint8_t* buf) { return (int32_t)read_le32(buf); }';
    end
    if need_single
        L{end+1} = 'static inline void write_single_le(uint8_t* buf, float val) { uint32_t raw; memcpy(&raw, &val, sizeof(raw)); write_le32(buf, raw); }';
        L{end+1} = 'static inline float read_single_le(const uint8_t* buf) { uint32_t raw = read_le32(buf); float val; memcpy(&val, &raw, sizeof(val)); return val; }';
    end
    L{end+1} = '';

    % Generate pack_input_from_ports
    L{end+1} = '/* ---- Pack input ports directly to payload ---- */';
    L{end+1} = 'void c2837x_block_pack_input_from_ports(SimStruct *S,';
    L{end+1} = '                                        uint8_t* payload,';
    L{end+1} = '                                        uint32_t step_index)';
    L{end+1} = '{';
    L{end+1} = '    uint32_t offset = 0;';
    L{end+1} = '';
    L{end+1} = '    /* Write step_index (4 bytes, little-endian) */';
    L{end+1} = '    write_le32(&payload[offset], step_index);';
    L{end+1} = '    offset += 4;';
    L{end+1} = '';

    % For each input variable, generate code to read from port and write to payload
    port_idx = 0;
    for i = 1:numel(config.inputs)
        v = config.inputs(i);
        c_type = type_to_c_type(v.type);
        write_fn = get_write_le_fn(v.type);

        if v.dim == 1
            % Scalar
            L{end+1} = sprintf('    /* %s: %s, port %d */', v.name, v.type, port_idx);
            L{end+1} = sprintf('    {');
            L{end+1} = sprintf('        const %s *u = (const %s *)ssGetInputPortSignal(S, %d);', ...
                               c_type, c_type, port_idx);
            L{end+1} = sprintf('        %s(&payload[offset], u[0]);', write_fn);
            L{end+1} = sprintf('        offset += %d;', type_wire_bytes(v.type));
            L{end+1} = sprintf('    }');
            port_idx = port_idx + 1;
        else
            % Array
            L{end+1} = sprintf('    /* %s: %s[%d], port %d */', v.name, v.type, v.dim, port_idx);
            L{end+1} = sprintf('    {');
            L{end+1} = sprintf('        const %s *u = (const %s *)ssGetInputPortSignal(S, %d);', ...
                               c_type, c_type, port_idx);
            L{end+1} = sprintf('        int i;');
            L{end+1} = sprintf('        for (i = 0; i < %d; i++) {', v.dim);
            L{end+1} = sprintf('            %s(&payload[offset], u[i]);', write_fn);
            L{end+1} = sprintf('            offset += %d;', type_wire_bytes(v.type));
            L{end+1} = sprintf('        }');
            L{end+1} = sprintf('    }');
            port_idx = port_idx + 1;
        end
        L{end+1} = '';
    end

    L{end+1} = '}';
    L{end+1} = '';

    % Generate unpack_output_to_ports
    L{end+1} = '/* ---- Unpack output payload directly to ports ---- */';
    L{end+1} = 'void c2837x_block_unpack_output_to_ports(SimStruct *S,';
    L{end+1} = '                                         const uint8_t* payload,';
    L{end+1} = '                                         uint32_t* step_index)';
    L{end+1} = '{';
    L{end+1} = '    uint32_t offset = 0;';
    L{end+1} = '';
    L{end+1} = '    /* Read step_index (4 bytes, little-endian) */';
    L{end+1} = '    *step_index = read_le32(&payload[offset]);';
    L{end+1} = '    offset += 4;';
    L{end+1} = '';

    port_idx = 0;
    for i = 1:numel(config.outputs)
        v = config.outputs(i);
        c_type = type_to_c_type(v.type);
        read_fn = get_read_le_fn(v.type);

        if v.dim == 1
            % Scalar
            L{end+1} = sprintf('    /* %s: %s, port %d */', v.name, v.type, port_idx);
            L{end+1} = sprintf('    {');
            L{end+1} = sprintf('        %s *y = (%s *)ssGetOutputPortSignal(S, %d);', ...
                               c_type, c_type, port_idx);
            L{end+1} = sprintf('        y[0] = (%s)%s(&payload[offset]);', c_type, read_fn);
            L{end+1} = sprintf('        offset += %d;', type_wire_bytes(v.type));
            L{end+1} = sprintf('    }');
            port_idx = port_idx + 1;
        else
            % Array
            L{end+1} = sprintf('    /* %s: %s[%d], port %d */', v.name, v.type, v.dim, port_idx);
            L{end+1} = sprintf('    {');
            L{end+1} = sprintf('        %s *y = (%s *)ssGetOutputPortSignal(S, %d);', ...
                               c_type, c_type, port_idx);
            L{end+1} = sprintf('        int i;');
            L{end+1} = sprintf('        for (i = 0; i < %d; i++) {', v.dim);
            L{end+1} = sprintf('            y[i] = (%s)%s(&payload[offset]);', c_type, read_fn);
            L{end+1} = sprintf('            offset += %d;', type_wire_bytes(v.type));
            L{end+1} = sprintf('        }');
            L{end+1} = sprintf('    }');
            port_idx = port_idx + 1;
        end
        L{end+1} = '';
    end

    L{end+1} = '}';
    L{end+1} = '';

    s = strjoin(L, '\n');
end

%% ---- Little-endian helper generators ----
function L = gen_le_helper(fn_name, type, is_write, active)
    L = {};
    if ~active
        return;
    end

    if is_write
        L{end+1} = sprintf('static inline void %s(uint8_t* buf, %s val)', fn_name, type);
        L{end+1} = '{';
        if strcmp(type, 'uint16_t')
            L{end+1} = '    buf[0] = (uint8_t)(val & 0xFFu);';
            L{end+1} = '    buf[1] = (uint8_t)((val >> 8) & 0xFFu);';
        else % uint32_t
            L{end+1} = '    buf[0] = (uint8_t)(val & 0xFFu);';
            L{end+1} = '    buf[1] = (uint8_t)((val >> 8) & 0xFFu);';
            L{end+1} = '    buf[2] = (uint8_t)((val >> 16) & 0xFFu);';
            L{end+1} = '    buf[3] = (uint8_t)((val >> 24) & 0xFFu);';
        end
        L{end+1} = '}';
    else
        L{end+1} = sprintf('static inline %s %s(const uint8_t* buf)', type, fn_name);
        L{end+1} = '{';
        if strcmp(type, 'uint16_t')
            L{end+1} = '    return (uint16_t)((uint16_t)buf[0] | ((uint16_t)buf[1] << 8));';
        else % uint32_t
            L{end+1} = '    return ((uint32_t)buf[0]) |';
            L{end+1} = '           ((uint32_t)buf[1] << 8) |';
            L{end+1} = '           ((uint32_t)buf[2] << 16) |';
            L{end+1} = '           ((uint32_t)buf[3] << 24);';
        end
        L{end+1} = '}';
    end
    L{end+1} = '';
end

%% ---- Helper functions ----
function bytes = compute_data_bytes(vars)
    bytes = 0;
    for i = 1:numel(vars)
        bytes = bytes + type_wire_bytes(vars(i).type) * vars(i).dim;
    end
end

function b = type_wire_bytes(t)
    switch t
        case {'int16','uint16'}, b = 2;
        case {'int32','uint32','single'}, b = 4;
        case 'double', b = 8;
    end
end

function c = type_to_c_type(t)
    switch t
        case 'int16',  c = 'int16_t';
        case 'uint16', c = 'uint16_t';
        case 'int32',  c = 'int32_t';
        case 'uint32', c = 'uint32_t';
        case 'single', c = 'float';
        case 'double', c = 'double';
    end
end

function s = type_to_simtype(t)
% Convert type string to Simulink type ID macro
    switch t
        case 'double', s = 'SS_DOUBLE';   % 0
        case 'single', s = 'SS_SINGLE';   % 1
        case 'int8',   s = 'SS_INT8';     % 2
        case 'uint8',  s = 'SS_UINT8';    % 3
        case 'int16',  s = 'SS_INT16';    % 4
        case 'uint16', s = 'SS_UINT16';   % 5
        case 'int32',  s = 'SS_INT32';    % 6
        case 'uint32', s = 'SS_UINT32';   % 7
        otherwise,     error('Unknown type: %s', t);
    end
end

function fn = get_write_le_fn(t)
% Get write function name for little-endian serialization
    switch t
        case {'int16', 'uint16'},  fn = 'write_le16';
        case {'int32', 'uint32'},  fn = 'write_le32';
        case 'single',             fn = 'write_single_le';
        case 'double',             fn = 'write_double64_le';
        otherwise,                 error('Unknown type: %s', t);
    end
end

function fn = get_read_le_fn(t)
% Get read function name for little-endian deserialization
    switch t
        case {'int16', 'uint16'},  fn = 'read_le16';
        case {'int32', 'uint32'},  fn = 'read_le32';
        case 'single',             fn = 'read_single_le';
        case 'double',             fn = 'read_double64_le';
        otherwise,                 error('Unknown type: %s', t);
    end
end

function copy_pc_library_files(output_dir)
%COPY_PC_LIBRARY_FILES  Copy existing PC library files to output directory.
%
%   copy_pc_library_files(output_dir)
%
%   Copies S-Function source files from simulink/.

    % Get project root (parent of app/ folder)
    app_dir = fileparts(mfilename('fullpath'));
    project_root = fileparts(app_dir);
    simulink_dir = fullfile(project_root, 'simulink');

    % Files to copy
    files_to_copy = {
        'c2837x_block_sfun.c'
        'c2837x_block_sfun.h'
        'c2837x_block_pc_socket.c'
        'c2837x_block_pc_socket.h'
        'c2837x_block_protocol.c'
        'c2837x_block_protocol.h'
        'build_c2837x_block_sfun.m'
    };

    % Copy files
    for i = 1:numel(files_to_copy)
        src = fullfile(simulink_dir, files_to_copy{i});
        dst = fullfile(output_dir, files_to_copy{i});
        if ~isfile(src)
            error('PC library file not found: %s', src);
        end
        copyfile(src, dst);
    end
end
