/*
 * C2837xBlock C MEX S-Function
 * PC-side Simulink block for DSP-in-the-loop communication.
 *
 * This file implements the Simulink S-Function callbacks for:
 * - Connecting to DSP via TCP/IP
 * - Sending input data each simulation step
 * - Receiving output data from DSP
 * - Managing connection lifecycle
 *
 * IMPORTANT: Port configuration is determined at compile time by
 * c2837x_block_pc_config.h (generated by the MATLAB App).
 * When configuration changes:
 *   1. Re-run the App to generate new config files
 *   2. Rebuild this MEX file using build_c2837x_block_sfun()
 */

#define S_FUNCTION_NAME  c2837x_block_sfun
#define S_FUNCTION_LEVEL 2

/* ---- Simulink includes ---- */
#include "simstruc.h"

/* ---- Project includes ---- */
#include "c2837x_block_sfun.h"
#include "c2837x_block_protocol.h"
#include "c2837x_block_pc_config.h"

/* ---- Compile-time configuration validation ---- */
#if !defined(C2837X_BLOCK_INPUT_COUNT) || (C2837X_BLOCK_INPUT_COUNT < 1)
#error "C2837X_BLOCK_INPUT_COUNT must be defined and >= 1 in c2837x_block_pc_config.h"
#endif

#if !defined(C2837X_BLOCK_OUTPUT_COUNT) || (C2837X_BLOCK_OUTPUT_COUNT < 1)
#error "C2837X_BLOCK_OUTPUT_COUNT must be defined and >= 1 in c2837x_block_pc_config.h"
#endif

/* ---- Single instance counter ---- */
static int g_c2837x_block_instance_count = 0;

/* ---- Helper: context management ---- */

C2837xBlockSfunContext* c2837x_block_sfun_create_context(void)
{
    C2837xBlockSfunContext* ctx;

    /* Initialize socket library if needed */
    if (c2837x_socket_init() != 0) {
        return NULL;
    }

    /* Allocate context */
    ctx = (C2837xBlockSfunContext*)calloc(1, sizeof(C2837xBlockSfunContext));
    if (ctx == NULL) {
        return NULL;
    }

    /* Initialize fields */
    ctx->sock.fd = 0; /* Will be set by socket_connect */
    ctx->step_index = 0;
    ctx->connected = 0;
    ctx->sim_started = 0;
    ctx->socket_lib_initialized = 1;

    /* Set timeouts from config */
    ctx->connect_timeout_ms = C2837X_BLOCK_PC_CONNECT_TIMEOUT_MS;
    ctx->step_timeout_ms = C2837X_BLOCK_PC_STEP_TIMEOUT_MS;
    ctx->terminate_timeout_ms = C2837X_BLOCK_PC_TERMINATE_TIMEOUT_MS;

    return ctx;
}

void c2837x_block_sfun_destroy_context(C2837xBlockSfunContext* ctx)
{
    if (ctx == NULL) {
        return;
    }

    /* Close socket if still connected */
    if (ctx->connected) {
        c2837x_socket_close(&ctx->sock);
        ctx->connected = 0;
    }

    /* Free context */
    free(ctx);

    /* Cleanup socket library */
    c2837x_socket_cleanup();
}

int c2837x_block_sfun_connect(C2837xBlockSfunContext* ctx)
{
    if (ctx == NULL) {
        return -1;
    }

    /* Connect to DSP */
    if (c2837x_socket_connect(&ctx->sock,
                              C2837X_BLOCK_IP_ADDR,
                              C2837X_BLOCK_TCP_PORT,
                              ctx->connect_timeout_ms) != 0) {
        return -1;
    }
    ctx->connected = 1;

    /* Send SIM_START */
    if (c2837x_protocol_send_sim_start(&ctx->sock,
                                       C2837X_BLOCK_PROTOCOL_VERSION,
                                       C2837X_BLOCK_CONFIG_HASH,
                                       ctx->step_timeout_ms) != 0) {
        c2837x_socket_close(&ctx->sock);
        ctx->connected = 0;
        return -1;
    }

    /* Wait for RESPONSE(0) */
    if (c2837x_protocol_wait_response(&ctx->sock,
                                      C2837X_BLOCK_ERR_NONE,
                                      ctx->step_timeout_ms) != 0) {
        c2837x_socket_close(&ctx->sock);
        ctx->connected = 0;
        return -1;
    }

    ctx->sim_started = 1;
    ctx->step_index = 0;
    return 0;
}

int c2837x_block_sfun_step(C2837xBlockSfunContext* ctx, void *S)
{
    uint16_t recv_length;
    uint32_t recv_step_index;
    uint16_t dsp_error = C2837X_BLOCK_ERR_NONE;

    if (ctx == NULL || S == NULL) {
        return -1;
    }

    if (!ctx->connected || !ctx->sim_started) {
        return -1;
    }

    /* Pack input ports directly to TX payload */
    /* Note: step_index naturally wraps to 0 after UINT32_MAX, which is correct
     * for long-running simulations. DSP side must accept wrapping step_index. */
    c2837x_block_pack_input_from_ports((SimStruct*)S, ctx->tx_buf, ctx->step_index);

    /* Send INPUT_DATA */
    if (c2837x_protocol_send_input_data(&ctx->sock,
                                        ctx->tx_buf,
                                        C2837X_BLOCK_INPUT_PAYLOAD_SIZE_BYTES,
                                        ctx->step_timeout_ms) != 0) {
        return -1;
    }

    /* Wait for OUTPUT_DATA */
    if (c2837x_protocol_wait_output_data(&ctx->sock,
                                         ctx->rx_buf,
                                         &recv_length,
                                         sizeof(ctx->rx_buf),
                                         ctx->step_timeout_ms,
                                         &dsp_error) != 0) {
        /* Store DSP error code for reporting */
        ctx->last_dsp_error = dsp_error;
        return -1;
    }

    /* Validate output length */
    if (recv_length != C2837X_BLOCK_OUTPUT_PAYLOAD_SIZE_BYTES) {
        return -1;
    }

    /* Unpack RX payload directly to output ports */
    c2837x_block_unpack_output_to_ports((SimStruct*)S, ctx->rx_buf, &recv_step_index);

    /* Validate step_index */
    if (recv_step_index != ctx->step_index) {
        return -1;
    }

    /* Advance step index */
    ctx->step_index++;

    return 0;
}

void c2837x_block_sfun_disconnect(C2837xBlockSfunContext* ctx, int graceful)
{
    if (ctx == NULL) {
        return;
    }

    if (ctx->connected) {
        if (graceful && ctx->sim_started) {
            /* Try to send SIM_STOP, ignore errors */
            c2837x_protocol_send_sim_stop(&ctx->sock, ctx->terminate_timeout_ms);
        }

        c2837x_socket_close(&ctx->sock);
        ctx->connected = 0;
        ctx->sim_started = 0;
    }
}

/* ==== Simulink S-Function Callbacks ==== */

/* Function: mdlInitializeSizes ===============================================
 * Abstract:
 *    Setup port sizes, data types, and work vectors.
 *    Port configuration comes from c2837x_block_pc_config.h macros.
 */
static void mdlInitializeSizes(SimStruct *S)
{
    ssSetNumSFcnParams(S, 0);
    if (ssGetNumSFcnParams(S) != ssGetSFcnParamsCount(S)) {
        return; /* Parameter mismatch will be reported by Simulink */
    }

    /* Setup ports using generated functions from c2837x_block_sfun_io.c */
    c2837x_block_setup_input_ports(S);
    c2837x_block_setup_output_ports(S);

    /* Sample time */
    ssSetNumSampleTimes(S, 1);

    /* PWork vector for context pointer */
    ssSetNumPWork(S, 1);

    /* Options */
    ssSetOptions(S, SS_OPTION_EXCEPTION_FREE_CODE);
}

/* Function: mdlInitializeSampleTimes =========================================
 * Abstract:
 *    Set sample time to fixed discrete.
 *    Reject variable-step solver.
 */
static void mdlInitializeSampleTimes(SimStruct *S)
{
    /* Check for fixed-step solver */
    if (ssGetSolverMode(S) != SOLVER_MODE_SINGLETASKING &&
        ssGetSolverMode(S) != SOLVER_MODE_MULTITASKING) {
        ssSetErrorStatus(S, "C2837xBlock: Requires fixed-step solver");
        return;
    }

    ssSetSampleTime(S, 0, C2837X_BLOCK_SAMPLE_TIME_SEC);
    ssSetOffsetTime(S, 0, 0.0);
}

/* Function: mdlStart ==========================================================
 * Abstract:
 *    Connect to DSP and perform SIM_START handshake.
 */
#define MDL_START
static void mdlStart(SimStruct *S)
{
    C2837xBlockSfunContext* ctx = NULL;

    /* Single instance check */
    if (g_c2837x_block_instance_count > 0) {
        ssSetErrorStatus(S, "C2837xBlock: Only one instance allowed");
        return;
    }

    /* Increment instance count */
    g_c2837x_block_instance_count++;

    /* Create context */
    ctx = c2837x_block_sfun_create_context();
    if (ctx == NULL) {
        ssSetErrorStatus(S, "C2837xBlock: Failed to create context");
        g_c2837x_block_instance_count--;
        return;
    }

    /* Store context in PWork */
    ssSetPWorkValue(S, 0, ctx);

    /* Connect to DSP */
    if (c2837x_block_sfun_connect(ctx) != 0) {
        ssSetErrorStatus(S, "C2837xBlock: Failed to connect to DSP");
        c2837x_block_sfun_destroy_context(ctx);
        ssSetPWorkValue(S, 0, NULL);
        g_c2837x_block_instance_count--;
        return;
    }
}

/* Function: mdlOutputs =======================================================
 * Abstract:
 *    Perform one simulation step with direct port-to-payload conversion.
 *    No intermediate data structures are used.
 */
static void mdlOutputs(SimStruct *S, int_T tid)
{
    C2837xBlockSfunContext* ctx;

    /* Get context from PWork */
    ctx = (C2837xBlockSfunContext*)ssGetPWorkValue(S, 0);
    if (ctx == NULL) {
        ssSetErrorStatus(S, "C2837xBlock: Context not initialized");
        return;
    }

    /* Perform communication step with direct port I/O */
    if (c2837x_block_sfun_step(ctx, S) != 0) {
        /* Report DSP error code if available */
        if (ctx->last_dsp_error != C2837X_BLOCK_ERR_NONE) {
            char msg[128];
            const char* err_name;
            switch (ctx->last_dsp_error) {
                case C2837X_BLOCK_ERR_INTERNAL:      err_name = "Internal error"; break;
                case C2837X_BLOCK_ERR_LENGTH:        err_name = "Invalid length"; break;
                case C2837X_BLOCK_ERR_CONFIG_HASH:   err_name = "Config hash mismatch"; break;
                case C2837X_BLOCK_ERR_PAYLOAD_SIZE:  err_name = "Payload too large"; break;
                case C2837X_BLOCK_ERR_ALGORITHM:     err_name = "Algorithm error"; break;
                case C2837X_BLOCK_ERR_PROTOCOL_VERSION: err_name = "Protocol version mismatch"; break;
                case C2837X_BLOCK_ERR_STEP_INDEX:    err_name = "Step index mismatch"; break;
                case C2837X_BLOCK_ERR_STATE:         err_name = "Invalid state"; break;
                default:                             err_name = "Unknown error"; break;
            }
            snprintf(msg, sizeof(msg), "C2837xBlock: DSP error %d (%s) at step %u",
                     ctx->last_dsp_error, err_name, (unsigned)ctx->step_index);
            ssSetErrorStatus(S, msg);
        } else {
            ssSetErrorStatus(S, "C2837xBlock: Communication step failed");
        }
        return;
    }

    UNUSED_ARG(tid);
}

/* Function: mdlTerminate ======================================================
 * Abstract:
 *    Disconnect from DSP and release resources.
 */
static void mdlTerminate(SimStruct *S)
{
    C2837xBlockSfunContext* ctx;

    /* Get context from PWork */
    ctx = (C2837xBlockSfunContext*)ssGetPWorkValue(S, 0);

    if (ctx != NULL) {
        /* Graceful disconnect: send SIM_STOP */
        c2837x_block_sfun_disconnect(ctx, 1);

        /* Destroy context */
        c2837x_block_sfun_destroy_context(ctx);

        /* Clear PWork */
        ssSetPWorkValue(S, 0, NULL);
    }

    /* Decrement instance count */
    if (g_c2837x_block_instance_count > 0) {
        g_c2837x_block_instance_count--;
    }
}

/* Required S-function trailer */
#ifdef MATLAB_MEX_FILE
#include "simulink.c"
#else
#include "cg_sfun.h"
#endif
