/*
 * Auto-generated by C2837xBlock Configurator.
 * DO NOT EDIT MANUALLY.
 *
 * Port I/O helpers for C S-Function.
 *
 * These functions directly pack/unpack between Simulink ports and
 * wire-format payload buffers, eliminating intermediate data structures.
 *
 * Payload format (little-endian):
 *   [step_index: 4 bytes] [input0 data] [input1 data] ...
 */

#include "c2837x_block_pc_config.h"
#include <string.h>

/* SimStruct and port access macros are defined in simstruc.h */
#include "simstruc.h"

/* ---- Little-endian serialization helpers ---- */

static inline void write_le16(uint8_t* buf, uint16_t val)
{
    buf[0] = (uint8_t)(val & 0xFFu);
    buf[1] = (uint8_t)((val >> 8) & 0xFFu);
}

static inline void write_le32(uint8_t* buf, uint32_t val)
{
    buf[0] = (uint8_t)(val & 0xFFu);
    buf[1] = (uint8_t)((val >> 8) & 0xFFu);
    buf[2] = (uint8_t)((val >> 16) & 0xFFu);
    buf[3] = (uint8_t)((val >> 24) & 0xFFu);
}

static inline uint16_t read_le16(const uint8_t* buf)
{
    return (uint16_t)((uint16_t)buf[0] | ((uint16_t)buf[1] << 8));
}

static inline uint32_t read_le32(const uint8_t* buf)
{
    return ((uint32_t)buf[0]) |
           ((uint32_t)buf[1] << 8) |
           ((uint32_t)buf[2] << 16) |
           ((uint32_t)buf[3] << 24);
}


static inline void write_int16_le(uint8_t* buf, int16_t val) { write_le16(buf, (uint16_t)val); }
static inline int16_t read_int16_le(const uint8_t* buf) { return (int16_t)read_le16(buf); }

/* ---- Pack input ports directly to payload ---- */
void c2837x_block_pack_input_from_ports(SimStruct *S,
                                        uint8_t* payload,
                                        uint32_t step_index)
{
    uint32_t offset = 0;

    /* Write step_index (4 bytes, little-endian) */
    write_le32(&payload[offset], step_index);
    offset += 4;

    /* a: int16, port 0 */
    {
        const int16_t *u = (const int16_t *)ssGetInputPortSignal(S, 0);
        write_le16(&payload[offset], u[0]);
        offset += 2;
    }

}

/* ---- Unpack output payload directly to ports ---- */
void c2837x_block_unpack_output_to_ports(SimStruct *S,
                                         const uint8_t* payload,
                                         uint32_t* step_index)
{
    uint32_t offset = 0;

    /* Read step_index (4 bytes, little-endian) */
    *step_index = read_le32(&payload[offset]);
    offset += 4;

    /* sum: int16, port 0 */
    {
        int16_t *y = (int16_t *)ssGetOutputPortSignal(S, 0);
        y[0] = (int16_t)read_le16(&payload[offset]);
        offset += 2;
    }

}

/* ---- Port setup functions ---- */

int c2837x_block_setup_input_ports(SimStruct *S)
{
    if (!ssSetNumInputPorts(S, 1)) return -1;

    /* Port 0: a (int16, dim=1) */
    ssSetInputPortWidth(S, 0, 1);
    ssSetInputPortDataType(S, 0, SS_INT16);
    ssSetInputPortDirectFeedThrough(S, 0, 1);
    ssSetInputPortRequiredContiguous(S, 0, 1);
    return 0;
}

int c2837x_block_setup_output_ports(SimStruct *S)
{
    if (!ssSetNumOutputPorts(S, 1)) return -1;

    /* Port 0: sum (int16, dim=1) */
    ssSetOutputPortWidth(S, 0, 1);
    ssSetOutputPortDataType(S, 0, SS_INT16);
    return 0;
}

int c2837x_block_get_input_count(void) { return 1; }
int c2837x_block_get_output_count(void) { return 1; }
