#ifndef C2837X_BLOCK_PC_CONFIG_H
#define C2837X_BLOCK_PC_CONFIG_H

/*
 * Auto-generated by C2837xBlock Configurator.
 * DO NOT EDIT MANUALLY.
 *
 * PC/Simulink C S-Function side configuration.
 *
 * This file defines compile-time constants for the S-Function.
 * Port I/O is handled by c2837x_block_sfun_io.c (also auto-generated).
 */

#include <stdint.h>

/* ---- Protocol configuration ---- */
#define C2837X_BLOCK_PROTOCOL_VERSION  0x0001u
#define C2837X_BLOCK_CONFIG_HASH       0x12345678u  /* Match DSP config */
#define C2837X_BLOCK_SAMPLE_TIME_SEC   0.0001

/* ---- Network configuration ---- */
#define C2837X_BLOCK_IP_ADDR           "192.168.1.100"
#define C2837X_BLOCK_TCP_PORT          5000u

#define C2837X_BLOCK_MAX_PAYLOAD_SIZE_BYTES       1024u
#define C2837X_BLOCK_MAX_FRAME_SIZE_BYTES         (4u + C2837X_BLOCK_MAX_PAYLOAD_SIZE_BYTES)

/* ---- PC-side timeouts ---- */
#define C2837X_BLOCK_PC_CONNECT_TIMEOUT_MS        5000u
#define C2837X_BLOCK_PC_STEP_TIMEOUT_MS           5000u
#define C2837X_BLOCK_PC_TERMINATE_TIMEOUT_MS      1000u

/* ---- Data counts ---- */
#define C2837X_BLOCK_INPUT_COUNT       3u
#define C2837X_BLOCK_OUTPUT_COUNT      1u

/* ---- Wire byte sizes ---- */
#define C2837X_BLOCK_INPUT_DATA_SIZE_BYTES      6u
#define C2837X_BLOCK_OUTPUT_DATA_SIZE_BYTES     2u
#define C2837X_BLOCK_INPUT_PAYLOAD_SIZE_BYTES   (4u + C2837X_BLOCK_INPUT_DATA_SIZE_BYTES)
#define C2837X_BLOCK_OUTPUT_PAYLOAD_SIZE_BYTES  (4u + C2837X_BLOCK_OUTPUT_DATA_SIZE_BYTES)

/* ---- Port configuration ----
 * Each port has: WIDTH (elements), SIMTYPE (Simulink type ID), BYTES_PER_ELEM
 * Simulink type IDs: SS_DOUBLE=0, SS_SINGLE=1, SS_INT8=2, SS_UINT8=3,
 *                    SS_INT16=4, SS_UINT16=5, SS_INT32=6, SS_UINT32=7
 */

/* Input port configuration */
#define C2837X_BLOCK_INPUT0_WIDTH           1
#define C2837X_BLOCK_INPUT0_SIMTYPE         SS_INT16
#define C2837X_BLOCK_INPUT0_BYTES_PER_ELEM  2

#define C2837X_BLOCK_INPUT1_WIDTH           1
#define C2837X_BLOCK_INPUT1_SIMTYPE         SS_INT16
#define C2837X_BLOCK_INPUT1_BYTES_PER_ELEM  2

#define C2837X_BLOCK_INPUT2_WIDTH           1
#define C2837X_BLOCK_INPUT2_SIMTYPE         SS_INT16
#define C2837X_BLOCK_INPUT2_BYTES_PER_ELEM  2

/* Output port configuration */
#define C2837X_BLOCK_OUTPUT0_WIDTH          1
#define C2837X_BLOCK_OUTPUT0_SIMTYPE        SS_INT16
#define C2837X_BLOCK_OUTPUT0_BYTES_PER_ELEM 2

/* ---- Port I/O functions (implemented in c2837x_block_sfun_io.c) ---- */
/* Note: SimStruct is defined in simstruc.h, included by c2837x_block_sfun.c */
struct SimStruct_tag;
typedef struct SimStruct_tag SimStruct;

/*
 * Pack input ports directly to payload buffer.
 * Payload format: [step_index: 4 bytes] [input data...]
 * Total size: C2837X_BLOCK_INPUT_PAYLOAD_SIZE_BYTES
 */
void c2837x_block_pack_input_from_ports(SimStruct *S,
                                        uint8_t* payload,
                                        uint32_t step_index);

/*
 * Unpack output payload buffer directly to output ports.
 * Payload format: [step_index: 4 bytes] [output data...]
 * Total size: C2837X_BLOCK_OUTPUT_PAYLOAD_SIZE_BYTES
 */
void c2837x_block_unpack_output_to_ports(SimStruct *S,
                                         const uint8_t* payload,
                                         uint32_t* step_index);

#endif /* C2837X_BLOCK_PC_CONFIG_H */
