classdef test_s2_09_dual_instance < matlab.unittest.TestCase
    methods (Test)
        function testStaticProjectCompilesStrictly(testCase)
            root = test_s2_09_dual_instance.repositoryRoot();
            fixture = test_s2_09_dual_instance.fixtureFolder();
            object = fullfile(tempdir, 's2_09_dual_instance_project.o');
            command = sprintf([ ...
                'gcc -std=c11 -Wall -Wextra -Werror -I"%s" -I"%s" ' ...
                '-I"%s" -I"%s" -c "%s" -o "%s" 2>&1'], ...
                fullfile(root, 'tests', 'dsp_host', 'include'), ...
                fullfile(root, 'dsp', 'inc'), fullfile(root, 'dsp', 'src'), ...
                fixture, fullfile(fixture, ...
                's2_09_dual_instance_project.c'), object);
            [status, output] = system(command);
            testCase.verifyEqual(status, 0, output);
        end

        function testRuntimeFixture(testCase)
            root = test_s2_09_dual_instance.repositoryRoot();
            folder = fullfile(root, 'tests', 'dsp_host');
            executable = fullfile(tempdir, 's2_09_dual_instance_runtime.exe');
            command = sprintf([ ...
                'gcc -std=c11 -Wall -Wextra -Werror -I"%s" -I"%s" ' ...
                '-I"%s" "%s" "%s" "%s" -o "%s" 2>&1'], ...
                fullfile(folder, 'include'), fullfile(root, 'dsp', 'inc'), ...
                fullfile(root, 'dsp', 'src'), fullfile(folder, ...
                's2_09_dual_instance_runtime_test.c'), fullfile(root, ...
                'dsp', 'src', 'c2837x_block.c'), fullfile(root, ...
                'dsp', 'src', 'c2837x_block_protocol.c'), executable);
            [status, output] = system(command);
            testCase.assertEqual(status, 0, output);
            [status, output] = system(sprintf('"%s" 2>&1', executable));
            testCase.verifyEqual(status, 0, output);
            testCase.verifySubstring(output, 'platform_init=1 init=A,B');
            testCase.verifySubstring(output, ...
                'trace=A.receive,B.receive/B.receive,A.receive');
            testCase.verifySubstring(output, ...
                'states=A:SENDING+SIM_RUNNING B:RECEIVING+WAIT_SIM_START');
            testCase.verifySubstring(output, 'steps=A:2 B:1');
            testCase.verifySubstring(output, ...
                'isolation=protocol,timeout,receive,send,close,algorithm');
            testCase.verifySubstring(output, 'sessions=multiple');
        end

        function testPublicSurfaceAndPrivateStaticResources(testCase)
            [header, source] = test_s2_09_dual_instance.fixtureText();
            externs = regexp(header, ...
                'extern\s+C2837xBlock\s+g_s2_09_\w+\s*;', 'match');
            testCase.verifyNumElements(externs, 2);
            testCase.verifyNotEmpty(regexp(header, ...
                '#include\s+"c2837x_block\.h"', 'once'));
            testCase.verifyEmpty(regexp(header, ...
                'Config|Channel|rx_words|tx_words|Algorithm|internal', 'once'));
            testCase.verifyEqual(numel(regexp(source, ...
                'C2837X_BLOCK_INSTANCE_INITIALIZER\s*\(', 'match')), 2);
            testCase.verifyEqual(numel(regexp(source, ...
                'C2837X_W5300_CHANNEL_INITIALIZER\s*\(', 'match')), 2);
            testCase.verifyEqual(numel(regexp(source, ...
                'static\s+const\s+C2837xBlock_Config\s+\w+_config', ...
                'match')), 2);
            for name = {'current_loop_input', 'current_loop_output', ...
                    'current_loop_rx_words', 'current_loop_tx_words', ...
                    'current_loop_algorithm_context', ...
                    'current_loop_algorithm_adapter', ...
                    'current_loop_channel', 'current_loop_config', ...
                    'voltage_loop_input', 'voltage_loop_output', ...
                    'voltage_loop_rx_words', 'voltage_loop_tx_words', ...
                    'voltage_loop_algorithm_context', ...
                    'voltage_loop_algorithm_adapter', ...
                    'voltage_loop_channel', 'voltage_loop_config'}
                testCase.verifyNotEmpty(regexp(source, ...
                    ['static[\s\S]{0,80}\<' name{1} '\>'], 'once'), name{1});
            end
            testCase.verifyNotEmpty(regexp(source, ...
                '#define\s+C2837X_BLOCK_EXPECTED_CORE_API_VERSION\s+2u', ...
                'once'));
        end

        function testSocketPortMemoryAndConfigDifferences(testCase)
            [~, source] = test_s2_09_dual_instance.fixtureText();
            channels = regexp(source, [ ...
                'C2837X_W5300_CHANNEL_INITIALIZER\s*\(\s*' ...
                '(\d+)u,\s*(\d+)u,\s*(\d+)u,\s*(\d+)u'], ...
                'tokens');
            testCase.verifyNumElements(channels, 2);
            values = cellfun(@(tokens) cellfun(@str2double, tokens), ...
                channels, 'UniformOutput', false);
            values = vertcat(values{:});
            testCase.verifyEqual(values(:, 1), [1; 6]);
            testCase.verifyGreaterThanOrEqual(values(:, 1), 0);
            testCase.verifyLessThanOrEqual(values(:, 1), 7);
            testCase.verifyEqual(values(:, 2:3), repmat(8192, 2, 2));
            testCase.verifyEqual(values(:, 4), [5101; 5102]);
            testCase.verifyEqual(numel(unique(values(:, 1))), 2);
            testCase.verifyEqual(numel(unique(values(:, 4))), 2);
            testCase.verifyNotEmpty(regexp(source, ...
                '0x11112222u[\s\S]*5000000u,\s*1000000u', 'once'));
            testCase.verifyNotEmpty(regexp(source, ...
                '0x33334444u[\s\S]*7000000u,\s*2000000u', 'once'));
            testCase.verifyEqual(numel(regexp(source, ...
                '&c2837x_w5300_iodevice_ops', 'match')), 2);
            testCase.verifyEqual(numel(regexp(source, ...
                'c2837x_block_time_us', 'match')), 4);
        end

        function testNoForbiddenMechanismsOrExtraSocketResources(testCase)
            root = test_s2_09_dual_instance.repositoryRoot();
            fixture = test_s2_09_dual_instance.fixtureFolder();
            text = test_s2_09_dual_instance.readTree(fixture);
            text = [text newline fileread(fullfile(root, 'tests', ...
                'dsp_host', 's2_09_dual_instance_runtime_test.c'))];
            banned = { ...
                '\<(malloc|calloc|realloc|free)\s*\(', ...
                '\<memcpy\s*\([^;]*C2837xBlock', ...
                '\<(RunAll|InitAll)\>', ...
                '\<(RTOS|pthread|thread|scheduler)\>', ...
                '(current_instance|instance_registry|socket_registry)', ...
                '\<(main\.c|\.project|\.cproject)\>'};
            for index = 1:numel(banned)
                testCase.verifyEmpty(regexp(text, banned{index}, 'once'), ...
                    banned{index});
            end
            [~, source] = test_s2_09_dual_instance.fixtureText();
            testCase.verifyEqual(numel(regexp(source, ...
                'static\s+Uint16\s+\w+_(rx|tx)_words\s*\[', 'match')), 4);
        end

        function testManifestIsMinimalAndExplicit(testCase)
            root = test_s2_09_dual_instance.repositoryRoot();
            manifest = fileread(fullfile( ...
                test_s2_09_dual_instance.fixtureFolder(), ...
                's2_09_dsp_source_manifest.txt'));
            required = {'dsp/src/c2837x_block.c', ...
                'dsp/src/c2837x_block_protocol.c', ...
                'dsp/src/c2837x_block_platform.c', ...
                'dsp/src/c2837x_w5300_hal.c', ...
                'dsp/src/c2837x_w5300_socket.c', ...
                'dsp/src/c2837x_w5300_channel.c', ...
                ['tests/dsp_host/fixtures/s2_09_dual_instance/' ...
                 's2_09_dual_instance_project.c']};
            for item = required
                testCase.verifyNotEmpty(strfind(manifest, item{1}), item{1}); %#ok<STREMP>
            end
            testCase.verifyNotEmpty(regexp(manifest, ...
                'Exclude:[\s\S]*dsp/src/c2837x_block_config\.c', 'once'));
            testCase.verifyNotEmpty(strfind(manifest, ...
                'tests/dsp_host/s2_09_dual_instance_runtime_test.c')); %#ok<STREMP>
            testCase.verifyTrue(isfile(fullfile(root, 'dsp', 'src', ...
                'c2837x_block_config.c')));
        end

        function testFrozenCoreAndWireRemainDeviceIndependent(testCase)
            root = test_s2_09_dual_instance.repositoryRoot();
            core = [fileread(fullfile(root, 'dsp', 'src', ...
                'c2837x_block.c')) newline fileread(fullfile(root, ...
                'dsp', 'src', 'c2837x_block_internal.h'))];
            protocol = fileread(fullfile(root, 'dsp', 'inc', ...
                'c2837x_block_protocol.h'));
            testCase.verifyEmpty(regexp(core, ...
                '(W5300|Sn_|SOCK_|SEND_OK|ERRATUM)', 'once'));
            constants = {'SIM_START\s+0x0001u', 'INPUT_DATA\s+0x0002u', ...
                'OUTPUT_DATA\s+0x0003u', 'SIM_STOP\s+0x0004u', ...
                'RESPONSE\s+0x0005u', 'HEADER_SIZE_BYTES\s+4u'};
            for constant = constants
                testCase.verifyNotEmpty(regexp(protocol, constant{1}, ...
                    'once'), constant{1});
            end
        end
    end

    methods (Static, Access = private)
        function root = repositoryRoot()
            root = fileparts(fileparts(fileparts(mfilename('fullpath'))));
        end

        function folder = fixtureFolder()
            folder = fullfile(test_s2_09_dual_instance.repositoryRoot(), ...
                'tests', 'dsp_host', 'fixtures', 's2_09_dual_instance');
        end

        function [header, source] = fixtureText()
            folder = test_s2_09_dual_instance.fixtureFolder();
            header = fileread(fullfile(folder, ...
                's2_09_dual_instance_project.h'));
            source = fileread(fullfile(folder, ...
                's2_09_dual_instance_project.c'));
        end

        function text = readTree(folder)
            files = [dir(fullfile(folder, '**', '*.c')); ...
                     dir(fullfile(folder, '**', '*.h'))];
            text = '';
            for index = 1:numel(files)
                text = [text newline fileread(fullfile(files(index).folder, ...
                    files(index).name))]; %#ok<AGROW>
            end
        end
    end
end
