classdef test_s3_02_w5300_udp_channel < matlab.unittest.TestCase
    methods (Test)
        function testUdpRxAdapterFixture(testCase)
            root = test_s3_02_w5300_udp_channel.repositoryRoot();
            folder = fileparts(mfilename('fullpath'));
            executable = fullfile(tempdir, ...
                'w5300_udp_rx_adapter_test.exe');
            testCase.addTeardown(@() ...
                test_s3_02_w5300_udp_channel.deleteIfExists(executable));
            command = sprintf([ ...
                'gcc -std=c11 -Wall -Wextra -Werror -Wno-unknown-pragmas ' ...
                '-Wno-int-to-pointer-cast -DC2837X_W5300_HOST_TEST ' ...
                '-I"%s" -I"%s" -I"%s" "%s" "%s" "%s" "%s" ' ...
                '-o "%s" 2>&1'], ...
                fullfile(folder, 'include'), fullfile(root, 'dsp', 'inc'), ...
                fullfile(root, 'dsp', 'src'), ...
                fullfile(folder, 'w5300_udp_channel_test.c'), ...
                fullfile(root, 'dsp', 'src', 'c2837x_w5300_hal.c'), ...
                fullfile(root, 'dsp', 'src', 'c2837x_w5300_socket.c'), ...
                fullfile(root, 'dsp', 'src', ...
                'c2837x_w5300_udp_channel.c'), executable);
            [status, output] = system(command);
            testCase.verifyEqual(status, 0, output);
            if status == 0
                [status, output] = system(sprintf('"%s" 2>&1', ...
                    executable));
                testCase.verifyEqual(status, 0, output);
            end
        end

        function testUdpRxAdapterScope(testCase)
            root = test_s3_02_w5300_udp_channel.repositoryRoot();
            source = fileread(fullfile(root, 'dsp', 'src', ...
                'c2837x_w5300_udp_channel.c'));
            header = fileread(fullfile(root, 'dsp', 'inc', ...
                'c2837x_w5300_udp_channel.h'));

            for symbol = {'c2837x_w5300_socket_udp_read_data', ...
                    'c2837x_w5300_socket_udp_drop_data', ...
                    'c2837x_w5300_socket_udp_commit_recv'}
                testCase.verifyNotEmpty(regexp(source, ...
                    [symbol{1} '\s*\('], 'once'), symbol{1});
            end
            testCase.verifyNotEmpty(regexp(source, ...
                'payload_length', 'once'));
            testCase.verifyEmpty(regexp(source, ...
                'SIM_START|SIM_STOP|step_index|Interface Hash|RESPONSE', ...
                'once'));
            testCase.verifyEmpty(regexp(source, ...
                ['c2837x_block_parse_header|heartbeat|retry|malloc|calloc|' ...
                'realloc|free\s*\('], ...
                'once'));
            testCase.verifyEmpty(regexp(source, ...
                '\bwhile\s*\(|\bdo\s*\{|\bDELAY_US\b', 'once'));
            testCase.verifyEmpty(regexp([header newline source], ...
                '\[\s*(?:1472|1[0-9]{3,})\s*\]', 'once'));
        end
    end

    methods (Static, Access = private)
        function root = repositoryRoot()
            root = fileparts(fileparts(fileparts(mfilename('fullpath'))));
        end

        function deleteIfExists(path)
            if isfile(path)
                delete(path);
            end
        end
    end
end
