classdef test_s2_05_sci < matlab.unittest.TestCase
    methods (Test)
        function testSciTxPendingFixture(testCase)
            [status, output] = test_s2_05_sci.compileAndRun( ...
                'sci_tx_pending_test.c');
            testCase.verifyEqual(status, 0, output);
        end

        function testSciTxSourceContract(testCase)
            root = test_s2_05_sci.repositoryRoot();
            source = fileread(fullfile(root, 'dsp', 'src', ...
                'c2837x_block_sci.c'));
            header = fileread(fullfile(root, 'dsp', 'inc', ...
                'c2837x_block_sci.h'));
            testCase.verifyEmpty(regexp(source, ...
                'send_not_implemented', 'once'));
            testCase.verifyNotEmpty(test_s2_05_sci.regexpOnce( ...
                header, 'tx_pending_data_words'));
            testCase.verifyNotEmpty(test_s2_05_sci.regexpOnce( ...
                header, 'tx_pending_total_octets'));
            testCase.verifyNotEmpty(test_s2_05_sci.regexpOnce( ...
                header, 'tx_pending_queued_octets'));
            testCase.verifyNotEmpty(test_s2_05_sci.regexpOnce( ...
                source, 'SCIFFTX\.bit\.TXFFST'));
            testCase.verifyNotEmpty(test_s2_05_sci.regexpOnce( ...
                source, 'SCICTL2\.bit\.TXEMPTY'));
            testCase.verifyNotEmpty(test_s2_05_sci.regexpOnce( ...
                source, 'SCITXBUF\.all'));
            testCase.verifyEmpty(regexp(source, ...
                '(DELAY_US|delay_us|malloc|calloc|realloc|free)', ...
                'once'));
            testCase.verifyEmpty(regexp(source, ...
                'while\s*\(\s*1', 'once'));
        end
    end

    methods (Static, Access = private)
        function match = regexpOnce(text, expression)
            match = regexp(text, expression, 'match', 'once');
        end

        function [status, output] = compileAndRun(fixture)
            root = test_s2_05_sci.repositoryRoot();
            folder = fileparts(mfilename('fullpath'));
            executable = fullfile(tempdir, ...
                ['c2837x_s2_05_' erase(fixture, '.c') '.exe']);
            command = sprintf([ ...
                'gcc -std=c11 -Wall -Wextra -Werror ' ...
                '-DC2837X_BLOCK_SCI_HOST_TEST -I"%s" -I"%s" ' ...
                '"%s" "%s" -o "%s" 2>&1'], ...
                fullfile(folder, 'include'), ...
                fullfile(root, 'dsp', 'inc'), ...
                fullfile(folder, fixture), ...
                fullfile(root, 'dsp', 'src', 'c2837x_block_sci.c'), ...
                executable);
            [status, output] = system(command);
            if status == 0
                [status, runOutput] = system(sprintf('"%s" 2>&1', ...
                    executable));
                output = [output runOutput];
            end
        end

        function root = repositoryRoot()
            root = fileparts(fileparts(fileparts(mfilename('fullpath'))));
        end
    end
end
