classdef test_s2_04_sci < matlab.unittest.TestCase
    methods (Test)
        function testSciIoDeviceFixture(testCase)
            [status, output] = test_s2_04_sci.compileAndRun( ...
                'sci_iodevice_test.c');
            testCase.verifyEqual(status, 0, output);
        end

        function testSciRuntimeSourceIsBounded(testCase)
            root = test_s2_04_sci.repositoryRoot();
            source = fileread(fullfile(root, 'dsp', 'src', ...
                'c2837x_block_sci.c'));
            header = fileread(fullfile(root, 'dsp', 'inc', ...
                'c2837x_block_sci.h'));
            connection = regexp(source, ...
                ['static C2837xBlock_IoConnectionState get_connection_state' ...
                 '[\s\S]*?static int32 receive'], 'match', 'once');
            testCase.verifyNotEmpty(connection);
            testCase.verifyEmpty(regexp(connection, ...
                'SCIRXBUF', 'once'), 'SCIRXBUF');
            testCase.verifyNotEmpty(test_s2_04_sci.regexpOnce( ...
                connection, 'SCIFFRX\.bit\.RXFFST'));
            testCase.verifyNotEmpty(test_s2_04_sci.regexpOnce( ...
                source, 'SCIRXBUF\.all'));
            testCase.verifyNotEmpty(header, ...
                'C2837xBlock_SciChannelRuntime');
            testCase.verifyNotEmpty(test_s2_04_sci.regexpOnce( ...
                source, 'C2837xBlock_IoDeviceOps c2837x_block_sci_iodevice_ops'));
            testCase.verifyNotEmpty(header, ...
                'c2837x_block_sci_iodevice_ops');
            testCase.verifyEmpty(regexp(source, ...
                '(DELAY_US|delay_us|SCI_setConfig|malloc|calloc|realloc|free)', ...
                'once'));
            testCase.verifyEmpty(regexp(source, 'while\s*\(\s*1', 'once'));
        end

        function testSciSessionRuntimeFields(testCase)
            root = test_s2_04_sci.repositoryRoot();
            header = fileread(fullfile(root, 'dsp', 'inc', ...
                'c2837x_block_sci.h'));
            testCase.verifyNotEmpty(header, ...
                'connection_state');
            testCase.verifyNotEmpty(header, ...
                'session_cleanup_done');
            testCase.verifyNotEmpty(header, ...
                'C2837X_IODEVICE_CONNECTION_CLOSED');
        end
    end

    methods (Static, Access = private)
        function match = regexpOnce(text, expression)
            match = regexp(text, expression, 'match', 'once');
        end

        function [status, output] = compileAndRun(fixture)
            root = test_s2_04_sci.repositoryRoot();
            folder = fileparts(mfilename('fullpath'));
            executable = fullfile(tempdir, ...
                ['c2837x_s2_04_' erase(fixture, '.c') '.exe']);
            command = sprintf([ ...
                'gcc -std=c11 -Wall -Wextra -Werror ' ...
                '-DC2837X_BLOCK_SCI_HOST_TEST -I"%s" -I"%s" ' ...
                '"%s" "%s" -o "%s" 2>&1'], ...
                fullfile(folder, 'include'), ...
                fullfile(root, 'dsp', 'inc'), ...
                fullfile(folder, fixture), ...
                fullfile(root, 'dsp', 'src', 'c2837x_block_sci.c'), ...
                executable);
            [status, output] = system(command);
            if status == 0
                [status, runOutput] = system(sprintf('"%s" 2>&1', ...
                    executable));
                output = [output runOutput];
            end
        end

        function root = repositoryRoot()
            root = fileparts(fileparts(fileparts(mfilename('fullpath'))));
        end
    end
end
