classdef test_s3_04_w5300_udp_lifecycle < matlab.unittest.TestCase
    methods (Test)
        function testUdpSessionCleanupAndReacquisition(testCase)
            [status, output] = test_s3_04_w5300_udp_lifecycle.compileAndRun();
            testCase.verifyEqual(status, 0, output);
        end

        function testUdpCoreSessionLifecycleIntegration(testCase)
            [status, output] = ...
                test_s3_04_w5300_udp_lifecycle.compileAndRunCore();
            testCase.verifyEqual(status, 0, output);
        end

        function testUdpSessionScopeRemainsTransportOnly(testCase)
            root = test_s3_04_w5300_udp_lifecycle.repositoryRoot();
            source = fileread(fullfile(root, 'dsp', 'src', ...
                'c2837x_w5300_udp_channel.c'));
            header = fileread(fullfile(root, 'dsp', 'inc', ...
                'c2837x_w5300_udp_channel.h'));
            core = fileread(fullfile(root, 'dsp', 'src', ...
                'c2837x_block.c'));
            integration = fileread(fullfile(root, 'tests', 'dsp_host', ...
                'w5300_udp_core_lifecycle_test.c'));

            testCase.verifyEmpty(regexp([header newline source], ...
                'session_peer|peer_ip|promote_peer|session_accept', ...
                'once'));
            testCase.verifyEmpty(regexp(source, ...
                ['SIM_START|SIM_STOP|protocol_phase|SIM_RUNNING|' ...
                'interface_hash|step_index|heartbeat|keepalive|' ...
                'retry|retransmit|reconnect|resume|takeover'], 'once'));
            testCase.verifyNotEmpty(regexp(source, ...
                'candidate_ip|candidate_port|candidate_valid', 'once'));
            testCase.verifyNotEmpty(regexp(source, ...
                ['clear_socket_runtime|clear_candidate_and_datagram|' ...
                'reset_runtime'], 'once'));
            testCase.verifyNotEmpty(regexp(source, ...
                'C2837X_W5300_UDP_CLOSE_WAIT_EXISTING_CR', 'once'));
            testCase.verifyNotEmpty(regexp(source, ...
                'C2837X_W5300_UDP_CLOSE_WAIT_STATE', 'once'));
            testCase.verifyEmpty(regexp(source, ...
                ['c2837x_w5300_socket_check_close_erratum|' ...
                'c2837x_w5300_socket_dummy_tx_ready|' ...
                'c2837x_w5300_socket_issue_udp_open|' ...
                'c2837x_w5300_socket_issue_dummy_send'], 'once'));
            testCase.verifyEmpty(regexp(source, ...
                '\<while\>|\<do\s*\{|DELAY_US|delay_us|sleep', ...
                'once'));

            testCase.verifyNotEmpty(regexp(core, ...
                'c2837x_block_terminate_session', 'once'));
            testCase.verifyNotEmpty(regexp(core, ...
                ['close_pending|C2837X_BLOCK_WAIT_INTERACTION|' ...
                'C2837X_BLOCK_WAIT_TRANSFER|' ...
                'C2837X_BLOCK_PROTOCOL_WAIT_SIM_START'], 'once'));
            testCase.verifyEmpty(regexp(core, ...
                'C2837xW5300|Sn_|SOCK_', 'once'));

            testCase.verifyNotEmpty(regexp(integration, ...
                'c2837x_w5300_udp_iodevice_ops', 'once'));
            testCase.verifyNotEmpty(regexp(integration, ...
                'C2837xBlock_Init|C2837xBlock_Run|C2837xBlock_GetLastError', ...
                'once'));
            testCase.verifyNotEmpty(regexp(integration, ...
                'c2837x_block_internal.h', 'once'));
        end
    end

    methods (Static, Access = private)
        function [status, output] = compileAndRun()
            root = test_s3_04_w5300_udp_lifecycle.repositoryRoot();
            folder = fileparts(mfilename('fullpath'));
            executable = fullfile(tempdir, ...
                'c2837x_udp_s304_lifecycle_test.exe');
            command = sprintf([ ...
                'gcc -std=c11 -Wall -Wextra -Werror -Wno-unknown-pragmas ' ...
                '-Wno-int-to-pointer-cast -DC2837X_W5300_HOST_TEST ' ...
                '-I"%s" -I"%s" -I"%s" "%s" "%s" "%s" "%s" ' ...
                '-o "%s" 2>&1'], ...
                fullfile(folder, 'include'), fullfile(root, 'dsp', 'inc'), ...
                fullfile(root, 'dsp', 'src'), ...
                fullfile(folder, 'w5300_udp_channel_test.c'), ...
                fullfile(root, 'dsp', 'src', 'c2837x_w5300_hal.c'), ...
                fullfile(root, 'dsp', 'src', 'c2837x_w5300_socket.c'), ...
                fullfile(root, 'dsp', 'src', ...
                'c2837x_w5300_udp_channel.c'), executable);
            [status, output] = system(command);
            if status == 0
                [status, runOutput] = system(sprintf('"%s" full 2>&1', ...
                    executable));
                output = [output runOutput];
            end
            test_s3_04_w5300_udp_lifecycle.deleteIfExists(executable);
        end

        function [status, output] = compileAndRunCore()
            root = test_s3_04_w5300_udp_lifecycle.repositoryRoot();
            folder = fileparts(mfilename('fullpath'));
            executable = fullfile(tempdir, ...
                'c2837x_udp_s304_core_lifecycle_test.exe');
            command = sprintf([ ...
                'gcc -std=c11 -Wall -Wextra -Werror -Wno-unknown-pragmas ' ...
                '-Wno-int-to-pointer-cast -DC2837X_W5300_HOST_TEST ' ...
                '-I"%s" -I"%s" -I"%s" "%s" "%s" "%s" "%s" "%s" "%s" ' ...
                '-o "%s" 2>&1'], ...
                fullfile(folder, 'include'), fullfile(root, 'dsp', 'inc'), ...
                fullfile(root, 'dsp', 'src'), ...
                fullfile(folder, 'w5300_udp_core_lifecycle_test.c'), ...
                fullfile(root, 'dsp', 'src', 'c2837x_block.c'), ...
                fullfile(root, 'dsp', 'src', 'c2837x_block_protocol.c'), ...
                fullfile(root, 'dsp', 'src', 'c2837x_w5300_hal.c'), ...
                fullfile(root, 'dsp', 'src', 'c2837x_w5300_socket.c'), ...
                fullfile(root, 'dsp', 'src', ...
                'c2837x_w5300_udp_channel.c'), executable);
            [status, output] = system(command);
            if status == 0
                [status, runOutput] = system(sprintf('"%s" 2>&1', ...
                    executable));
                output = [output runOutput];
            end
            test_s3_04_w5300_udp_lifecycle.deleteIfExists(executable);
        end

        function root = repositoryRoot()
            root = fileparts(fileparts(fileparts(mfilename('fullpath'))));
        end

        function deleteIfExists(path)
            if isfile(path)
                delete(path);
            end
        end
    end
end
