classdef test_s2_06_sci < matlab.unittest.TestCase
    methods (Test)
        function testSciHalfDuplexFixture(testCase)
            [status, output] = test_s2_06_sci.compileAndRun( ...
                'sci_half_duplex_test.c');
            testCase.verifyEqual(status, 0, output);
        end

        function testSciHalfDuplexSourceContract(testCase)
            root = test_s2_06_sci.repositoryRoot();
            source = fileread(fullfile(root, 'dsp', 'src', ...
                'c2837x_block_sci.c'));

            testCase.verifyNotEmpty(regexp(source, ...
                'c2837x_block_sci_has_ctrl', 'once'));
            testCase.verifyNotEmpty(regexp(source, ...
                'c2837x_block_sci_ctrl_tx_level', 'once'));
            testCase.verifyNotEmpty(regexp(source, ...
                'GPIO_WritePin', 'once'));
            testCase.verifyEmpty(regexp(source, ...
                'C2837X_BLOCK_SCI_MAX_GPIO', 'once'));
            testCase.verifyEmpty(regexp(source, ...
                '(DELAY_US|delay_us|malloc|calloc|realloc|free)', ...
                'once'));
            testCase.verifyEmpty(regexp(source, ...
                'while\s*\(\s*1', 'once'));
            testCase.verifyEmpty(regexp(source, ...
                'while\s*\([^)]*TX(FFST|EMPTY)', 'once'));
            testCase.verifyNotEmpty(regexp(source, ...
                ['tx_pending_data_words\s*=\s*data_words[\s\S]*?' ...
                 'GPIO_WritePin[\s\S]*?ctrl_tx_active\s*=\s*1u'], ...
                'once'));
            testCase.verifyNotEmpty(regexp(source, ...
                ['GPIO_WritePin[\s\S]*?ctrl_tx_active\s*=\s*0u[\s\S]*?' ...
                 'c2837x_block_sci_clear_tx_pending'], 'once'));
        end
    end

    methods (Static, Access = private)
        function [status, output] = compileAndRun(fixture)
            root = test_s2_06_sci.repositoryRoot();
            folder = fileparts(mfilename('fullpath'));
            executable = fullfile(tempdir, ...
                ['c2837x_s2_06_' erase(fixture, '.c') '.exe']);
            command = sprintf([ ...
                'gcc -std=c11 -Wall -Wextra -Werror ' ...
                '-DC2837X_BLOCK_SCI_HOST_TEST -I"%s" -I"%s" ' ...
                '"%s" "%s" -o "%s" 2>&1'], ...
                fullfile(folder, 'include'), ...
                fullfile(root, 'dsp', 'inc'), ...
                fullfile(folder, fixture), ...
                fullfile(root, 'dsp', 'src', 'c2837x_block_sci.c'), ...
                executable);
            [status, output] = system(command);
            if status == 0
                [status, runOutput] = system(sprintf('"%s" 2>&1', ...
                    executable));
                output = [output runOutput];
            end
        end

        function root = repositoryRoot()
            root = fileparts(fileparts(fileparts(mfilename('fullpath'))));
        end
    end
end
