function tests = test_s2_03_sci
tests = functiontests(localfunctions);
end

function testDescriptorValidationAndHardwareBranches(testCase)
[status, output] = compileAndRun('sci_platform_init_test.c', ...
    {'c2837x_block_platform.c'}, ...
    {'-DC2837X_BLOCK_PLATFORM_CONFIG_EXTERN', ...
     '-DC2837X_BLOCK_SCI_HOST_TEST'});
verifyEqual(testCase, status, 0, output);
end

function testPlatformInitMapsDescriptorErrorToSciInit(testCase)
[status, output] = compileAndRun('sci_platform_invalid_config_test.c', ...
    {'c2837x_block_platform.c'}, ...
    {'-DC2837X_BLOCK_PLATFORM_CONFIG_EXTERN', ...
     '-DC2837X_BLOCK_SCI_HOST_TEST'});
verifyEqual(testCase, status, 0, output);
end

function testChannelRuntimeIsolation(testCase)
[status, output] = compileAndRun('sci_channel_runtime_test.c', ...
    {'c2837x_block_sci.c'});
verifyEqual(testCase, status, 0, output);
end

function testDescriptorAndChannelBoundaries(testCase)
root = repositoryRoot();
descriptor = fileread(fullfile(root, 'dsp', 'inc', ...
    'c2837x_block_sci.h'));
platform = fileread(fullfile(root, 'dsp', 'src', ...
    'c2837x_block_platform.c'));
channel = fileread(fullfile(root, 'dsp', 'src', ...
    'c2837x_block_sci.c'));

for symbol = {'C2837xBlock_SciDescriptor', 'C2837xBlock_SciModule', ...
        'C2837xBlock_SciRxEndpoint', 'C2837xBlock_SciTxEndpoint', ...
        'C2837xBlock_SciChannelRuntime', 'C2837X_BLOCK_SCI_NO_CTRL_GPIO'}
    verifyNotEmpty(testCase, regexp(descriptor, symbol{1}, 'once'), ...
        symbol{1});
end
for symbol = {'SciaRegs', 'ScibRegs', 'ScicRegs', 'ScidRegs', ...
        'GPIO_SetupPinMux', 'GPIO_SetupPinOptions', 'SCIHBAUD', ...
        'SCILBAUD', 'SCIFFENA', 'TXFIFORESET', 'RXFIFORESET'}
    verifyNotEmpty(testCase, regexp(platform, symbol{1}, 'once'), ...
        symbol{1});
end
verifyNotEmpty(testCase, regexp(platform, ...
    'SCIFFCT\.bit\.CDC\s*=\s*0u', 'once'));
verifyNotEmpty(testCase, regexp(platform, ...
    'SCIFFCT\.bit\.ABD\s*=\s*0u', 'once'));
verifyEmpty(testCase, regexp([descriptor platform channel], ...
    '\<(malloc|calloc|realloc|free|SCI_setConfig)\s*\(', 'once'));
verifyEmpty(testCase, regexp(channel, ...
    'GPIO_SetupPinMux|GPIO_SetupPinOptions|LOSPCP|SCIHBAUD|SCILBAUD', ...
    'once'));
end

function [status, output] = compileAndRun(fixture, sources, extraFlags)
if nargin < 3
    extraFlags = {};
end
root = repositoryRoot();
folder = fileparts(mfilename('fullpath'));
[~, executableName] = fileparts(fixture);
executable = fullfile(tempdir, [executableName '_sci.exe']);
sourceArguments = cellfun(@(name) sprintf('"%s"', ...
    fullfile(root, 'dsp', 'src', name)), sources, 'UniformOutput', false);
command = sprintf(['gcc -std=c11 -Wall -Wextra -Werror %s -I"%s" -I"%s" ' ...
    '-I"%s" "%s" %s -o "%s" 2>&1'], strjoin(extraFlags, ' '), ...
    fullfile(folder, 'include'), fullfile(root, 'dsp', 'inc'), ...
    fullfile(root, 'dsp', 'src'), fullfile(folder, fixture), ...
    strjoin(sourceArguments, ' '), executable);
[compileStatus, compileOutput] = system(command);
if compileStatus ~= 0
    status = compileStatus;
    output = compileOutput;
    return;
end
[status, output] = system(sprintf('"%s"', executable));
end

function root = repositoryRoot()
root = fileparts(fileparts(fileparts(mfilename('fullpath'))));
end
