function tests = test_s2_03a_static_config
tests = functiontests(localfunctions);
end

function testStaticConfigFixtureCompilesAndRuns(testCase)
[status, output, executable] = compile_binary();
verifyEqual(testCase, status, 0, output);
[status, output] = system(sprintf('"%s"', executable));
verifyEqual(testCase, status, 0, output);
end

function testInternalContractContainsFrozenBindings(testCase)
root = repository_root();
header = fileread(fullfile(root, 'dsp', 'src', ...
    'c2837x_block_config_internal.h'));
for field = {'iodevice_ops', 'iodevice_channel', ...
        'rx_frame_words', 'rx_frame_capacity_octets', ...
        'tx_frame_words', 'tx_frame_capacity_octets', ...
        'input_object', 'output_object', 'algorithm', ...
        'algorithm_context', 'protocol_version', 'interface_hash', ...
        'input_payload_octets', 'output_payload_octets', ...
        'max_payload_octets', 'interaction_timeout_us', ...
        'transfer_timeout_us'}
    verifyNotEmpty(testCase, regexp(header, ['\<' field{1} '\>'], 'once'), ...
        field{1});
end
for callback = {'reset_io', 'on_start', 'decode_input', ...
        'on_step', 'encode_output', 'on_stop'}
    verifyNotEmpty(testCase, regexp(header, ['\<' callback{1} '\>'], 'once'), ...
        callback{1});
end
end

function testBindingStaysInternalAndUnique(testCase)
root = repository_root();
publicHeader = fileread(fullfile(root, 'dsp', 'inc', 'c2837x_block.h'));
internalHeader = fileread(fullfile(root, 'dsp', 'src', ...
    'c2837x_block_internal.h'));
sources = read_tree(fullfile(root, 'dsp'));
verifyEmpty(testCase, regexp(publicHeader, ...
    'Config|AlgorithmAdapter|IoDevice|void\s*\*', 'once'));
verifyNotEmpty(testCase, regexp(internalHeader, ...
    'C2837X_BLOCK_INSTANCE_INITIALIZER', 'once'));
verifyEmpty(testCase, regexp(sources, ...
    ['c2837x_block_' 'bind_iodevice'], 'once'));
verifyEmpty(testCase, regexp(sources, ...
    '\<(bind_config|register_device|set_callbacks)\s*\(', 'once'));
end

function testCoreUsesNoRetiredSingleInstanceSymbols(testCase)
root = repository_root();
source = fileread(fullfile(root, 'dsp', 'src', 'c2837x_block.c'));
patterns = {'C2837X_BLOCK_PROTOCOL_VERSION', 'C2837X_BLOCK_CONFIG_HASH', ...
    'C2837X_BLOCK_INPUT_PAYLOAD_SIZE_BYTES', ...
    'C2837X_BLOCK_OUTPUT_PAYLOAD_SIZE_BYTES', ...
    'C2837X_BLOCK_MAX_PAYLOAD_SIZE_BYTES', ...
    'C2837X_BLOCK_INPUT_DATA_SIZE_', 'C2837X_BLOCK_OUTPUT_DATA_SIZE_', ...
    'c2837x_block_input', 'c2837x_block_output', ...
    'C2837xBlock_OnSimStart', 'C2837xBlock_OnStep', ...
    'C2837xBlock_OnSimStop', 'c2837x_block_unpack_input_payload', ...
    'c2837x_block_pack_output_payload'};
for index = 1:numel(patterns)
    verifyEmpty(testCase, regexp(source, patterns{index}, 'once'), ...
        patterns{index});
end
end

function testSampleUsesStrongTypedAlgorithmAndStaticConfig(testCase)
root = repository_root();
algorithm = fileread(fullfile(root, 'dsp', 'src', 'my_algorithm.c'));
config = fileread(fullfile(root, 'dsp', 'src', 'c2837x_block_config.c'));
verifyNotEmpty(testCase, regexp(algorithm, ...
    'C2837xBlock_OnStep\s*\([^)]*InputData\s*\*', 'once'));
verifyNotEmpty(testCase, regexp(config, ...
    'static\s+const\s+C2837xBlock_Config', 'once'));
verifyNotEmpty(testCase, regexp(config, ...
    'C2837X_BLOCK_INSTANCE_INITIALIZER', 'once'));
verifyEmpty(testCase, regexp([algorithm config], ...
    '\<(malloc|calloc|realloc|free)\s*\(', 'once'));
end

function testSampleConfigAndAlgorithmCompileStrictly(testCase)
root = repository_root();
folder = fileparts(mfilename('fullpath'));
for source = {'c2837x_block_config.c', 'my_algorithm.c'}
    object = fullfile(tempdir, [source{1} '.o']);
    command = sprintf(['gcc -std=c11 -Wall -Wextra -Werror -I"%s" ' ...
        '-I"%s" -I"%s" -c "%s" -o "%s" 2>&1'], ...
        fullfile(folder, 'include'), fullfile(root, 'dsp', 'inc'), ...
        fullfile(root, 'dsp', 'src'), ...
        fullfile(root, 'dsp', 'src', source{1}), object);
    [status, output] = system(command);
    verifyEqual(testCase, status, 0, output);
end
end

function [status, output, executable] = compile_binary()
root = repository_root();
folder = fileparts(mfilename('fullpath'));
executable = fullfile(tempdir, 'c2837x_s2_03a_config_test.exe');
command = sprintf(['gcc -std=c11 -Wall -Wextra -Werror -I"%s" -I"%s" ' ...
    '-I"%s" "%s" "%s" -o "%s" 2>&1'], ...
    fullfile(folder, 'include'), fullfile(root, 'dsp', 'inc'), ...
    fullfile(root, 'dsp', 'src'), ...
    fullfile(folder, 'core_instance_test.c'), ...
    fullfile(root, 'dsp', 'src', 'c2837x_block.c'), executable);
[status, output] = system(command);
end

function text = read_tree(folder)
files = [dir(fullfile(folder, '**', '*.c')); ...
         dir(fullfile(folder, '**', '*.h'))];
text = '';
for index = 1:numel(files)
    text = [text newline fileread(fullfile(files(index).folder, ...
        files(index).name))]; %#ok<AGROW>
end
end

function root = repository_root()
root = fileparts(fileparts(fileparts(mfilename('fullpath'))));
end
