classdef test_s2_02_platform_init < matlab.unittest.TestCase
    methods (Test)
        function testPlatformInitializationAndFailures(testCase)
            [status, output] = compileAndRun('platform_init_test.c', ...
                {'c2837x_block_platform.c'});
            testCase.verifyEqual(status, 0, output);
        end

        function testConditionalTransportInitialization(testCase)
            modes = [
                struct('name', 'W5300_ONLY', 'value', 1)
                struct('name', 'SCI_ONLY',   'value', 2)
                struct('name', 'MIXED',      'value', 3)];
            for mode = modes'
                flags = sprintf(['-DC2837X_BLOCK_PLATFORM_CONFIG_EXTERN ' ...
                    '-DC2837X_BLOCK_PLATFORM_TEST_MODE=%u ' ...
                    '-DC2837X_BLOCK_PLATFORM_TEST_SEAM'], mode.value);
                [status, output] = compileAndRun( ...
                    'platform_sci_modes_test.c', ...
                    {'c2837x_block_platform.c'}, {flags});
                testCase.verifyEqual(status, 0, ...
                    sprintf('%s: %s', mode.name, output));
            end
        end

        function testTimer2MicrosecondSource(testCase)
            [status, output] = compileAndRun('timer2_test.c', ...
                {'c2837x_block_timer2.c'});
            testCase.verifyEqual(status, 0, output);
        end

        function testRealW5300HalInitializationControlFlow(testCase)
            [status, output] = compileAndRun('w5300_hal_init_test.c', ...
                {'c2837x_w5300_hal.c', 'c2837x_block_platform.c'}, ...
                {'-Wno-unknown-pragmas', '-Wno-int-to-pointer-cast'});
            testCase.verifyEqual(status, 0, output);
        end

        function testResetTimingAndScope(testCase)
            root = repositoryRoot();
            halHeader = fileread(fullfile(root, 'dsp', 'inc', ...
                'c2837x_w5300_hal.h'));
            halSource = fileread(fullfile(root, 'dsp', 'src', ...
                'c2837x_w5300_hal.c'));
            platformSource = fileread(fullfile(root, 'dsp', 'src', ...
                'c2837x_block_platform.c'));
            testCase.verifyNotEmpty(regexp(halHeader, ...
                'RESET_ASSERT_US\s+2u', 'once'));
            testCase.verifyNotEmpty(regexp(halHeader, ...
                'RESET_SETTLE_US\s+10000u', 'once'));
            testCase.verifyNotEmpty(regexp(halSource, ...
                ['GPIO_WritePin\([^;]+,\s*0\);\s*' ...
                 'DELAY_US\(C2837X_W5300_RESET_ASSERT_US\);\s*' ...
                 'GPIO_WritePin\([^;]+,\s*1\);\s*' ...
                 'DELAY_US\(C2837X_W5300_RESET_SETTLE_US\);'], 'once'));
            testCase.verifyEmpty(regexp(platformSource, ...
                '\<Sn_CR_(OPEN|LISTEN)\>', 'once'));
        end

        function testInstanceInitKeepsPlatformHardwareBoundary(testCase)
            root = repositoryRoot();
            instanceSource = fileread(fullfile(root, 'dsp', 'src', ...
                'c2837x_block.c'));
            testCase.verifyEmpty(regexp(instanceSource, ...
                ['C2837xBlock_PlatformInit|c2837x_block_timer2_init|' ...
                 'c2837x_w5300|LOSPCP|LSPCLK|PinMux|GPIO_SetupPin'], ...
                'once'));
        end

        function testPlatformConfigContractIsOpaqueAndProjectScoped(testCase)
            root = repositoryRoot();
            header = fileread(fullfile(root, 'dsp', 'src', ...
                'c2837x_block_platform.h'));
            platformSource = fileread(fullfile(root, 'dsp', 'src', ...
                'c2837x_block_platform.c'));
            for symbol = {'use_w5300', 'sci_descriptors', ...
                    'C2837xBlock_SciDescriptorCollection', ...
                    'C2837xBlock_PlatformConfig', ...
                    'c2837x_block_sci_platform_init'}
                testCase.verifyNotEmpty(regexp(header, ...
                    ['\<' symbol{1} '\>'], 'once'), symbol{1});
            end
            testCase.verifyNotEmpty(regexp(header, ...
                'c2837x_block_sci\.h', 'once'));
            testCase.verifyNotEmpty(regexp(header, ...
                'SCI_LSPCLK_DIVISOR\s+4u', 'once'));
            testCase.verifyNotEmpty(regexp(header, ...
                'SCI_LOSPCP_VALUE\s+2u', 'once'));
            testCase.verifyNotEmpty(regexp(platformSource, ...
                'ClkCfgRegs\.LOSPCP\.all\s*=\s*C2837X_BLOCK_SCI_LOSPCP_VALUE;', 'once'));
            testCase.verifyEmpty(regexp(header, ...
                'sci_lspclk_bringup\s*;', 'once'));
            testCase.verifyEmpty(regexp(header, ...
                'sci_init\s*;', 'once'));
        end
    end
end

function [status, output] = compileAndRun(fixture, sources, extraFlags)
if nargin < 3
    extraFlags = {};
end
root = repositoryRoot();
folder = fileparts(mfilename('fullpath'));
[~, executableName] = fileparts(fixture);
executable = fullfile(tempdir, [executableName '.exe']);
sourceArguments = cellfun(@(name) sprintf('"%s"', ...
    fullfile(root, 'dsp', 'src', name)), sources, 'UniformOutput', false);
command = sprintf(['gcc -std=c11 -Wall -Wextra -Werror %s -I"%s" -I"%s" ' ...
    '-I"%s" "%s" %s -o "%s" 2>&1'], strjoin(extraFlags, ' '), ...
    fullfile(folder, 'include'), fullfile(root, 'dsp', 'inc'), fullfile(root, 'dsp', 'src'), ...
    fullfile(folder, fixture), strjoin(sourceArguments, ' '), executable);
[compileStatus, compileOutput] = system(command);
if compileStatus ~= 0
    status = compileStatus;
    output = compileOutput;
    return;
end
[status, output] = system(sprintf('"%s"', executable));
end

function root = repositoryRoot()
root = fileparts(fileparts(fileparts(mfilename('fullpath'))));
end
