function codes = legacy_v1_error_codes()
%LEGACY_V1_ERROR_CODES Immutable V1 RESPONSE error-code matrix.

codes = struct( ...
    'value', num2cell(uint16(0:8)), ...
    'dsp_symbol', { ...
        'C2837X_ERR_OK', ...
        'C2837X_ERR_UNKNOWN_TYPE', ...
        'C2837X_ERR_PAYLOAD_LENGTH', ...
        'C2837X_ERR_CONFIG_MISMATCH', ...
        'C2837X_ERR_STATE', ...
        'C2837X_ERR_INTERNAL', ...
        'C2837X_ERR_PROTOCOL_VERSION', ...
        'C2837X_ERR_STEP_INDEX', ...
        'C2837X_ERR_UNSUPPORTED_TYPE'}, ...
    'pc_symbol', { ...
        'C2837X_BLOCK_ERR_NONE', ...
        'C2837X_BLOCK_ERR_UNKNOWN_TYPE', ...
        'C2837X_BLOCK_ERR_LENGTH', ...
        'C2837X_BLOCK_ERR_CONFIG_HASH', ...
        'C2837X_BLOCK_ERR_STATE', ...
        'C2837X_BLOCK_ERR_INTERNAL', ...
        'C2837X_BLOCK_ERR_PROTOCOL_VERSION', ...
        'C2837X_BLOCK_ERR_STEP_INDEX', ...
        'C2837X_BLOCK_ERR_UNSUPPORTED_TYPE'}, ...
    'wire_semantics', { ...
        'request succeeded', ...
        'unknown message type', ...
        'invalid or fixed-length-mismatched payload', ...
        'interface hash or configuration mismatch', ...
        'message invalid in current protocol state', ...
        'DSP internal processing or algorithm failure', ...
        'protocol version mismatch', ...
        'step_index mismatch', ...
        'unsupported data type or ABI'}, ...
    'new_architecture_produces', num2cell([true true true true true true true true false]));
end
