function parsed = legacy_v1_parse_pc_frame(frame_octets)
%LEGACY_V1_PARSE_PC_FRAME Model the historical PC little-endian parser.
frame_octets = uint8(frame_octets(:).');
assert(numel(frame_octets) >= 4, ...
    'DSPSimBridge:LegacyV1:IncompleteHeader', ...
    'Frame header is incomplete.');
msg_type = uint16(frame_octets(1)) + bitshift(uint16(frame_octets(2)), 8);
payload_length = uint16(frame_octets(3)) + bitshift(uint16(frame_octets(4)), 8);
assert(mod(double(payload_length), 2) == 0, ...
    'DSPSimBridge:LegacyV1:OddPayloadOctetCount', ...
    'Payload length must be even.');
assert(numel(frame_octets) == 4 + double(payload_length), ...
    'DSPSimBridge:LegacyV1:FrameLengthMismatch', ...
    'Frame length mismatch.');
parsed = struct('type', msg_type, 'payload_length', payload_length, ...
    'payload', frame_octets(5:end));
end
