classdef test_sci_s4_03_sfun_lifecycle < matlab.unittest.TestCase
    properties
        RepositoryRoot
    end

    methods (TestClassSetup)
        function addAppPath(testCase)
            testCase.RepositoryRoot = fileparts(fileparts(fileparts( ...
                mfilename('fullpath'))));
            testCase.applyFixture(matlab.unittest.fixtures.PathFixture( ...
                fullfile(testCase.RepositoryRoot, 'app')));
        end
    end

    methods (Test)
        function testParameterContractAndGeneratedConfig(testCase)
            w5300 = render_instance('w5300_tcp');
            sci = render_instance('sci');
            userConfig = native2unicode( ...
                c2837x_block_render_sfun_build_files(sci.project).user_config_bytes, ...
                'UTF-8');

            testCase.verifySubstring(w5300.sfun, ...
                'ssSetNumSFcnParams(S, 0);');
            testCase.verifyEmpty(strfind(w5300.sfun, ...
                'ssSetSFcnParamTunable'));
            testCase.verifySubstring(w5300.config, ...
                '#define AXIS_ALPHA_SFUN_TCP_PORT 5000u');
            testCase.verifyEmpty(strfind(w5300.config, ...
                'SFUN_REQUESTED_BAUD'));

            testCase.verifySubstring(sci.sfun, ...
                'ssSetNumSFcnParams(S, 1);');
            testCase.verifySubstring(sci.sfun, ...
                'ssSetSFcnParamTunable(S, 0, 0);');
            testCase.verifySubstring(sci.sfun, ...
                '#define MDL_CHECK_PARAMETERS');
            testCase.verifySubstring(sci.sfun, ...
                'c2837x_pc_serial_configure(&context->serial,');
            testCase.verifySubstring(sci.sfun, ...
                'AXIS_ALPHA_SFUN_REQUESTED_BAUD');
            testCase.verifySubstring(sci.config, ...
                '#define AXIS_ALPHA_SFUN_IODEVICE_SCI 1u');
            testCase.verifySubstring(sci.config, ...
                '#define AXIS_ALPHA_SFUN_REQUESTED_BAUD 57600u');
            testCase.verifySubstring(sci.config, ...
                '#define AXIS_ALPHA_SFUN_NOMINAL_BAUD 57600u');
            testCase.verifyFalse(contains(sci.config, 'COM'));
            testCase.verifyFalse(contains(sci.config, 'DSP_IP_ADDRESS'));
            testCase.verifyFalse(contains(sci.config, 'TCP_PORT'));

            testCase.verifyEqual( ...
                numel(regexp(userConfig, '(?m)^#define\s+', 'match')), 4);
            testCase.verifySubstring(userConfig, ...
                '#define CONNECT_TIMEOUT_MS');
            testCase.verifySubstring(userConfig, ...
                '#define STEP_TIMEOUT_MS');
            testCase.verifySubstring(userConfig, ...
                '#define TERMINATE_TIMEOUT_MS');
            testCase.verifyEmpty(regexpi(userConfig, ...
                'SERIAL_TIMEOUT|SERIAL_OPEN_TIMEOUT|SERIAL_RX_TIMEOUT|SERIAL_TX_TIMEOUT', ...
                'once'));
        end

        function testUpdateDiagramStaticComRules(testCase)
            sci = render_instance('sci');
            checker = section(sci.sfun, ...
                'static int axis_alpha_sfun_parse_com_number', ...
                '#define MDL_CHECK_PARAMETERS');

            testCase.verifySubstring(checker, 'ssGetSFcnParam(S, 0)');
            testCase.verifySubstring(checker, 'mxIsNumeric(parameter)');
            testCase.verifySubstring(checker, 'mxIsComplex(parameter)');
            testCase.verifySubstring(checker, ...
                'mxGetNumberOfElements(parameter) != 1u');
            testCase.verifySubstring(checker, 'mxIsFinite(value)');
            testCase.verifySubstring(checker, 'value <= 0.0');
            testCase.verifySubstring(checker, 'value != floor(value)');
            testCase.verifySubstring(checker, ...
                'value > (double)UINT32_MAX');
            testCase.verifyFalse(contains(lower(checker), 'createfile'));
            testCase.verifyFalse(contains(lower(checker), 'purge'));
            testCase.verifyFalse(contains(checker, 'SIM_START'));
            testCase.verifyFalse(contains(lower(checker), 'enumerat'));
        end

        function testSciStartStepTerminateLifecycle(testCase)
            sci = render_instance('sci');
            start = section(sci.sfun, 'static void mdlStart', ...
                'static void mdlOutputs');
            step = section(sci.sfun, 'static void mdlOutputs', ...
                'static void mdlTerminate');
            terminate = section(sci.sfun, 'static void mdlTerminate', ...
                '#ifndef MATLAB_MEX_FILE');
            destroy = section(sci.sfun, ...
                'void axis_alpha_sfun_destroy_context', ...
                'static const char *axis_alpha_sfun_error_text(SimStruct *S,');

            verify_order(testCase, start, { ...
                'axis_alpha_sfun_parse_com_number', ...
                'axis_alpha_sfun_create_context', ...
                'c2837x_pc_serial_init', ...
                'c2837x_pc_serial_open', ...
                'c2837x_pc_serial_configure', ...
                'c2837x_pc_serial_purge', ...
                'axis_alpha_protocol_send_sim_start', ...
                'axis_alpha_protocol_wait_response', ...
                'context->step_index = 0u', ...
                'context->session_started = 1'});
            testCase.verifyEqual(numel(strfind(start, ...
                'c2837x_pc_serial_purge')), 1);
            testCase.verifyEqual(numel(strfind(start, ...
                'STEP_TIMEOUT_MS')), 2);
            testCase.verifyEmpty(strfind(start, 'CONNECT_TIMEOUT_MS'));
            testCase.verifyEmpty(regexpi(start, ...
                'sleep|retry|reconnect|autobaud|bootloader|CreateFile|''A''', 'once'));
            testCase.verifySubstring(start, ...
                'ssSetPWorkValue(S, 0, NULL);');
            testCase.verifySubstring(start, ...
                'axis_alpha_sfun_destroy_context(context);');

            verify_order(testCase, step, { ...
                'axis_alpha_sfun_pack_input_payload', ...
                'axis_alpha_protocol_send_input_data', ...
                'axis_alpha_protocol_wait_output_data', ...
                'axis_alpha_sfun_decode_output_payload', ...
                'axis_alpha_sfun_commit_output_ports', ...
                'context->step_index++'});
            testCase.verifyEqual(numel(strfind(step, ...
                'STEP_TIMEOUT_MS')), 2);
            testCase.verifySubstring(sci.sfun, 'c2837x_pc_serial_close');
            testCase.verifySubstring(sci.sfun, 'context->session_started = 0;');
            testCase.verifySubstring(sci.sfun, 'ssSetErrorStatus(S,');
            testCase.verifyEmpty(regexpi(step, ...
                'retry|reconnect|resend|pipeline|thread|CreateFile|Sleep', 'once'));

            verify_order(testCase, terminate, { ...
                'axis_alpha_protocol_send_sim_stop', ...
                'axis_alpha_sfun_destroy_context'});
            testCase.verifySubstring(terminate, ...
                ['axis_alpha_sfun_destroy_context(context);' newline ...
                 '    ssSetPWorkValue(S, 0, NULL);']);
            testCase.verifyEqual(numel(strfind(terminate, ...
                'TERMINATE_TIMEOUT_MS')), 1);
            testCase.verifySubstring(terminate, 'cleanup_error');
            testCase.verifyEmpty(strfind(terminate, ...
                'axis_alpha_protocol_wait_response'));
            testCase.verifyEmpty(strfind(terminate, 'ssSetErrorStatus'));
            verify_order(testCase, destroy, { ...
                'c2837x_pc_serial_close', 'free(context)'});
        end

        function testSingleProtocolBindingUsesOneReceiveDeadline(testCase)
            w5300 = render_instance('w5300_tcp');
            sci = render_instance('sci');
            receive = section(sci.protocol, ...
                'int axis_alpha_protocol_recv_frame', ...
                'int axis_alpha_protocol_send_sim_start');
            send = section(sci.protocol, ...
                'static int axis_alpha_protocol_send_complete_frame', ...
                'int axis_alpha_protocol_recv_frame');

            testCase.verifySubstring(w5300.protocol, ...
                'axis_alpha_protocol_send_input_data(AxisAlphaPcSocket *socket,');
            testCase.verifyEmpty(regexpi(sci.protocol, ...
                'protocol_tcp|protocol_sci', 'once'));
            testCase.verifySubstring(sci.protocolHeader, ...
                '#include "axis_alpha_pc_serial.h"');
            testCase.verifyEmpty(strfind(sci.protocolHeader, ...
                'c2837x_block_pc_serial.h'));
            testCase.verifySubstring(sci.protocol, ...
                'c2837x_pc_serial_deadline_start');
            testCase.verifySubstring(sci.protocol, ...
                'c2837x_pc_serial_send_all_until');
            testCase.verifySubstring(sci.protocol, ...
                'c2837x_pc_serial_recv_exact_until');
            testCase.verifyEqual(numel(strfind(sci.protocol, ...
                'c2837x_pc_serial_recv_exact(')), 0);
            verify_order(testCase, receive, { ...
                'axis_alpha_pc_serial_deadline_start', ...
                'axis_alpha_pc_serial_recv_exact_until(socket, header', ...
                'axis_alpha_pc_serial_recv_exact_until(socket, payload'});
            verify_order(testCase, send, { ...
                'axis_alpha_pc_serial_deadline_start', ...
                'axis_alpha_pc_serial_send_all_until'});
            testCase.verifyEqual(numel(strfind(receive, '&deadline')), 3);
            testCase.verifyEqual(numel(strfind(send, '&deadline')), 2);
        end

        function testGeneratedSciSfunHostRuntime(testCase)
            output = run_sci_host_runtime(testCase, testCase.RepositoryRoot);
            testCase.verifySubstring(output, 'SUMMARY passed=41 failed=0');
            testCase.verifySubstring(output, 'PASS start_call_order');
            testCase.verifySubstring(output, ...
                'PASS start_requested_baud_and_purge');
            testCase.verifySubstring(output, ...
                'PASS step_success_commit_and_increment');
            testCase.verifySubstring(output, ...
                'PASS terminate_best_effort_and_cleanup');
            testCase.verifySubstring(output, ...
                'ERROR_TEXT serial_os_error instance=axis_alpha COM=7 baud=115200 stage=serial_open category=serial');
            testCase.verifySubstring(output, ...
                'ERROR_TEXT partial_timeout instance=axis_alpha COM=7 baud=115200 stage=recv_payload category=timeout');
            testCase.verifySubstring(output, ...
                'ERROR_TEXT protocol_dsp_error instance=axis_alpha COM=7 baud=115200 stage=wait_response category=dsp_response');
            testCase.verifySubstring(output, ...
                'ERROR_TEXT decode_step_error instance=axis_alpha COM=7 baud=115200 stage=decode_output category=step_index');
            testCase.verifySubstring(output, ...
                'ERROR_TEXT commit_port_error instance=axis_alpha COM=7 baud=115200 stage=commit_output category=port_access');
        end

        function testGeneratedSciProtocolProductionBinding(testCase)
            evidence = run_sci_production_binding(testCase);
            testCase.verifyEqual(evidence.protocol_status, 0, evidence.output);
            testCase.verifyEqual(evidence.serial_status, 0, evidence.output);
            testCase.verifySubstring(evidence.output, ...
                'axis_alpha_pc_serial.c');
            testCase.verifySubstring(evidence.output, ...
                'GENERATED_SERIAL_HEADER:');
            testCase.verifyEmpty(strfind(evidence.output, ...
                'c2837x_block_pc_serial.c'));
            testCase.verifyEmpty(strfind(evidence.output, 'sci_host'));
            testCase.verifyEmpty(strfind(evidence.output, ...
                'sci_sfun_host_serial.c'));
        end
    end
end

function output = render_instance(type)
project = c2837x_block_create_default_project();
instance = c2837x_block_create_default_instance();
instance.display_name = 'Axis Alpha';
instance.internal_name = 'axis_alpha';
instance.inputs = struct('name', 'command', 'type', 'uint16', 'dim', 1);
instance.outputs = struct('name', 'feedback', 'type', 'uint16', 'dim', 1);
if strcmp(type, 'sci')
    instance.iodevice = c2837x_block_create_iodevice('sci');
    instance.iodevice.settings.module = 'SCI-B';
    instance.iodevice.settings.rx_gpio = 'GPIO19';
    instance.iodevice.settings.tx_gpio = 'GPIO14';
end
project.instances = instance;
rendered = c2837x_block_render_sfun_files(project);
pc = c2837x_block_render_pc_files(project);
output = struct( ...
    'project', project, ...
    'sfun', native2unicode(rendered.sfun_source_bytes, 'UTF-8'), ...
    'config', native2unicode(rendered.config_header_bytes, 'UTF-8'), ...
    'protocol', native2unicode(pc.protocol_source_bytes, 'UTF-8'), ...
    'protocolHeader', native2unicode(pc.protocol_header_bytes, 'UTF-8'), ...
    'pcError', native2unicode(pc.pc_error_header_bytes, 'UTF-8'), ...
    'serialSource', native2unicode(pc.serial_source_bytes, 'UTF-8'), ...
    'serialHeader', native2unicode(pc.serial_header_bytes, 'UTF-8'));
end

function output = run_sci_host_runtime(testCase, repositoryRoot)
root = c2837x_block_normalize_absolute_path(tempname);
mkdir(root);
testCase.addTeardown(@() rmdir(root, 's'));
project = c2837x_block_create_default_project();
instance = c2837x_block_create_default_instance();
instance.display_name = 'Axis Alpha';
instance.internal_name = 'axis_alpha';
instance.inputs = struct('name', 'command', 'type', 'uint16', 'dim', 1);
instance.outputs = struct('name', 'feedback', 'type', 'uint16', 'dim', 1);
instance.iodevice = c2837x_block_create_iodevice('sci');
instance.iodevice.settings.module = 'SCI-B';
instance.iodevice.settings.rx_gpio = 'GPIO19';
instance.iodevice.settings.tx_gpio = 'GPIO14';
instance.iodevice.settings.baud = uint32(115200);
project.instances = instance;
sfun = c2837x_block_render_sfun_files(project);
pc = c2837x_block_render_pc_files(project);
generated = fullfile(root, 'generated');
mkdir(generated);
write_bytes(fullfile(generated, 'axis_alpha_sfun.c'), sfun.sfun_source_bytes);
write_bytes(fullfile(generated, 'axis_alpha_sfun.h'), sfun.sfun_header_bytes);
write_bytes(fullfile(generated, 'axis_alpha_sfun_io.c'), sfun.io_source_bytes);
write_bytes(fullfile(generated, 'axis_alpha_sfun_config.h'), ...
    sfun.config_header_bytes);
write_bytes(fullfile(generated, 'axis_alpha_sfun_user_config.h'), ...
    unicode2native(sprintf([ ...
    '#define CONNECT_TIMEOUT_MS 500u\n' ...
    '#define STEP_TIMEOUT_MS 100u\n' ...
    '#define TERMINATE_TIMEOUT_MS 50u\n']), 'UTF-8'));
write_bytes(fullfile(generated, 'axis_alpha_protocol.c'), ...
    pc.protocol_source_bytes);
write_bytes(fullfile(generated, 'axis_alpha_protocol.h'), ...
    pc.protocol_header_bytes);
    write_bytes(fullfile(generated, 'axis_alpha_pc_error.h'), ...
        pc.pc_error_header_bytes);
    write_bytes(fullfile(generated, 'axis_alpha_pc_serial.h'), ...
        pc.serial_header_bytes);
support = fullfile(repositoryRoot, 'tests', 'app', 'support', 'sci_host');
gcc = 'E:\\Mingw_w64\\mingw64\\bin\\gcc.exe';
testCase.assertTrue(isfile(gcc), 'The configured MinGW gcc is required.');
executable = fullfile(root, 'sci_sfun_host_fixture.exe');
fixture = fullfile(support, 'sci_sfun_host_fixture.c');
serial = fullfile(support, 'sci_sfun_host_serial.c');
command = sprintf([ ...
    '"%s" -std=c11 -Wall -Wextra -Werror -pedantic-errors ' ...
    '-DMATLAB_MEX_FILE -I"%s" -I"%s" -I"%s" ' ...
    '"%s" "%s" -o "%s" 2>&1'], gcc, generated, ...
    fullfile(repositoryRoot, 'simulink'), support, fixture, serial, ...
    executable);
[status, compileOutput] = system(command);
testCase.assertEqual(status, 0, compileOutput);
[status, output] = system(sprintf('"%s" 2>&1', executable));
testCase.verifyEqual(status, 0, output);
end

function evidence = run_sci_production_binding(testCase)
root = c2837x_block_normalize_absolute_path(tempname);
mkdir(root);
testCase.addTeardown(@() rmdir(root, 's'));
sci = render_instance('sci');
generated = fullfile(root, 'generated');
mkdir(generated);
protocolSource = fullfile(generated, 'axis_alpha_protocol.c');
protocolHeader = fullfile(generated, 'axis_alpha_protocol.h');
serialSource = fullfile(generated, 'axis_alpha_pc_serial.c');
serialHeader = fullfile(generated, 'axis_alpha_pc_serial.h');
pcError = fullfile(generated, 'axis_alpha_pc_error.h');
write_bytes(protocolSource, unicode2native(sci.protocol, 'UTF-8'));
write_bytes(protocolHeader, unicode2native(sci.protocolHeader, 'UTF-8'));
write_bytes(serialSource, unicode2native(sci.serialSource, 'UTF-8'));
write_bytes(serialHeader, unicode2native(sci.serialHeader, 'UTF-8'));
write_bytes(pcError, unicode2native(sci.pcError, 'UTF-8'));

gcc = 'E:\\Mingw_w64\\mingw64\\bin\\gcc.exe';
testCase.assertTrue(isfile(gcc), 'The configured MinGW gcc is required.');
protocolObject = fullfile(root, 'axis_alpha_protocol.o');
serialObject = fullfile(root, 'c2837x_block_pc_serial.o');
common = sprintf([ ...
    '"%s" -std=c11 -Wall -Wextra -Werror -Wno-unused-function ' ...
    '-pedantic-errors -DC2837X_PC_SERIAL_TEST_SEAM ' ...
    '-I"%s" -c'], gcc, generated);
protocolCommand = sprintf('%s "%s" -o "%s" 2>&1', common, ...
    protocolSource, protocolObject);
serialCommand = sprintf('%s "%s" -o "%s" 2>&1', common, ...
    serialSource, serialObject);
[protocolStatus, protocolOutput] = system(protocolCommand);
[serialStatus, serialOutput] = system(serialCommand);
evidence = struct( ...
    'protocol_status', protocolStatus, ...
    'serial_status', serialStatus, ...
    'output', sprintf([ ...
    'PROTOCOL_COMMAND: %s\n%s\nSERIAL_COMMAND: %s\n%s\n' ...
    'GENERATED_SERIAL_HEADER: %s\nGENERATED_PC_ERROR: %s'], ...
    protocolCommand, protocolOutput, serialCommand, serialOutput, ...
    serialHeader, pcError));
end

function write_bytes(path, bytes)
file = fopen(path, 'wb');
assert(file >= 0);
cleanup = onCleanup(@() fclose(file));
fwrite(file, bytes, 'uint8');
clear cleanup
end

function value = section(text, startToken, endToken)
startPosition = strfind(text, startToken);
endPosition = strfind(text, endToken);
assert(isscalar(startPosition) && isscalar(endPosition) && ...
    startPosition < endPosition);
value = text(startPosition:endPosition - 1);
end

function verify_order(testCase, text, tokens)
positions = cellfun(@(token) strfind(text, token), tokens, ...
    'UniformOutput', false);
testCase.verifyTrue(all(cellfun(@(position) isscalar(position), positions)));
testCase.verifyTrue(issorted(cell2mat(positions)));
end
